[[appendix]]
= Appendix

[[ii.-mano-and-citta]]
II. _Mano_ and _Citta_
~~~~~~~~~~~~~~~~~~~~~~

a.  The English word 'mind' is rather carelessly used to denote the Pali
terms _mano_ and __citta__. __Mano__, in strict terminology, refers to a
particular base (__āyatana__) just as much as _cakkhu_ (eye) does. On
the basis of these certain perceptions come about Based on the eye there
is seeing; likewise based on _mano_ there is thinking. That is why the
Buddha always teaches six such bases - these being the six internal
bases (__ajjattikāni āyatanani__), viz., eye-base (__cakkhāyatana__),
ear-base (__sotāyatana__), nose-base (__ghānāyatana__), tongue-base
(__jivhāyatana__), body-base (__kāyāyatana__) and mind-base
(__manāyatana__).

The eye-base refers to two very conspicuous round lumps of flesh
situated in the head; the ear-base refers to a membrane called the
ear-drum and a flesh flap projecting out of the head. Likewise, the
mind-base can be considered to be, in the main, what is referred to as
the grey-matter in the head. This description of the mind-base, however,
appears inadequate, for the reason that though there can be no hearing
based on the eye-base or no seeing based on the ear-base (and so with
three other bases), there can be seeing, hearing, smelling, tasting and
touching based on the mind- base. In other words, based on the mind-base
there can be imaginary sights, imaginary sounds, imaginary smells,
imaginary tastes and imaginary touch. Therefore, from this point of
view, the mind-base can also be regarded as a collection of imaginary
internal bases based on which imaginary percepts come about.

Occasionally we find _mano_ being indifferently used to refer to
imagination or thinking in the same manner that the English word 'mind'
is used to refer to thinking.

a.  _Citta_ refers to thinking or to mentality. The relationship that
_citta_ bears to _mano_ is similar to that which, for instance, the eye
bears to seeing.

Derived from _citta_ is the word _cetasika_ which means __mental__. In
the _Sutta_ we further find a dual classification into _kāyika_ (bodily)
and _cetasika_ (mental). But this is quite different from the erroneous
but common classification called "mind-and-body" (or "mind-and-matter")
wherein mind and body are conceived as two things independent of each
other and together constituting the living individual.

There is also no justification for reckoning _citta_ to be the same as
__viññāna__. _Citta_ involves __viññāna__. But that does not mean it is
the same as __viññāna__.

[[ii.-manosankhara-and-cittasankhara]]
II. _Manosankhara_ and _Cittasankhara_
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

In the _Kukkuravatiya Sutta_ (__Majjhima Nikāya 57__) and else where we
get the triad __kāyasaṅkhāra__, _vacīsaṅkhāra_ and _manosaṅkhāra_ as
against the triad __kāyasaṅkhāra__, _vacīsaṅkhāra_ and _cittasaṅkhāra_
that appears in the _paṭiccasamuppāda_ exemplification. The former
triad, it should be noted, is not the same as the latter.

In the triad __kāyasaṅkhāra__, _vacīsaṅkhāra_ and __manosaṅkhāra__, the
word _saṅkhāra_ refers to _cetanā_ (intention). This can be seen from
the __Saṃyutta Nikāya II__, __Abhisamaya Saṁyutta__, __Dasabala Vagga__,
Sutta No. 5, where __kāyasaṅkhāra__, _vacīsaṅkhāra_ and _manosaṅkhāra_
refer to __kāyasaṅcetanā__, _vacīsaṅcetanā_ and __manosaṅcetanā__, and
this applies to the use of the triad in the _Kukkuravatiya Sutta_ too.

[[iii.-attā]]
III. ATTĀ
~~~~~~~~~

It will be seen that the Buddha does not give much weight to the many
speculations regarding 'self' (__attā__). He just dismisses them as
wrong views (__miccādiṭṭhi__). What he _does_ give weight to is the
_notion_ of 'self', which fundamentally is nothing but a notion of
mastery (__vasa__), or in other words, a notion of existing __as
desired__. Some thing is considered as 'self' means that thing is
considered as being readily amenable to altering its existence to suit
one's wish. "If, monks, this body were 'self', then you should be able
to have 'Let my body be thus, let my body be not thus'." The same
applies to Feeling, Perception, _Determinations_ and Consciousness. In
the __puthujjana__'s conscious life it is just this notion of mastery
that _leads_ him on and not those speculations such as 'Self is eternal'
or 'Self is not eternal' or 'Self is conscious', etc. which he indulges
in during his moments of speculation. The _puthujjana_ can well be
divorced from these speculations, but certainly not from the notion that
he has mastery over the Five Grasping Groups. He is constantly thinking
and acting as if he wields power over these Groups. And the many
speculations about 'self' have their origin also in this notion of
mastery, a notion for which the _puthujjana_ has passion. He is
possessed (__pariyuṭṭhaṭṭhāyī__) by it. His very being is sunk in this
notion. When this notion is removed there is no room whatever for any of
the speculations regarding 'self' to arise.

When one sees that this notion of mastery is a false notion, or that one
has really no power over the Grasping Groups to make them behave in
accordance with one's wishes, or again that the Grasping Groups are
Not-self (__anattā__), then one begins to get tired of them, to get
wearied (__nibbida__) of them, to be disenchanted with them, to be
detached (__virāga__) from them. This seeing leads one on
(__opanayika__) to seeing Suffering and the cessation of Suffering.

This notion of mastery is also immediately visible (__sandiṭṭhika__) in
one's experience. As against this none of the many speculations about
'self' are either _opanayika_ or __sandiṭṭhika__. This should also make
it clear why the Buddha pays hardly any attention to these many
speculations.

Holding to belief in 'self' (__attavādupādana__) is dependent on
__bhava-tanhā__. The stronger the individual's _bhava-tanhā_ is the
harder does he adhere to some view or other about ’self‘.

[[edited-up-to-here]]
*edited up to here*
-------------------

[[iv.-saddha]]
IV. SADDHA
~~~~~~~~~~

Saddhā is one of the five faculties, and the Buddha states that; the
puthujjana has none of these faculties. It is, however, sometimes
thought that a puthujjana can have saddha.ThiS is not so. With regard to
the Buddha, Dhamma and Sangha, what such a person may have is what is
referred to by the Sanskrit word bhakti, i.e. belief tinged with a
certain quantum of emotion, or at a higher level what he may have is
what is referred to in the Suttas as Cittappasāda, i.e. gladdening, or
being pleased in mind. One can have belief in a doctrine or be pleased
about a doctrine even though one does not really see it or understand
it.

On a certain occasion (obviously when Ananda was still a puthujJ'ana)
the Buddha said that if Ananda dies just at that time, Ananda would
bereborn seven times the king of the gods and seven times the king of
India by reason of the Cittappasāda Ananda had towards the Buddha. Note
that the word used is cittappasāda and not isaddhā. (See Anguttara
Nikāya I, Tika Nipāta, Ānanda Vagga, Sutta N0. I0).

Saddhā is bom of seeing and understanding the Dhamma, and it exists
alongside the other four faculties of sati, vīn'ya, paññā, and samādhi
There seems to be no precise English equivalent for this word. The words
'faith' and belief do not by themselves always carry the right meaning.
There can be rational faith or irrational faith, rational belief or
irrational belief. Saddhā refers to a particular kind of faith or
belief. It is that faith or belief in the Dhamma which is a result of
seeing and understanding the DhaInma. For exaInple, even though the
sekha does not experience the amata (deathlesSneSS) he has saddhā in the
amata; and that is because he sees and understands the amata.

[[v.-sankhāra-and-sankhata]]
V. SANKHĀRA AND SANKHATA
~~~~~~~~~~~~~~~~~~~~~~~~

It is not uncommon to see saṅkhāra being mistaken for saṅkhata Sarikhāra
means something which determines some other thing, whilst saṅkhata
refers to that which is determined Immense difficulty can result if
these two things are confused.

[[vi.-nirodha-tanhā]]
VI. NIRODHA-TANHĀ
~~~~~~~~~~~~~~~~~

In the Sangīti Sutta (Dīgha Nikāya 33} are given three groupings of
tanhā. One group consists of the following three classes of tanhā:
rupa-tanhā, arūpa-tanhā, and nirodha-tankā. Nirodha means cessazi0n.
But, for this reason it must not be thought that nirodha-tamhā means
tanhā for Nibbāna. Nibbāna is tanhakkhaya, i.e. it is the destruction of
tanhā Tanhā refers to the puthujJ'ana’s wanting, and that is essentially
a wanting sense- pleasure and 'self3existence.

To have tanhā for Nibbāna means to have tanhā for the destniction of
tanhā. In other words it means to want sense- pleasure and
'Self-'exiStence so as to destroy wanting sense- pleasure and
'self'-existence Such a state of affairs cannot be.

In the same Sutta are mentioned nine kinds of nir0dha, the first being
kāma-sārīna nirodha (cessation of the perception of sense-pleaSure),
which is a characteristic of the first jhāna. Tanhā for this cessation,
Viz. the cessation of the perception of sense- pleasure, is really a
tanhā for 'sellexistence in the first jhāna Thus nirodha-tanhā is a
negative fonn of the positive bhava- tanhā. It is like saying that a
person wants the cessation of unpleasant feeling so that his existence
comprises only pleasant and neutral feeling When he says he wants the
cessation of unpleasant feeling what he really means is that he wants
the existence of pleasant and neutral feeling His wanting a particular
postitive existence is put in the form of wanting a certain thing to be
absent in his existence Nirodha-tanhā therefore means tanhā for that
bhava wherein the specified thing has ceased.

[[vii.-vibhava-tanha]]
VII. VIBHAVA-TANHA
~~~~~~~~~~~~~~~~~~

Apart from avijJ'ā, what really lies at the bottom of vibhava- tanhā is
a dissatisfaction with the past, present and expected future experience
The puthujjanā is dissatisfied with his past; he is dissatisfied with
the present; and he cannot see any satisfaction in the future which he
knows will be decay and death. ln other words, he is dissatisfied with
the sakkāya, past, present and future.

Unfortunately, he knows no escape from the sakkāya He does not know
sakkāyanir0dha.Under the circumstances he seeks consolation by doubting
the reality of the sakkāya which of course is nothing but a doubting the
reality of his own existence; and on this basis he logically tries to
find a way out. In this attempt he gets very close to the view of no
existence fi Nevertheless, having sakkāyadiṭṭhi he cannot doubtlessly
accept that he does not exist. He is therefore caught in a duality - the
duality of is and is not - a duality which in extremist thinking points
to eternalism (sasata) on the one hand and to nihilism (uccedha) on the
other. So, without applying his view of nihilism to present living he
goes beyong (atidhāvati) and applies it to a future time, i.e. to after
death. He does so because he thinks he has better reason to apply his
view to after death than to present liVing. He therefore consoles
himself and falls into complacency by thinking that he will be fully and
completely cut off at death. Actually he is not convinced about it, and
he has fears regarding the matter. But at least he finds some
consolation in thinking that everything is completely over at death.

Vibhava-tanhā is the wanting a complete cutting off of the sakkāya at
death. But this kind of tamhā is as undersirable as bhava-tanhā because
it does not give one any opportunity what- soever to experience
sakkāyanirodha which is nothing but the experience of the cessation of
Suffering. Let alone experiencing the cessation of Suffering it does not
give one any opportunity whatsoever to even see the cessation of
Suffering. Vibhava-tanhā will merely keep Suffering going on till death.
It cannot bring Suffering to an end. One's present problem of Suffering
just remains with no prospect whatever of a solution.

[[viii.-puthujjana]]
VIII. PUTHUJJANA
~~~~~~~~~~~~~~~~

When the puthujjana experiences Suffering (i.e. when he is grieved, or
agitated, or wonied, etc.) at a time he is considering some particular
thing as 'mine', he attempts to get away from that Suffering not by
considering that same thing as 'not mine' but by switching his mind over
to considering some other thing as 'mine'. Considering this other thing
as 'mine' may give him less Suffering, and also provide him with some
kind of temporary relief; but he is basically continuing to regard
things as 'mine'. Whether it is this that he is considering as 'mine' or
whether it is that, it hardly matters What matters is that the
considerations 'mine' is persisting in him unbroken. Thus he is in no
way going towards the extinction of Suffering as the Ariyan disciple who
considers things as 'not mine' is.

One must even for a brief period consider some thing which _ one has
been considering as 'mine' as ' not mine'., One can then experience its
telling effect - how the agitation, worry, fear, etc. that were present
at the time of considering it as 'mine' immediately subside as the
considering of it as ‘not mine' sets in.

Incidenta11y, we have said that 'mine' points to 'I' . Expanded, this
statement would be: 'is mine' points to '1 am'. Since 'iS mine' is the
same as 'for me' (in fact the Pali word me refers to both 'mine' and
'for me'), we also have 'for me' points to 'I am'. The puthujjanā sees
these things the other way about.

[[ix.-upadisesa]]
IX. UPADISESA
~~~~~~~~~~~~~

Upādisesa means residue or that which is remaining.

HoweVer, we find this word used in the Suttas to refer to two different
things that remain. Usually it refers to the pancakkhandha (the Five
GroupS) which is what is remaining with regard to the Arahat. But, for
instance, in the Satipatthāna Sutta (MajJ'hima Nikāya ]O) it is used to
refer to that which remains with regard to the anāgāmi In the fomter
case it denotes the difference between sa-upādisesa nibbānadhātu and
anupādisesā nibbānadhātu (see page 1 O4). In the latter case it denotes
the difference between the anāgāmi and the Arahat. These two differences
are by no means the same. Thus, the word upādiseso does not specify what
remains. For this reason Nānavīra Thera considers that upādisesā must be
unspecified residue.

[[x.-upādāya-rūpam]]
X. UPĀDĀYA RŪPAM
~~~~~~~~~~~~~~~~

With reference to the rāpupādānakkhanda in the pancupādānakkhandha we
get the phrase upādāya rūpam This phrase which means "by grasping rāpa”
is often seen translated as "de1ived from rI2pa", or as "becauSe of
rūpa",or again as "by- product of rūpa¥ This is seriously misleading for
with regard to the first Group, it immediately shuts the door to the
problem of Suffering and the cessation of Suffering.

In the Upādānam Pariva_t_tam Sutta (Sar_nyutza Nikāya III, Khandha
Saṃyutta, Upāya vagga) we get the following paSsages:

*Katamañca bhikkhave rI1pam. Catntāro ca mahābhūtā catunnam ca
mahābhātānam upādāya rāpam, idam vuccati bhikkhave rūparh, Ahārasamudayā
r11pasamudayO, āhāranirodhā rāpanirOdh0. Ayam eva ariyo aḷṭhangiko
maggorāpanirodhagāmini pa_tipadā, seyyathīdam.‘ sammādiḷghi . .
sammāsamādhi

Ye hi keci bhikkhave samānā va brahmanā va evam rūpam abhiññāya evam
rāpasamudayam abhiññāya evam rāpanirodham abhiññāya evam
rlipanirodhagāminim pa_tipadarh abhirīrīāya rūpassa nibbidāya virāgāya
nirodhāya paṭipannā te supaṭipannā Ye supaḷipannā te imasmim
dhammavinaye gādhanti.*

The translation would be:

____
"What, monks, is rūpa ? The Fou1=~Primary Modes and that rūpa by
grasping the Four Primary Modes - thiS, monks, is called rūpa By the
arising of the nutriment, the arising of rupa,' by the cessation of the
nutriment, the cessation of rI1pa. The path that leads to the cessation
of rūpa is this Noble Eightfold Pathg that is to say, right view . .
right concentration."

"WhosoVer recluses and brahamins, monks, having fully understood rūpa
thus, having fully understood the arising of rūpa thus, having fully
understood the cessation of rūpa thus, having understood the path
leading to the cessaion of rūpa thuS, have attained to wearineSs, to
detaChment, to cessation of rūpa they have well attained. Whosoever have
well attained, they are grounded in this Dhamma and Discip1ine." ,
____

At once we see the Buddha indicating the arising of Suffering and the
cessation of Suffering with regard to rĪ1pa. The Suffering is in the
upādāya i.e. in the Grasping; and the cessation of Suffering is in the
abhiññāya i.e. in the fully understanding Certain other Sutta passages
conceming rūpa are those defining the Four Primary Modes. One such
passage (defining the Earth Mode) iS:

_Katamā ca, bhikku, paḷhavīdhātu? Paḷhavidhātu siyā ajjhattikā siyā
bāhirā Katamā ca, bhikku, ajjhattikā pa_thavidhātu? Yam ajjhattam
paccattam kakkhaḷām kharigatam upādinnam, seyya thīdamf kesā lomā nakhā
dantā taco mamsam nahārū a_t_thi aṭṭhimiñjā vakkam hadayam yakanam
kilomakam phihakam papphasam antam antagunam udariyam karisam,‘ yam vā
pan' aññam pi kiñci ajjhattam paccattam kakkhaḷām kharigatam upādinnam,'
- ayam vuccati, bhikkhu, ajjhattikā pa_thavīdhātu. Yā C’ eva kho pana
ajjhattikā pathavī dhātu, ya ca bāhirā pathavīdhātu paḷhavidhātur ev’
esā, tam.‘ N'etam mama, n'esO 'ham asmi, na me s0 attā ti , evam etam
yathābhātam sammappaññāya daṭṭhabbām Evam etam yathābhūtam sammappaññāya
disvā pathavīdhātuyā nibbindati, pathavīdhātuyā cittam virājeti_

The translation would be:

____
"And what, monks, is the Earth-Mode. The Earth-Mode may be internal, may
be extemal . And what , monks, is the internal Earth-Mode? Whatever is
hard, solid, is intema1, grasped by oneself, that is to sayz the hair of
the head, the hair of the body, nails, teeth, skin, flesh, sinews,
bones, marrow of the bones, kidneyS, heart, liver, pleura, Spleen,
lungs, intestines, mesentary, Stomach, excrement, or whatever other
thing is hard, solid, is intemal, grasped by oneself - thiS, monks, is
called the intemal Earth-Mode. Whatever is the intemal Earth-Mode and
whatever is the external Earth-Mode, just these are the Earth-Mode. By
wisdom this should be regarded as it really is, thus: 'Not, this is
mine; not, this am I; not, this is my self. Having by wisdom seen this
thus as it really is, he wearies himself of the Earth- Mode, he detaches
his thinking from the Earth-Mode."
____

Here again, we see the Buddha indicating Suffering and its ceSsation.
The latter part of this passage wherein the Buddha exhorts the disciple
to regard the Mode as 'Not, this is mine; not, this am I; not, this is
my self and thereby detach his thinking (cittarh virājeti) from the Mode
has meaning only from the fact of the Mode being grasped (upādz'nnar'n).
If the word upādinnaṁ is reckoned to mean "because oF' or "derived from"
the whole meaning and purpose of the Sutta passage is lost. It is
because the Mode is grasped (i.e. it is considered as 'mine' and the
individual has attachment (raga) to it) that he has to regard it as
'Not, this is mine; not, this am I; not, this is my self and get
detached from it.

In the Saṃyutza Nikāya IV, Salāyalana Sar_nyuzta, Navapurana Vagga,
Sutta N0. ] the phrase anukampam upādāya appears. It means "taking up
Sympathy". But we should not take upādāya herein precisely the same
sense in which the word is used in reference to the pancupādānakkhandha
The Arahat takes sympathy, but that does not mean he takes sympathy in
the sense of considering sympathy as 'mine'. There is no 'my Sympathy'
or '1 am in Sympathy' with the Arahat. In the phraseanukampafn upādāya
the word upādāya is rather indifferently used. It is again dm to that
elasticity of language, often present in dialogue Axothcr place where
the word upādānā is used without bring given exactly the same meaning as
in pancupādānakkhandha is the Aggivacchagotta Sutta, Majjhima Nikāya 72.
In this Sutta we get the phrase ayaṁ aggi tinakagḷhupādānafn paricca
jtL7atzIi, which means, "this fire is burning dependent on taking up
grass and Sticks." Perhaps, the use of upādāya and upādāna is such
places has been one of the reasons for thinking that in the phrase
upādāya rāpaṁ too the word upādāya need not be taken in the same sense
in which it is to be taken in reference to the pancupādānakkhandhā.

[[xi.-invalid-questions]]
XI. INVALID QUESTIONS
~~~~~~~~~~~~~~~~~~~~~

What happens to the Arahat after death ? Does he exist ? Does he not
exist ? etc.

The Buddha says that these questions, likewise such questions as, Does
self exist ? Does self not exist ? IS the world etemal? ls the world not
etemal ?Are asked through not understanding the DhaInma, or through
delighting in and being attached to the Groups (See Samyutta Nikāya III,
Vacchagotta Saṃyulta and Saṃyutta Nikāya IV, Avyākata Saṃyutta, Sutta
N0. 6).

V The person who asks the question as to what will happen to the Arahat
after death is really asking the following questionz What will happen to
mz after death if 1 become Arahat ? It is an answer to this question
that he is really seeking. The attachment to the Groups lies latent and
unnoticed by the queStioner. Although in the question, the questioner
does not indicate the involment of any subjectivity (i.e. he does not
indicate in the question that he himself is involved), the fact is that
he as a subject is invo1ved. He wants to know what will happen to him
after death if he becomes Arahat. Since the questioner is a puthujjana
the question appears valid I0 him, and so he keeps on asking it. Not
seeing the pancupādānakkhand/1a. as pczncupādānakkhandha and the
pancakkhandha as pancakkhandha he puts forth these questions. But if he
does see the pancupādānakkhandha and the pancakkhandha he cannot and
will not ask these questions, for he then knows that since all
subjectivity and attachment are extinct with the Arahat, they are
invalid questions. Actually, the thinking of one who sees the Dhamma
does not go beyond Arahatship.

The puthL£jJana, whether he be a philosopher, ethicist, ascetic, or
anyone elSe, does not see that these questions about the Arahat, self
and the world are unjustified He assumes he is justified in asking them,
and so he keeps on asking them. At the same time he sees that n0 answer
to any one of them is justifiable He can proceed no fuIther, and so his
thinking ends in frustration.

The Buddha also does not answer these questions. But he shows how and
why they arise When this is seen the invalidity of the questions is
seen. When their invalidity is seen the questions are no longer asked.
Thus does the Buddha rescue the thinker from frustration - not by
answering unanswerable questions, but by bringing him to the cessation
of all such questions That is also why the Buddha's Teaching is 'beyond
the world' (lOkuttara). It is beyond the world of the put/wjjana, and
hence beyond his comprehension.

[[xii.-dassana]]
XII. DASSANA
~~~~~~~~~~~~

ln the Sabbāsava Sulta, Majjhima Nikāya 2, it is said that adherence to
rites and ritual, doubt, and 'person'-view are to be laid aside by
seeing (dassanZ1).

This means, that one has to see that adherence to rites and ritual,
doubt (about the Dhamma), and having 'person'-view prevent the cessation
of Suffering This seeing is not quite as easy and simple as it would
appear to be. It is not to be achieved through a process of conceptual
or logical thinking. Nor is it to be achieved by any kind of scholarly
analySis. Only a sustained effort at looking deep down into the very
depths of one's own personal exiStence, can bring about this seeing
Actually, with this seeing the Four Noble Truths are also seen; and this
is what is meant by the arising of the Dhamma-Eye (dhammaCakkhuṁ
udapādi).

Further if one is to enter the Path adherence to rites and ritua1, doubt
and 'person’- view must be done away with. For this reason it is a
matter of the highest importance.

[[xiii.-rebirth]]
XIII. REBIRTH
~~~~~~~~~~~~~

It Should be noted that the Suttas do not explain how rebirth takes
place. They only tell us that so long as a being dies with Ignorance and
Ianhā there is a new bhavā springing up.

Conceptually thinking out how rebirth takes place (the mechanics of it,
so to say), with connections in time and spaCe, will not help. And any
attempt to do so can do more harm than good (as in fact has happened,
e.g. by going beyond the Suttas and introducing the concept of a
paḷisandhi viññāna). What one has to do, as the Buddha says, is to see
and understand one's present Suffering, how it arises, how it ceascS,
and the way to its cessation, and thereby reach the Path. The individual
who accomplishes this task will know that whatsoever rebirth will befall
him cannot be in an unfortunate sphere; and that, for him, is the most
important knowledge regarding rebirth. It is also a matter of experience
that as one begins to see Suffering and its cessation, one's thoughts
about rebirth (which are purely speculative unless one sees rebirth)
begin to recede into the background. In fact the phenomenon of rebinh
itself causes little concem to such a One.

lt should also be noted that the more one tries to make the Buddha's
Teaching a subject for scholarship the more confused one will become.
Subjects like rebirth will continue to bother such an individualy
Unanswerable questions about self and the world will continue to worry
him. In short he will remain in the same state of Suffering, and with no
prospect of reducing it.

The Buddha's Teaching is a medicine to be taken - a medicine, in the
taking of which one experiences its healing effect. AS a patient trusts
the physician and takes the medicine, so must one trust the Buddha and
follow his advice and guidance. "Let be the past, let be the future, I
will preach to you the Dhamma." (ti_t_t/tatu pubbanto titthatu aparanto
dhammam te deSeSsāmi).

[[xiv.-opanayika]]
XIV. OPANAYIKA
~~~~~~~~~~~~~~

The Buddha said that the Dhamma is well said (SvākhāI0) and leading on
(0panayikO). It leads on to seeing Suffering and the cessation of
Suffering, and of course to the subsequent experiencing of the cessation
of Suffering. These characteristics of the Dhamma, which are well
portrayed in the Suzzas, are however missing in a very large part of the
Abhidhamma. A knowledge of the large number of cetasika said to be
present in a particular citta is not all that conducive to solving the
problem of Suffering, which is not a problem whose solution can be seen
by pure and simple analysiS, however vast and imposing that analysis be.
Analysis for the sake of analysis gets one nowhere. It only results in
frustration Add to this the Abhidamma also incorporates a rather
misleading doctrine referred to as the ciztavīthi ("cOgnitive series").
It is difficult to see how these doctrines are Opanayika If they are not
0panayika, they are also not of much use.
