[[taṇhā-and-bhava]]
= Taṇhā and Bhava

We have seen that any actual present points to many possibilities. From
these possibilities conscious life makes a choice and exercises it. In
exercising the choice Consciousness finds its new footing.

The question now is: _What_ determines that particular choice and no
other? Why is it that at any given instant I choose to do this and not
any other?

The answer is simply that I _want_ that thing towards which _that_
particular action will lead me. Keeping the wanted thing in mind, or
wanting that thing, I take the action that will lead me to it. Of all
the courses of action available I select and pursue that particular
course of action which leads me to the wanted thing. Throughout the
action, the wanting lasts.

Now, a __puthujjana__’s want can be categorized under three main
headings called __kāma__, _bhava_ and __vibhava__. Wanting any one or
more of these things is called __tanhā__.

The word _tanhā_ is usually translated as Craving or Thirst. This
however, tends to give an inaccurate picture, since either of the words
Craving or Thirst gives the impression of an acute wanting. But wanting
__kāma__, _bhava_ or _vibhava_ in the _slightest_ degree is __tanhā__.
On the other hand the word _wanting_ is too wide to be used for
__tanhā__, since though the Arahat has _no tanhā_ he certainly has other
wants like wanting to eat food when hungry or wanting to rest when
tired. There seems to be no exact English equivalent to __tanhā__, so we
shall use it as it is.

The _puthujjana_ has __kāma-tanhā__, _bhava-tanhā_ and
__vibhava-tanhā__.

What now are __kāma__, _bhava_ and __vibhava__?

_Kāma_ is sense-pleasure,footnote:[Pleasure, it should be noted, is not
the feeling born of the senses. One can take pleasure in a feeling or
not take pleasure in it. Thus pleasure is a matter of one’s mental
attitude. The Buddha said that his mind was freed from the Canker of
sense-pleasure (__kāmāsavāpi citta vimuccitva__). Sight, sound, smell,
taste and touch are the strands of sense-pleasure (__kāmagunā__).] i.e.,
the pleasure connected with the senses. Wanting pleasure that arises in
connection with one or more of the senses is called __kāma-tanhā__.

What is __bhava__?

It is not possible to answer this question and indicate the meaning of
the answer effectively and with sufficient clarity unless the question
that was left unanswered in the first chapter is answered – the
question: As against the Five Grasping Groups could there be _just_ the
Five Groups?

The answer is: Yes.

The unique discovery that the Buddha made was just this: there could be
Five Groups _without_ Grasping. In other words, there could be an
individual (i.e., as distinct from other individuals) who has no notion
whatever of ‘self’, ‘I’ and ‘mine’. This individual is called Arahat
(__arahaṃ__). __The Arahat does not consider anything whatever as
‘mine’__. The Buddha experienced this state of affairs in himself. Thus
he was the first Arahat to have appeared in the world in our time.

_Bhava_ literally means ‘existence’ or ‘being’. But existence of what?
Being what? It refers to the __existence of ‘self’__, or to the notion
‘__I exist__’. Or we may say it refers to __being a ‘self’__, to __being
a subject (‘I’)__. Or yet, to the __existence of subjectivity__. A
life-mode completely devoid of all notions of ‘self’ and of thoughts of
‘I’ and ‘mine’ will _not_ be a __bhava__.

The _puthujjana_ looks upon his existence as ‘__my__ existence’. He
thinks ‘my self exists’ or ‘I exist’. This looking upon one’s existence
as ‘my existence’ or ‘existence of my self’ is called having
__bhavadiṭṭhi__. When there are no notions of ‘self’ no thoughts of ‘I’
and ‘mine’ there can be no such thing as ‘my existence’ and so on.

To speak very precisely, _bhava_ is the existence of the notions ‘self’
and ‘I’. Something is, of course, always identified as ‘self’ and ‘I’,
which again, is one or more of the Five Grasping Groups. But _bhava_ is
really a matter of one’s thinking just as much as Grasping (__upādāna__)
is.footnote:[This should not lead the reader to think that since _bhava_
and upādāna are really a matter of one’s thinking they can be easily got
rid of if necessary. If one completely gets rid of the thought ‘mine’ so
that it will never arise again, then one has become Arahat.]

It is the mind that is freed from the canker of __bhava__, just as it is
the mind that is freed from the cankers of sense-__pleasure__ and
Ignorance. The Buddha said that his mind was freed from the canker of
__bhava__: “Thus knowing, thus seeing, my mind was freed from the canker
of sense-pleasure, freed from the canker of __bhava__, freed from the
canker of Ignorance.”footnote:[Majjhima Nikāya 36.] He described himself
as “gone to the end of __bhava__” – __bhavassa
pāragu__.footnote:[Itivuttaka 100.] He did not say he was _going_ to the
end of __bhava__. He said that he had already _gone_ to the end of
__bhava__; which means he lives free from __bhava__. In him _bhava_ has
ceased. He is __bhavanirodha__, because he is completely free from
notions of ‘self’ and from thoughts of ‘I’ and ‘mine’. He does not look
upon his existence as ‘__my__ existence’. He does not think ‘__I__
exist’. Certainly he uses the _words_ ‘I’ and ‘mine’ for purposes of
conversation. But that is all. They are expressions current in the world
of which he makes use, but he is not at all affected by them.

The tendency to the conceit ‘I’ and ‘mine’
(__ahaṅkāramamaṅkāramānānusaya__) is not always apparent, for it is not
always on the surface. It lies deep-rooted and latent. It is something
that one perceives only when one reflects upon it. One does not perceive
it at all times even though it is present at all times lying behind
one’s thoughts and actions. In the Buddha, and in the Arahats, this
tendency is completely uprooted, never to arise again. When all thoughts
of ‘I’ and ‘mine’ are extinct and do not arise again, ‘my existence’ or
‘I exist’ are also extinct and do not arise again.

The Arahat “has gone beyond all __bhava__” – __upaccagā
sabbabhavāni__.footnote:[Udāna, Nanda Vagga, Sutta No. 10.] The Arahat
Maha Kassapa declared that he had “escaped from __bhava__” –
__bhavābhinissato__.footnote:[Theragāthā 1089.] _Bhava_ ceases with the
attainment of Arahatship. Thereafter the Arahat lives freed from
__bhava__, delivered from __bhava__. Before the ascetic Gotama attained
Arahatship all life that existed was __bhava__. With his attaining
Arahatship there came to be for the first time in the world a life free
of __bhava__.

_Bhava_ is also called a fetter. This fetter is completely cut off and
destroyed in the Arahat. He is
__parikkhīnabhavasaññojano__.footnote:[Saṃyutta Nikāya III, Khandha
Saṃyutta, Anta Vagga, Sutta No. 8.]

If _bhava_ means ‘existence’ pure and simple, then the living Arahat
cannot have completely destroyed __bhava__, for as a living Arahat there
is an ‘existence’.footnote:[See page 56. FIXME: add link] The living
Arahat has ‘existence’, but no __bhava__. He is __bhava__-ceased.
_Bhava_ refers to the existence of _all_ modes of life _other than_ that
of the Arahats, simply because all such modes of life, save the
Arahat’s, are a case of ’__my__ existence’ or ‘self’-existence to some
degree or other.

If the precise meaning of _bhava_ is not understood there can be much
confusion with regard to the Buddha’s Teaching, particularly when it
comes to the Doctrine of Dependent Arising (__paṭiccasamuppāda__). The
Teaching will then become either a matter of faith, which will remain
beyond reach here, or a hypothesis left for future verification. But the
Buddha’s Teaching is neither a matter of faith nor a matter of
hypothesis. It is a teaching to be experienced here and now, all of it,
from beginning to end.

As with the word __tanhā__, there does not seem to be an exact
equivalent in English for the word __bhava__. This word is usually
translated as ‘becoming’ or ‘existence’ – all of which miss the
point.footnote:[Sometimes _bhava_ is seen translated as rebirth! The
extent to which the meaning of the Suttas (Discourses) is hidden from
the reader by such inaccuracies can thus be seen.] We shall therefore
keep to the Pāi word __bhava__.

Wanting __bhava__, i.e., wanting ‘self’-existence or ‘my existence’ is
__bhava-tanhā__.

_Vibhava_ is not so straightforward as __bhava__.

Some thinkers, in their search for truth, want to be quite certain of
everything they take to be true. They begin by doubting everything,
including their very existence. But by doubting their own existence they
very cleverly deceive themselves for the simple reason that their very
doubting proves their existence. To doubt also one must exist. _Vibhava_
stems out of this type of thinking. It is a denial of existence.
Existence denies itself. But this denial of existence only leads to a
confirmation of existence. It does _not_ lead to _cessation_ of
existence.

Since, perhaps, it appears insane to deny existence whilst being
existent, this tendency to denial is pushed back (__atidhāvati__) to
‘after death’, and in the following manner a denial of existence is
made: “To the extent, revered Sir, that this self is of Form, is made up
of the Four Primary Modes, is from the union of the parents, is cut off
and destroyed on the dissolution of the body, and does not exist after
death, to that extent is there a complete cutting off of the
self.”footnote:[Dīgha Nikāya 1.]

This thinking, in the final analysis, only confirms ‘self’-existence.
Thus _vibhava_ – denial of ‘self’-existence – only confirms __bhava__,
only confirms ‘self’-existence. It does not lead to _cessation_ of
‘self’-existence. Just as _bhava_ is, _vibhava_ is also based on ‘self’
and on thoughts of ‘I’ and ‘mine’. “Those worthy recluses and brahmins
who lay down for beings the cutting off, the destruction, the denial of
_bhava_ (of ‘self’-existence), these, afraid of the ‘person’
(__sakkāya__), loathing the ‘person’, simply keep running and circling
round the ‘person’. Just as a dog that is tied by a leash to a strong
post keeps running and circling round the post, so do these worthy
recluses and brahmins, afraid of the ‘person’, loathing the ‘person’,
simply keep running and circling round the ‘person’.”footnote:[Majjhima
Nikāya 102.]

Wanting the cutting off of ‘self’-existence and the destruction of
‘self’-existence at death is called __vibhava-tanhā__.footnote:[See
Appendix on Vibhava-tanhā, pages 172 and 173. FIXME: add link] (It is an
undesirability because such a destruction of ‘self’-existence cannot be
got. ‘Self’-existence, or __bhava__, can be destroyed only by following
a particular training, i.e., by treading the Noble Eightfold Path.)

Just as much as grasping belief in ‘self’ is the most fundamental of the
four kinds of Grasping, wanting _bhava_ is the most fundamental of the
three kinds of __tanhā__.

Thus the __puthujjana__’s intentional action is determined by __tanhā__.
“So, Ānanda, action is the field, Consciousness the seed, and _tanhā_
the moisture.”footnote:[Anguttara Nikāya I, Tika Nipāta, Ānanda Vagga,
Sutta No. 6.] Just as moisture must be present for the seed to sprout up
out of the field, so must _tanhā_ be there for the __puthujjana__’s
Consciousness to arise from his intentional action. _Tanhā_ is one of
the most powerful factors that go into the fashioning of one’s life, yet
it is one factor that can be brought under immediate control. The
necessity to control _tanhā_ cannot be overstressed if one is to
progress. Hence the reason for the Buddha laying so much stress on it.

In the texts the words __tanhā__, __chanda__, _rāga_ and _nandi_ often
come together. There seems to be a tendency to consider the words
__chanda__, _rāga_ and _nandi_ as being almost identical with __tanhā__.
They are not “various shades of __tanhā__”. They have their own meaning.

_Chanda_ means desire, _rāga_ means attachment, and _nandi_ means
delight. Desire, attachment and delight are things dependent on
__tanhā__. Were there no kind of wanting sense-pleasures or
‘self’-existence there can be no desire or attachment or delight.

____
“Thus it is, Ānanda, that _tanhā_ arises dependent on feeling, pursuit
dependent on __tanhā__, gain dependent on pursuit decision dependent on
gain, _desire_ and _attachment_ dependent on decision, tenacity
dependent on desire and attachment, possession dependent on tenacity,
avarice dependent on possession, watch and ward dependent on avarice,
and many a bad and unskilled state of things such as blows and wounds,
strife, contradiction and retort, quarrelling, slander and lies arise
from keeping watch and ward.”footnote:[Dīgha Nikāya 15.]
____

Desire (__chanda__), attachment (__rāga__) and delight (__nandi__) have
also been referred to as Grasping (__upādāna__). “Friend, Visakha, that
desire and attachment there is in the Five Grasping Groups, that there,
is the Grasping.”footnote:[Majjhima Nikāya 44.] And, “Whatsoever there
is delight in Feeling, that is Grasping.”footnote:[Majjhima Nikāya 38.]
This means to say that grasping something also means desiring of it, or
being attached to it, or delighting in it. This is so because desiring,
or being attached, or delighting, is _in effect_ the same as regarding
as ‘mine’. It is a matter of direct experience that when desire,
attachment or delight exist ‘I’ and ‘mine’ also exist. It is only an ‘I’
that can desire something or be attached to it or delight in it.

__Tanhā__, desire, attachment, delight, are all supports for __bhava__.
‘__I__ exist’ or ‘__my__ existence’ stands supported by these. _Bhava_
hangs on these as its “cord”. They are called the “cord of __bhava__”
(__bhavanetti__). “Whatever desire, attachment, delight, __tanhā__,
whatever tendencies to determinations, attachments, and to the grasping
of various means there are in the mind, Radha, towards Form … Feeling …
Perception … Determinations … Consciousness, that is called the cord of
__bhava__. The cessation of these is the cessation of the cord of
__bhava__.”footnote:[Saṃyutta Nikāya III, Rādha Samyutta, Bhavanetti
Sutta.]

Just as a bunch of mangoes hanging by a stalk will fall down when the
stalk is cut, so will _bhava_ disappear when the cord of _bhava_ is cut.
The Buddha said that he stood with the cord of _bhava_ cut. Thus he
stood freed from __bhava__. “Just, monks, as when the stalk of a bunch
of mangoes has been cut, all the mangoes that were hanging on that stalk
go with it, just so, monks, the body of the Tathāgata stands with the
cord that binds it to _bhava_ cut
(__ucchinnabhavanettiko__).”footnote:[Dīgha Nikāya 1.]
