[[ch-00-notes-on-the-second-edition]]
= Notes on the Second Edition

This short book has been valuable for many of us in clarifying key points of the Dhamma.

The original publication has been out of print for a long time, and we wish to make it available again.
We feel that as the well-explained Teaching makes the Truth visible, good typography makes the Teaching readable,
and the contents are more accessible in the electronic formats commonly used today.

The pages were scanned, OCR-ed, the OCR errors corrected, and the contents formatted in the present volume.
The sutta references were transcribed to their currently used numbering system with hyperlinks to the online texts.

Italics are used for Pali terms, and the author's emphasis is formatted in *bold* to avoid being mixed up.

As for the translation of __āsava__, we replaced the term ‘cankers’,
(which was the translation used by I. B. Horner in the PTS editions)
with the currently more common term ‘taints’
(used by Bhikkhu Bodhi in the Wisdom Publications editions)
as the author was not discussing a particular choice of translation
and the latter is more easily recognizable to readers today.

2023 March
