[[ch-06-sankhara]]
= 6. Saṅkhāra

It is now necessary to discuss the key-word __saṅkhāra__, examine how it
appears in the various contexts, and determine whether a meaning to this
word which will comfortably accommodate all its applications could be
derived.

Below are six important uses of this word found in the Suttas:

Firstly, it is the name given to the fourth Group
__(saṅkhāra-kkhandha)__ which has been translated as the Group of
Determinations. This fourth Group is defined as __cetanā-kāya__, i.e.,
as intention-group. Thus, in the context of the fourth Group, _saṅkhāra_
is synonymous with intention __(cetanā)__.

Secondly, in the context of the Doctrine of Dependent Arising
__(paṭiccasamuppāda)__ where it occurs in __saṅkhārapaccayā viññānaṁ__,
it is defined as bodily-__saṅkhāra__, verbal-__saṅkhāra__ and
mental-__saṅkhāra__ thus:

[quote, role=quote]
____
What, monks, are the __saṅkhāra__? They are
the three __saṅkhāra__, namely, bodily-__saṅkhāra__, verbal-__saṅkhāra__
and mental-__saṅkhāra__. These, monks, are called the
__saṅkhāra__.

-- https://suttacentral.net/sn12.2/en/bodhi[SN 12.2], Analysis of Dependent Origination
____

These three kinds of _saṅkhāra_ are in turn defined in the
__Cūlavedalla Sutta__  as follows:

[quote, role=quote]
____
“Friend, Visākha, in-breathing and out-breathing are the
bodily-__saṅkhāra__. Discursive thinking is the verbal-__saṅkhāra__
Perception and Feeling are the mental-__saṅkhāra__.”

“Noble lady, for what reason are in-breathing and out- breathing the
bodily-__saṅkhāra__? For what reason is discursive thinking the
verbal-__saṅkhāra__? For what reason are Perception and Feeling the
mental-__saṅkhāra__?”

“Friend, Visākha, in-breathing and out-breathing are corporeal. These
are *closely connected with* __(paṭibaddhā)__ the body. Therefore they are
bodily-__saṅkhāra__. Having earlier had discursive thinking, one
subsequently utters words. Therefore discursive thinking is
verbal-__saṅkhāra__. Perception and Feeling are mental. These are
closely connected with the mind. Therefore they are mental-__saṅkhāra__.”

-- https://suttacentral.net/mn44/en/sujato[MN 44], The Shorter Classification
____

Thirdly, in the __Kukkuravatiya Sutta__, bodily-__saṅkhāra__,
verbal-__saṅkhāra__ and mental-__saṅkhāra__ appear in a somewhat different
context thus:

[quote, role=quote]
____
Here, Punna, someone determines a
bodily-__saṅkhāra__ that is harmful, determines a verbal-__saṅkhāra__
that is harmfu1, determines a mental-__saṅkhāra__ that is harmful. He
having determined a bodily-__saṅkhāra__ … a verbal-__saṅkhāra__ … a
mental-__saṅkhāra__ that is harmful, upbrings a world that is harmful.

-- https://suttacentral.net/mn57/en/bodhi[MN 57], The Dog-Duty Ascetic
____

Fourthly, in the context of the Doctrine of Dependent Arising, the
__Parivīmaṁsana Sutta__ contains _saṅkhāra_ as
meritorious-__saṅkhāra__, demeritorious-__saṅkhāra__, and
imperturbable-__saṅkhāra__, thus:

[quote, role=quote]
____
Were, monks, an ignorant individual
to determine a meritorious-__saṅkhāra__ his consciousness would go
towards merit. Were he to determine a demeritorious-__saṅkhāra__ his
consciousness would go towards demerit. Were he to determine an
imperturbable-__saṅkhāra__ his consciousness would go towards
imperturbability. A monk who has got rid of Ignorance and has attained
to Knowledge, monks, through such non-attachment to Ignorance and the
arising of Knowledge does not determine meritorious-__saṅkhāra__, does
not determine demeritorious-__saṅkhāra__, does not determine
imperturbable-__saṅkhāra__. Not determining, not intending, he grasps at
nothing in the world.

-- https://suttacentral.net/sn12.51/en/sujato[SN 12.51], Thorough Investigation
____

Fifthly, the __Khajjaniya Sutta__ identifies _saṅkhāra_ as the fourth Group thus.

[quote, role=quote]
____
Why, monks, do ye say __sahkhāra__? They determine __(abhisaṅkaronti)__
the determined. That is why they are called __saṅkhāra__. What is the
determined that they determine? Determined Form do they determine in
accordance with the nature of Form. Determined Feeling do they determine
in accordance with the nature of Feeling. Determined Perception do they
determine in accordance with the nature of Perception. Determined
Determinations do they determine in accordance with the nature of
Determinations. Determined Consciousness do they determine in accordance
with the nature of Consciousness. They determine the determined. That is
why they are called __saṅkhāra__.

-- https://suttacentral.net/sn22.79/en/bodhi[SN 22.79], Being Devoured
____

Sixthly, in the _Mahāvedalla Sutta_ (https://suttacentral.net/mn43/en/sujato[MN 43]) heat is called a life-__saṅkhāra__,
as that on which depends __(paṭicca)__ life.

It might assist the reader to see the above mentioned relationships
better if they are presented in the following manner:

FIXME: add figure.

Thus, firstly, _saṅkhāra_ is synonymous with intention as adopted in the
case of the fourth Group in the Five Groups. Secondly, in the
_Cūlavedalla Sutta_ we cannot equate _saṅkhāra_ entirely to intention.
Thirdly, the three kinds of _saṅkhāra_ mentioned in the _Kukkuravatiya
Sutta_ appear in the said Sutta as varieties of intentional action,
and therefore have a lot to do with intention. Fourthly, in the
__Parivīmaṁsana Sutta__, _saṅkhāra_ are again certainly some kind of
intention upon which the Consciousness of the ignorant individual
depends. Fifthly, in the __Khajjaniya Sutta__, _saṅkhāra_ (synonymous
with intention) are described as things that determine the Five Groups.
And, Sixthly, in the _Mahāvedalla Sutta_ life-__saṅkhāra__ is given as
heat upon which depends life.

Now, the words _paṭibaddhā_ in the _Cūlavedalla Sutta_ passage,
_abhisaṅkaronti_ in the _Khajjaniya Sutta_ passage, and _paṭicca_ in the
_Mahāvedalla Sutta_ passage are most indicative of what the word
_saṅkhāra_ means. It means:

- a thing to which some other thing is closely connected, or
- a thing upon which some other thing depends, or
- a thing without which some other thing cannot be, or
- a thing which determines some other thing.

__Saṅkhāra__, therefore, in short means: a determination,
or *necessary condition*. This one meaning covers all uses of this word.

What is meant by determination or *necessary condition* (that is to say,
__saṅkhāra__) must be distinctly understood. It means that whatever
thing depends upon this necessary condition, that thing can exist *only if*
this necessary condition is present. The thing cannot be present
without the necessary condition being present. If the necessary
condition is absent, then the thing is also absent. It should not be
understood as ‘once the necessary condition has come and gone the thing
arises’. Nor must it be understood as ‘the necessary condition *becomes*
the thing’. No. There is no *temporal* succession one after the other. If
the necessary condition is gone, then the thing is also gone. This is a
*structural principle*.

It should also be clearly understood that _saṅkhāra_ do not refer to the
things __(dhammā)__ for which they form necessary condition. The things
that are determined or upbuilt with the _saṅkhāra_ as necessary
condition are called _saṅkhatā dhammā_ (determined things). These
_saṅkhatā dhammā_ are, however, *of the nature of saṅkhāra*. That is
to say, these determined things in turn act as the necessary condition
for other determined things.

For example, the Six Bases are necessary
condition for Contact. This means that Contact cannot come about without
the presence of the Six Bases. Thus, in this instance, the Six Bases are
_saṅkhāra_ and Contact is a __saṅkhatā dhammā__. But again, Contact
which is on the one hand a _saṅkhatā dhammā_ is the necessary condition
for something else, viz., Feeling. Without Contact, no Feeling. Thus
Contact as a _saṅkhatā dhammā_ is also a __saṅkhāra__, dependent upon
which stands Feeling.

The same applies to the Five Grasping Groups. The
Five Grasping Groups are _saṅkhatā dhammā_ with _saṅkhāra_ (primarily,
intention) as necessary condition. But they are also the necessary
condition for something else, viz., Grasping. Thus, the Five Grasping
Groups are both _saṅkhatā dhammā_ and __saṅkhāra__. That is what is
meant by saying that all _saṅkhatā dhammā_ are in the nature of
__saṅkhāra__.

These implications of the word __saṅkhāra__, have to be clearly
understood. Quite a lot of the fanciful interpretations of the
Buddha-word are due to not understanding the precise meaning of the word
_saṅkhāra_ and the manner in which it is used in the Suttas.
