[[consciousness]]
Consciousness
-------------

In the elucidation of the Five Grasping Groups, Consciousness takes the
pride of place. The reason for that is that any _experience_ means
__being conscious of one or more of the other four Groups__. I am
conscious of Form (i.e. I am conscious either of my body or of an
external object or of both); I am conscious of Feeling; I am conscious
of Perception; and I am conscious of Determinations.“ It is as with the
choir-master of a five-member choir who himself, as the chief, takes up
his part and in the performance of the whole piece takes in himself
along with it.”

What now is Consciousness (__viññāna__)?

When I say I am conscious of something it means that that something is
_present_ to me. A sight, a sound, a smell, a taste, a touch, or an idea
is present. I am _aware_ of a certain perception, or the perception is
_present_ to me. I am conscious of it.

Sometimes Consciousness is seen equated to the subject to whom the
phenomenon is present. This is not correct. Consciousness does not refer
to the subject. Neither does it refer to the phenomenon nor to a part of
the phenomenon. It is not _what_ is present or a part of what is
present. It is only the _presence_ of the phenomenon. It is the presence
of that which is present. A feeling is present to me. Consciousness is
not the feeling. It is only the presence of the feeling. It is the being
conscious of the feeling Presence that is ‘mine’ or presence ‘for me’ is
Grasping-Consciousness (__upādāna-viññāna__).

Without sufficient reason, the Buddha says, no Consciousness arises.

____
“Consciousness, monks, is named after that in dependence on which it
comes into being.

* The Consciousness which comes into being in respect of sights in
dependence on the eye is called eye-consciousness;
* the Consciousness which comes into being in respect of sounds in
dependence on the ear is called ear-consciousness;
* the Consciousness which comes into being in respect of odours in
dependence on the nose is called nose-consciousness;
* the Consciousness which comes into being in respect of tastes in
dependence on the tongue is called tongue-consciousness;
* the Consciousness which comes into being in respect of touch in
dependence on the body is called body-consciousness;
* the Consciousness which comes into being in respect of ideas in
dependence on the mind is called mind-consciousness.”

“Just as, monks, fire is named after that independence on which it
burns. The fire that burns in dependence on logs of wood is called a
log-fire; the fire that burns in dependence on chips is called a
chip-fire; the fire that burns in dependence on grass is called a
grass-fire; the fire that burns in dependence on cow-dung is called a
cow-dung fire; the fire that burns in dependence on husks is called a
husk-fire; the fire that burns in dependence on rubbish is called a
rubbish-fire. In the same way, monks, Consciousness is named after that
in dependence on which it comes into being. The Consciousness that comes
into being in respect of sights in dependence on the eye is called
eye-consciousness …”footnote:[Majjhima Nikāya 38.]
____

The four Groups, Form, Feeling, Perception, Determinations, are called
the supports, or the footholds, or the base, for Consciousness.

____
"There are these five kinds of seed, monks. What five? Seed from root,
seed from trunk, seed from joints, seed from shoots, and seed from
grain.

"If, monks, these five kinds of seed were present undamaged, not rotten,
unspoiled by wind and heat, capable of sprouting, well preserved, but
there is no earth and water, would, monks, these five kinds of seed come
to growth, spread, and increase?"

“No, Lord.”

“If, monks, these five kinds of seed were damaged, rotten, spoilt by
wind and heat, incapable of sprouting, not well preserved, but there is
earth and water, would, monks, these five kinds of seed come to growth,
spread, and increase?”

“No, Lord.”

“If, monks, these five kinds of seed were undamaged, not rotten,
unspoiled by wind and heat, capable of sprouting, well preserved, and
there is earth and water, would, monks, these five kinds of seed come to
growth, spread and increase?”

“Yes, Lord.”

"As the earth, monks, should the four supports for the persistence of
Consciousness be regarded. As the water, monks, should delight and
attachment be regarded. As the five kinds of seed, monks, should the
nutritive Consciousness be regarded.

"If Consciousness persists, monks, it is by holding to Form that it
persists. With Form as object, with Form as support, in association with
delight, it attains to growth, spread and increase.

If Consciousness persists, monks, it is by holding to Feeling …
Perception … Determinations … that it attains to growth, spread and
increase."footnote:[SN III, Khandha Samyutta, Upāya Vagga, Sutta No. 2.]
____

The footholds for Consciousness can be viewed from a second angle. That
is through a dual classification of _internal_ and _external_ bases. The
six sense-bases, viz., the eye, the ear, the nose, the tongue, the body,
and the mind, are called the internal bases or the internal supports for
Consciousness, whilst those phenomena corresponding to these six
sense-bases, viz., sight, sound, smell, taste, touch and idea are called
the external bases or the external supports for Consciousness. The
latter are called external bases because they are largely dependent on
objects external to the corresponding internal base.

Consciousness and the other four Groups Cannot therefore be comprehended
from a standpoint outside of them by any method of objective synthesis
induction, and so on. Through themselves, and only through themselves,
i.e., by one’s own experience _only_ can they be understood.
