[[all-things-are-not-self]]
= All Things Are Not Self

FIXME update 'cankers' to 'taints' or 'outflows'?

The Buddha shows that a thing is impermanent by showing that the
necessary condition (or the __saṅkhāra__) upon which the thing depends
is impermanent.

This can be seen, for instance, in the __Pārileyya Sutta__.
The destruction of the cankers is spoken of, and the following passage occurs:

[quote, role=quote]
____
“Monks, how knowing, how seeing, is there without delay the destruction
of the cankers? Here, monks, the uninstructed _puthujjana_ not
discerning the Noble Ones, unskilled in the Noble Doctrine, untrained in
the Noble Doctrine, not disceming the Worthy Ones, not skilled in the
Doctrine of the Worthy Ones, regards Form as ‘self’. This regarding,
monks, is the __saṅkhāra__. This __saṅkhāra__, how does it result, how
does it arise, how is it born, and how is it produced? In the
uninstructed __puthujjana__, monks, nourished by feeling that is born
from Contact with Ignorance, arises __taṅhā__. Thence is born that
__saṅkhāra__. Thus, monks, that _saṅkhāra_ is impermanent, determined,
dependently arisen. That _taṅhā_ is impermanent, determined, dependently
arisen. That Contact is impermanent, is determined, is dependently
arisen. That Ignorance is impermanent, is determined, is dependently
arisen. Thus knowing, monks, thus seeing, is there without delay the
destruction of the cankers.”

-- https://suttacentral.net/sn22.81[SN 22.81], At Pārileyya
____

And so with the other Groups, Feeling, Perception, Determinations and
Consciousness.

Here, the cankers are the things (__dhammā__) considered. The necessary
condition for the cankers is the regarding of Form (or the other Groups)
as ‘self’. That is, regarding the Groups as ‘self’ is the _saṅkhāra_ for
the cankers. Thus we have: “This regarding, monks, is the __saṅkhāra__.”
The Buddha then goes on to show that the _saṅkhāra_ on which the cankers
depend is impermanent by showing that this _saṅkhāra_ in turn depends
upon certain other conditions for its own existence. So we have, “Thus,
monks, that _saṅkhāra_ impermanent, is determined, dependently arisen.”
When the impermanence of the _saṅkhāra_ called “regarding the groups as
‘self’” is seen, then the impermanence of the cankers which depend on
this _saṅkhāra_ is seen, and hence the possibility of their destruction
is seen.

In the above, the Buddha does not directly say that the cankers are
impermanent. He indicates the fact in an indirect manner. He shows that
the cankers are impermanent by showing that the _saṅkhāra_ which forms
the necessary condition for the cankers to exist is impermanent. I will
stop regarding the house I live in as permanent only if I see that the
constituents which form the necessary conditions for the house, i.e. the
foundation, the walls, the roof, etc., are impermanent. My being merely
told that the house is impermanent does not convince me of its
impermanence. That the house is impermanent is seen by me only by my
seeing that its constituent factors are impermanent. When the
constituent factors that go to make up the house are impermanent then
the house must necessarily be impermanent:

[quote, role=quote]
____
“Whatever cause, whatever condition there be for the arising of Form ...
Feeling ... Perception ... Determinations ... Consciousness, that is
impermanent. How can, monks, consciousness that is so composed of impermanent
things be permanent?”

-- https://suttacentral.net/sn22.18[SN 22.18], Impermanence With Its Cause
____

With regard to the other two characteristics of the
Grasping Groups, viz., Not-self and Suffering, the same applies. When
the _saṅkhāra_ are Not-self and Suffering those things determined by the
_saṅkhāra_ are also Not-self and Suffering.

The Buddha shows the _puthujjana_ that whatever thing (__dhamma__) he
identities as ‘self’ is something that is dependent upon other things.
In other words, he shows the _puthujjana_ that the latter’s ‘self’ is a
determined thing dependent upon Determinations, upon __saṅkhāra__. He
further shows that these _saṅkhāra_ which form the necessary conditions
for that thing identified as ‘self’ are impermanent. “All _sañkhāra_ are
impermanent (__sabbe saṅkhāra aniccā__)”. (https://suttacentral.net/mn35[MN 35])

Now, when he sees that the _saṅkhāra_ upon which his ‘self’ depends are
impermanent, then he sees that this his ‘self’ must also be necessarily
impermanent, and hence not worth holding to. That means he is now left
with a ‘self’ that is impermanent and not worth holding to. (He finds
that he has no real mastery in the face of this impermanence.) And if it
is impermanent and not worth holding to, then it contradicts the very
concept of ‘self’. This means that what he had identified as ‘self’ is
now no longer self. The thing (__dhamma__) which he had regarded as
‘self’, he now finds is Not-self (__anattā__). Thus: “All things are
Not-Self” (__sabbe dhammā anattā__).

Therefore, when “All _saṅkhāra_ are impermanent” is seen “All things are
Not-self” and “All _saṅkhāra_ are Suffering”footnote:[See Chapter 11 on
Suffering. TODO: link to chapter] are also seen. These three stand
together, and fall together. When there is perception of Impermanence
there is simultaneously perception of Not-self and perception of
Suffering. When perception of Impermanence is not there, there is also
no perception of Not-self and no perception of Suffering.
