[[ch-05-kamma]]
= 5. Kamma

It is useful to discuss briefly the subject of intentional action once
again.

[quote, role=quote]
____
Intention, monks, I declare is __kamma__. Having intended, one does
_kamma_ through body, speech, and mind.

-- https://suttacentral.net/an6.63/en/thanissaro[AN 6.63], A Penetrative Discourse
____

This statement of the Buddha is not quite as simple as it is usually
reckoned to be. Firstly, from the Sutta itself, it is
clear that this statement was made in relation to the *non*-Arahat.
The literal meaning of _kamma_ is 'action'. With the _puthujjana_ it
therefore refers to '*my* action' or '*I* act'. The word _kamma_ is
used in this sense. Further expanded, _kamma_ means '*my* intentional
action' or 'the action *I* intentionally take'. And *all* action that is
consciously done is intentional. This intentional action can be by means
of body, speech, or mind.

Intentional action *unaccompanied* by thoughts of 'I' or 'mine' is *not
kamma*. The Arahat has no thoughts of 'I' and 'mine'. Therefore the
Arahat's intentional action is not __kamma__. The Arahat has intentional
action, but no __kamma__. *Kamma is the non-Arahat's intentional
action.* Of the Arahat the Buddha says: 'He does not commit new
__kamma__.'footnote:[Of all the many things about _kamma_ the Buddha has
taught, such as the various types of _kamma_ and their various fruits
(__vipāka__), this is the most important. It is also the most
fundamental thing about it.]

Ethics is concerned with the question of 'what should *I* do'. Whether
that 'what should be done by *me*' is good or bad, moral or immoral,
etc., it is necessarily something which *I* should do.

Ethics accepts that 'I' and 'mine' must exist. It builds itself on the
basis that 'I' is a necessity. Ethics may or may not be conscious of its
own position here. Nevertheless that remains its basic position.
Actually, ethics is a searching after the most comfortable or the best
way in which 'I' can exist. But, as we shall see later on, 'I' exists
only in so far as Ignorance of the Four Noble Truths exists. Ethics does
not know this fact. Thus, in the final analysis, ethics is a searching
after the most comfortable and best way in which Ignorance can exist. It
is therefore no wonder that no two schools of ethics are in agreement.
Wherever there is Ignorance, there is conflict.

Where 'I' and 'mine' are wholly and entirely extinct, there the question
of what should *I* do does not arise. Arahatship is *the extinction of
ethics* also. Whilst all religions, in the end, teach an ethics of some
kind or other. Buddha teaches the extinction of *all* ethics also.

The Buddha teaches the arising and ceasing of _kamma_ thus:

[quote, role=quote]
____
Monks, were there _kamma_ performed in lust, born of lust, conditioned
by lust, arising from lust -- that _kamma_ is unskilful (__akusala__),
that _kamma_ is blameworthy, that _kamma_ has pain as fruit, that
_kamma_ leads to the arising of (further) __kamma__. That _kamma_ does
not lead to the cessation of __kamma__. Monks, were there _kamma_
performed in hatred … performed in delusion … that _kamma_ is unskilful,
that _kamma_ is blameworthy, that _kamma_ has pain as fruit, that
_kamma_ leads to the arising of __kamma__. That _kamma_ does not lead to
the ceasing of __kamma__. These, monks, are the three conditions for the
arising of __kamma__.

Monks, were there _kamma_ performed with non-lust, conditioned by
non-lust, arising from non-lust -- that _kamma_ is skilful (__kusala__),
that _kamma_ is praiseworthy, that _kamma_ has happiness as fruit, that
_kamma_ leads to the ceasing of __kamma__. That _kamma_ does not lead to
the arising of __kamma__. Monks, were there _kamma_ performed with
non-hatred … performed with non-delusion … that _kamma_ is skilful, that
_kamma_ is praiseworthy, that _kamma_ has happiness as fruit, that
_kamma_ leads to the ceasing of __kamma__. That _kamma_ does not lead to
the arising of __kamma__. These, monks, are the three conditions for the
ceasing of __kamma__.

-- https://suttacentral.net/an3.111/en/sujato[AN 3.111], Sources (1st)
____

Summarized, the above means: unskilful _kamma_ leads to the arising of
__kamma__, and skilful _kamma_ leads to the cessation of __kamma__. Or,
unskilful intentional action accompanied by thoughts of 'I' and 'mine'
leads to further intentional action accompanied by thoughts of 'I' and
'mine', and skilful intentional action accompanied by thoughts of 'I'
and 'mine' leads to the cessation of intentional action accompanied by
thoughts of 'I' and 'mine'. The Arahat not having any thoughts of 'I'
and 'mine' whatsoever does *not* perform *either* skilful *or* unskilful
__kamma__.

The Buddha further teaches how _kamma_ rooted in lust, hatred and
delusion leads to further _kamma_ whilst _kamma_ rooted in non-lust,
non-hatred and non-delusion leads to the cessation of __kamma__, thus:

____
Monks, there are these three conditions for the arising of __kamma__.
What three? Monks, for things which in the past were based on desire and
attachment … in the future will be based on desire and attachment … in
the present are based on desire and attachment, desire is born.

How, monks, is desire born for things which in the past were based on
desire and attachment … in the future will be based on desire and
attachment … in the present are based on desire and attachment? Monks,
things which in the past … in the future … in the present are based on
desire and attachment, one turns over in his mind. Thus turning over in
his mind things which in the present are based on desire, desire is
born. Desire being born, he is fettered by those things. I call it a
fetter, monks -- that mind full of attachment. Thus, monks, is desire
born for things which in the present are based on desire and attachment.
These are the three conditions, monks, for the arising of __kamma__.
____

On the other hand:

[quote, role=quote]
____
How, monks, is desire not born for things which in
the past were based on desire and attachment … in the future will be
based on desire and attachment … in the present are based on desire and
attachment? Monks, one understands the future result of things which in
the present are based on desire. Seeing this result one turns away from
them. Turning away from them, the mind getting detached from them, one
penetrates them with wisdom and sees them plain. Thus, monks, is desire
not born for those things which in the present are based on
desire.

-- https://suttacentral.net/an3.112/en/sujato[AN 3.112], Sources (2nd)
____
