[[holding-to-belief-in-self-and-person-view]]
= Holding to Belief in Self- and Person-view

With this we come to the problem of ‘self’. It is in fact the basic
problem. It is also more difficult a problem than it is generally
supposed to be. And if one is speaking of the Buddha’s Teaching then
fundamentally one is speaking of _attavādupādāna_ (holding to belief in
‘self’) and _asmimāna_ (the conceit ‘I am’). For, a Teaching that is
meant to lead on to a cutting off at the root that which is called
_upādāna_ must necessarily have a great deal to do with the most
fundamental of __upādāna__, viz., __attavādupādāna__. The Buddha’s
Teaching sets out to destroy Suffering, and this, as we shall see later
on, is to destroy and uproot beliefs in ‘self’ and thoughts of ‘I’ and
‘mine’, which again is to uproot __upādāna__. “Uproot false view of
seIf.”^Snp{nbsp}1119^ With the uprooting and destruction of these false views other
things follow.

The notion of ‘self-hood’ is fundamentally a notion of
**mastery**footnote:[The Pali word is __vasa__. See https://suttacentral.net/mn35[Majjhima Nikāya 35].]
over things, a notion of being able to wield power over things, which in
the final analysis is a notion of mastery over Form, Feeling,
Perception, Determinations and Consciousness. ‘I am master over this
body, it is mine.’ Or else, ‘I am master over my intentions, they are
mine.’ To own or appropriate a thing means to become master over it, to
wield power over it. Moreover, I think that ‘I am’ is something pleasant
and pleasurable only when I feel or think I am permanently *master* over
my Form, Feeling, Perception, Determinations and Consciousness, and I
have *power* over them so as to make them become just what I want them to
be. This feeling is the feeling of ‘self-hood’, and with it I lull
myself into a false sense of security.

Though in times of right mindfulness the _puthujjana_ may tend towards
seeing impermanence, the __puthujjana__’s reaction towards things is as
if they were permanent. His actions are based upon such wrong view.
Basing himself on this wrong view he intends and acts. Whatever mastery
he possesses is very *temporary* and very *partial*. Impermanence
undermines the mastery. And a mastery that is undermined by impermanence
is certainly no mastery. In short, the assumed ‘self-hood’ is no ‘self-
hood’ at all. ‘Self-hood’ is therefore a *deception*.

I really do not wield power or possess mastery over the Five Grasping
Groups which I regard as *my own*. I cannot say to my Consciousness:
“Let my Consciousness be thus, let my Consciousness be not thus.” I
cannot say to my body which is suffering from an ulcer, “Let my body be
relieved of the ulcer” and so have my body relieved of the ulcer. I
certainly wish that from this body which I regard as my own the ulcer
would vanish. In fact I think that it should never have come at all. But
however much I wish the ulcer to vanish it does not. Nor can I wield any
such power over the other Groups which I regard as ‘mine’. I cannot say
to the feelings which I regard as ‘mine’, “Let my feelings be thus, let
my feelings be not thus”, and so have my feelings as I want them to be.
Thus this ‘self-hood’ which is adhered to is a deception, ever and again
leading to betrayal, to disappointment. Betrayal and disappointment are
the inevitable outcome of adhering to a deception.

Now, the _puthujjana_ has __attavādupādāna__. That is to say, the
_puthujjana_ holds (__upādāna__) to belief (__vāda__) in ‘self’
(__attā__).footnote:[“Holding to belief in ‘self’” essentially means
holding to belief in a master.] Because he holds to this belief in
‘self’ he keeps looking for something which he can *identify* as this
his ‘self’.footnote:[To “identify something as his ‘self’” essentially
means to identify something as that thing over which he is master.] If
he is to keep believing there is a ‘self’ then he *must* at the same
time regard something or other as this ‘self’. And if there is anything
that he is led to identify as this his ‘self’ it must pertain to the
Five Grasping Groups. It must be one or more of these Groups. It is
impossible for him to identify it with anything else. He therefore views
one or more of the Groups as ‘self’.footnote:[To view the Groups as
‘self’ essentially means to regard that ‘I am master over the Groups’.
‘The Groups are my self’ means ‘I am master over my Groups’.] This means
he has gone to wrong view. He has gone to the wrong view that one or
more of his Groups is ‘self’. Having thus gone to a wrong view he
elaborates on the view and formulates a distinction between himself and
the rest thus: ‘The self, the world’ (__attā ca loko ca__). And he
further keeps deliberating about himself (that is about the Five
Grasping Groups regarded as ‘self’) thus:

[quote, role=quote]
____
* ‘Was I in the past’,
* ‘was I not in the past’,
* ‘who was I in the past’,
* ‘how was I in the past’,
* ‘having been who in the past who have I come to be now’,
* ‘will I be in the future’,
* ‘will I not be in the future’,
* ‘who will I be in the future’,
* ‘how will I be in the future’,
* ‘being who in the future whom will I be again in the future’.

About his present existence too he begins to doubt:

* ‘Am I’,
* ‘am I not’,
* ‘who am I’,
* ‘how am I’,
* ‘from where has this being come’,
* ‘where is he going’.

Further, one or other of the following views arises in him as though it
were real and true:

* ‘There is self for me’,
* ‘there is not self for me’,
* ‘by self I recognize self’,
* ‘by self I recognize not-self’,
* ‘by not-self I recognize self’,
* or ‘this my self which feels pleasant and unpleasant feelings, reaps the
fruit of good and bad action, is permanent, steadfast, eternal, not
transitory, stands unchanging as an etemal thing’.

-- https://suttacentral.net/mn2[MN 2], All the Defilements
____

Thus he is gone to (wrong) view, or he is of (wrong) view (__diṭṭhigata__).

All this deliberating about ‘self’ is because he is attached to a belief
in ‘self’, because he has desire and passion towards ‘self’. If he does
not hold to a belief in ‘self’, these deliberations do not arise.

This regarding or viewing the Grasping Groups as ‘self’ in some way or
other is called the ‘person’-view (__sakkāyadiṭṭhi__).

[quote, role=quote]
____
“But how, noble lady, is there the ‘person’-view?”

“Here, friend Visakha, the uninstructed _puthujjana_ not discerning the
Noble Ones, not skilled in the Noble Doctrine, untrained in the Noble
Doctrine, not discerning the Worthy Ones, not skilled in the Doctrine of
the Worthy Ones, untrained in the Doctrine of the Worthy Ones, regards

* Form … Feeling … Perception … Determinations … Consciousness as ‘self’,
* or regards ‘self’ as having Consciousness,
* or regards Consciousness as being in ‘self’,
* or regards ‘self’ as being in Consciousness.

Thus, friend Visakha, it is said there is the ‘person’-view.”

-- https://suttacentral.net/mn44[MN 44], The Shorter Classification
____

But why say ‘*person*’-view (__sakkāyadiṭṭhi__)?

_Sakkāya_ means ‘person’, ‘somebody’, a ‘self-existing
being’.footnote:[It does not matter very much what word we use as the
English equivalent of the Pali word __sakkāya__. The fact is that
whatever word we use to denote _sakkāya_ will equally baffle the
individual who does not understand its meaning. What is needed is not so
much a precise English equivalent for the word _sakkāya_ as much as
understanding what it refers to.] To the _puthujjana_ he is himself a
__sakkāya__, i.e., a ‘person’, a ‘somebody’, a collection of Five
Grasping Groups which regards itself as master over itself. To be
precise the Five Grasping Groups takes itself to be a __sakkāya__.

Another word is __satta__. The _puthujjana_ takes himself to be a
__satta__. _Satta_ or _sakkāya_ refers to the sentient being regarded in
some way or other as ‘self’. That is, it refers to the Five Grasping
Groups taken to be ‘self’. It is the __puthujjana__’s concept of the
sentient being. It is his concept of himself. That is why the Five
Grasping Groups are called __sakkāya__.footnote:[“What, monks, is the
__sakkāya__? The Five Grasping Groups are to be so called.” (https://suttacentral.net/sn22.105[SN 22.105])]
To have this concept means to be gone to ‘person’-view.

Again, the Five Grasping Groups looks upon itself as ‘self’ so long as
it contains __attavādupādāna__, i.e., so long as it holds to belief in
‘self’. _Sakkāya_ incorporates __sakkāya-diṭṭhi__; that is to say,
‘person’ contains ‘person’-view.footnote:[This statement is not fully
applicable to the __sotāpanna__, and higher __sekhas__. To the extent
that thoughts of ‘I’ and ‘mine’ and the deception ‘self’ arise in them,
they are still __sakkāya__. But they know that regarding anything as ‘I
am’ or as ‘mine’ or as ‘self’ is wrong. Therefore they do not hold to
any belief in ‘self’. Thus they have no __attavādupādāna__, and to that
extent have no _sakkāyadiṭṭhi_ also. See footnote on page 135. FIXME:
add link] It should be noted that _sakkāyadiṭṭhi_ is not a question of
just passively viewing oneself as a _sakkāya_ in a rather detached
manner. It is much more dynamic and intense a matter, deeply rooted.
Hence the difficulty in getting rid of it.

_Sakkāyadiṭṭhi_ should not be identified purely and simply with “the
view that *in* the Five Grasping Groups there is a self” or with “the
belief in a self or soul”. Regarding one or more of the Five Grasping
Groups as ‘self’ in some way or other is different to purely and simply
regarding the Five Grasping Groups as having a ‘self’ *in* them somewhere
or other. The person who mistakes _sakkāyadiṭṭhi_ to mean purely and
simply “the view that in the Five Grasping Groups there is a self” can
very effectively impede his own progress and even think he is an _ariya_
(Noble One) whilst he is not.

After a masterly analysis of the Five
Grasping Groups, perhaps with the assistance of modern science, he finds
no self-existing thing in it. Thus quite honestly he comes to the
conclusion that there is no self in the Five Grasping Groups, and so he
thinks he has no __sakkāyadiṭṭhi__, which means he now thinks he is a
__sotāpanna__,footnote:[See Chapter XV for definition of the
__sotāpanna__. At this stage it would be sufficient to know that the
_sotāpanna_ is not a _puthujjana_ and that he is therefore an __ariya__,
i.e. he is a Noble.] whilst in truth he really is not.

The Five Grasping Groups constantly recognizes itself as ‘self’. It is
its very nature. And the apparent ‘self’, or that which appears as
‘self’ is taken as it appears and is identified as ‘self’.

_Sakkāyadiṭṭhi_ is a determined thing (__saṅkhata dhamma__), because it
has come about with _attavādupādāna_ as necessary condition. Here,
_attavādupādana_ is a __saṅkhāra__. As a _saṅkhāra_ it is the necessary
condition for __sakkāyadiṭṭhi__. Without _attavādupādāna_ there can be
no __sakkāyadiṭṭhi__. Because the _puthujjana_ holds to belief in ‘self’
he views the Five Grasping Groups (or one or more of them) as this
‘self’ which he believes in.

On the other hand, if there is no holding to belief in ‘self’, then
there can be no __sakkāyadiṭṭhi__, because then no identification or
regarding of anything as ‘self’ will arise. The _puthujjana_ does not
see this. He does not see that his _sakkāyadiṭṭhi_ is dependent on a
_saṅkhāra_ and that all _saṅkhāras_ are *impermanent*. But if he sees
that the _saṅkhāra_ called holding to belief in ‘self’
(__attavādupādāna__) is impermanent then the _saṅkhāra_ will cease, and
he will no longer be deceived into believing in any ‘self’. When
_attavādupādāna_ ceases his identification of the sentient being as self
ceases, which means _sakkāyadiṭṭhi_ ceases and he ceases to be a
__puthujjana__. He has then crossed from the plane of the _puthujjana_
(__puthujjana bhūmi__) to the plane of the Noble (__ariya bhūmi__).

Of the three notions ‘This is mine, this am I, this is my self’, the
most fundamental one is ‘*this is mine*’. In the Discourse on __The
Fundamentals of All Things__ (Majjhima Nikāya 1) the Buddha
narrates at length the many things that the _puthujjana_ takes to be
‘mine’. He does *not* include the other two notions of ‘I’ and ‘self’ at
all in this Discourse.

Further, in the __Ananda Sutta__ we have the following:

[quote, role=quote]
____
“By grasping Form is there ‘I am’, not by not-grasping (__rūpam upādāya
asmīti hoti no anupādāya__). By grasping Feeling … Perception …
Determinations … Consciousness is there ‘I am’, not by not-grasping.”

-- https://suttacentral.net/sn22.83[SN 22.83], With Ānanda
____

This too indicates that ‘mine’ (which is essentially the same as what
has been referred to in the Sutta as grasping) is more fundamental
than ‘I’, and that for ‘I’ to be present ‘mine’ must be present.

It is of great *practical* importance to see that ‘mine’ is the most
fundamental of these three notions ‘mine’, ‘I’ and ‘self’. The
__puthujjana__’s constant thinking is a thinking that something is
*his*. In fact there is nothing more fundamental than this about his
experience. And he must seek to understand this state of affairs in his
own experience itself. The notions ‘I’ and ‘self’ do not take the same
stature as the notion ‘mine’. When he, the __puthujjana__, is conscious
of a feeling, he is always conscious of it as *my* feeling. It is this
consideration ‘mine’ that leads the _puthujjana_ on.

The __puthujjana__, however, works with the assumption that the
fundamental is ‘I’ and not ‘mine’. Since *he* exists, he thinks things
are *his*. “*Since ‘I’* exist, things are *mine*.” But the
fundamental condition, the Buddha points out, is ‘mine’. The
_puthujjana_ having Grasping Consciousness, things *present* themselves
to him as *‘mine’*. And this state of affairs further *points* to a
subject to *whom* they are present. That is, they point to an ‘I’. The
correct position is therefore: *Since things are ‘mine’, ‘I’ exist.*

The _puthujjana_ then begins to wonder what precisely this ‘I’ is. He
begins to reflect upon the ‘I’. And when he so reflects he sees a
‘self’; that is to say, he sees a mastery over things. A ‘self’ appears
before him as he reflects, just as ‘water’ appears to the deer when it
gazes upon the sun shining on the sand. ‘Mine’ being present all the
time, this ‘self’ also appears as ‘*my* self’.

Finally, the _puthujjana_ -- holding to belief in ‘self’ all the time --
tries to identify this ‘self’. But he can identify it with nothing else
other than one or more of the Five Grasping Groups. He therefore
proceeds to regard or view one or more of the Groups as ‘self’ -- more
precisely, as ‘my self’. He thinks ‘The Groups are myself’, meaning
fundamentally, ‘I am master over my Groups’. Thus he has
__sakkāyadiṭṭhi__.

The notion of ‘self’ is secondary to ‘mine’ and ‘I’. It is like a coarse
layer that lies over the conceit ‘I am’. Before getting rid of the
conceit ‘I am’ (__asmimāna__), holding to belief in ‘self’ is got rid
of. The Ariyan disciple (who is a __sotāpanna__), seeing fully well how
_sakkāyadiṭṭhi_ arises, has got rid of it. That is to say, he no longer
regards anything as ‘self’. But until he becomes Arahat the subtle
conceit ‘I’ still remains in him. It is only the Arahat who is utterly
freed of ‘I’ and ‘mine’ too.
