[[impermanence]]
= Impermanence

Invariably, one imagines all too soon that one understands and perceives
the Buddha's doctrine of Impermanence (__aniccatā__). But the
impermanence that the Buddha teaches is not the impermanence that one
sees around oneself. It is something far more subtle than that.

The meaning of the word _anicca_ (__a-nicca__) is not-permanent. It says
nothing more.

In reflection, the thinker is not averse to accepting that things are
not-permanent or not-eternal or not-everlasting. He sees most things
passing away, at least after some time. And if he thinks he will not
live long enough to see a particular thing pass away he contents himself
by inferring that it will pass away some time in the future, somehow.
Thus to a large extent he avoids falling into the one extreme of
*eternal* existence. And if at all there be anything that shall remain
permanent it may be his own ‘self’!

But herein lies the difficulty. For, as he moves himself away from the
extreme of eternal-existence he falls into the other extreme of
*no*-existence without realising that he is actually falling there. He
falls from the extreme of *eternal* duration to the extreme of *no*
duration. The usual way in which this happens is by assuming that things
are *becoming from moment to moment*. If he is questioned as to what a
moment is, he will reply that it is the shortest possible time.

But the shortest possible time is *no* time. Thus, his thinking that a
thing exists for only a moment when critically analysed means that the
thing exists for *no* time, which only means that the thing *does not
exist at all*.

But if his definition of moment means *some* duration of time however
small it be, then what he really means is that the thing exists or
persists *without change for some time or other*. That means there is
a *temporary persistence*.

Temporary persistence is not rejected by not-permanent. A thing can be
not-permanent but yet *exist without change for some time*. It lasts
*for some time* though *not for ever*. Therefore, *“nothing endures
absolutely for ever, and nothing is absolutely without duration.”* In
other words, it means that “between its appearance and disappearance a
thing endures.”

Actually changes go on at various levels of generality. A table, for
instance, remains a table even though its components are changing.
Though a little part of it may have changed and even disappeared, yet
the table remains a table. And it will remain a table until changes have
developed to the point at which the table is no more. “A thing
*remains the same* means it has become the *invariant of a
transformation*.”

@@

Now, the Buddha teaches: "Monks, there are these three
__Determined__-characteristics of the _Determined_ (__saṅkhata__). What
three? Arising is to be discerned, passing away is to be discerned,
otherwise-ness in persistence is to be discerned. These are the three
Determined-characteristics of the __Determined__."footnote:[Anguttara
Nikāya I, Tika Nipāta, Cūla Vagga, Sutta No. 7.]

And: "Monks, there are these three Not-__Determined__- characteristics
of the Not-__determined__ (__asaṅkhata__). What three? Arising is not to
be discerned, passing away is not to be discerned, otherwise-ness in
persistence is not to be discerned. These are the three
Not-__Determined__-characteristics of the
Not-__Determined__."footnote:[Anguttara Nikāya I , Tikaa Nipāta, Cūla
Vagga. Sutta No. 8.]

In understanding the above we must remember what the Buddha refers to as
the _Determined_ (__saṅkhata__) and the Not-__Determined__
(__asaṅkhata__). It is very easy for us to assume that what the Buddha
taught can be applied in full to each and every thing that lies outside
the domain of his Teaching. But it is very dangerous. We must know
always precisely what he is referring to, and avoid stretching the
limits in our own imagination. He specifically said that he teaches only
one thing always, i.e. Suffering and the cessation of Suffering.
"Formerly, and now also, Anuradha, it is just Suffering and the
cessation of Suffering that I proclaim."footnote:[Saṃyutta Nikāya IV,
Avyākata Saṃyutta, Sutta No. 2.] He also said that his Teaching has the
taste of Deliverance right through. "Just as the great ocean, Paharada,
has but one taste, the taste of salt, even so, Paharada, this Dhamma and
Discipline has but one taste, the taste of
Deliverance."footnote:[Anguttara Nikāya IV, Aṭṭhaka Nipāta, Maha Vagga,
Sutta No. 9.] The words _Determined_ and Not-__Determined__ are also
used by him in relation to that one thing he teaches -- Suffering and
the cessation of Suffering.

What now is the __Determined__?

As the _Khajjaniya Sutta_ tells us, it is the Five Grasping Groups. This
means that it refers to the 'person', or to 'self', or to the subject
'I'. These are all detemined things. Hence they are called the
_Determined_ (__saṅkhata__). Of all the things that have been determined
the most important thing is 'my self', and it is precisely in _this_
that the problem of Suffering lies. The Buddha is not teaching anything
other than about this problem either.

Let us now see how the three characteristics of the _Determined_ as
taught by the Buddha apply to the __Determined__, particularly the
characteristic which he refers to as "otherwise-ness in persistence"
(__ṭhitassa aññathattaṃ__).

_Ṭhitassa aññathattaṃ_ means otherwise-ness (__aññathattaṃ__) in
persistence (__ṭhitassa__). It is commonly thought that this refers to
decay (__jarā__). But it does not refer to decay. It refers to something
much more fundamental than decay. Appearance (__uppāda__), disappearance
(__vayo__), and otherwise-ness in persistence (__ṭhitassa aññathattaṃ__)
are three characteristics that are fundamental to all Grasping Groups at
_all_ times and not merely at time of decay. The essential idea in the
word 'persistence' is really permanence or unchange. A thing persists
for some time means it exists without change for some time.

Firstly, what is it that is seen to persist?

It is 'self'. It is 'I'. An apparent 'self' is seen to persist. There is
a persistence of this apparent 'self'.

'I' am thinking, or 'I' am eating, or 'I' am writing. Or, 'my self' is
thinking, or 'my self' is eating, or 'my self' is writing. Now, whether
'my self' is writing or doing something else, the 'my self' is seen to
persist. Though the actions of the 'I' and the appropriations of the
'mine' are varying and changing, the 'self'-ness and the 'I'-ness is
seen to persist. In other words, the subjectivity is seen to persist.
Now, this 'self' is always identified as something. There is something
that is always taken to be this 'self'. And that is one or more of the
Five Grasping Groups. But whilst this 'self' is persisting, that which
is taken as this 'self' is becoming otherwise, is under-going
transformation or change all the time.

The persisting 'self' is equated to the Grasping Groups which are
becoming otherwise. Thus we get an "otherwise-ness in persistence", a
characteristic which is discernible from the time of appearance up to
the time of disappearance. And for the Five Grasping Groups appearance
is synonymous with birth whilst disappearance is synonymous with death.
This is somewhat similar to the principle called 'Invariance under
Transformation' which occurs in Quantum Mechanics and Relativity Theory.
The invariant with regard to the Five Grasping Groups is 'self'.

In this persistence of an apparent 'self' lies the reason for Religion
to assume the actual existence of an immortal self called a 'soul'. This
is the connection between 'self' and 'soul' that is of any worthwhile
interest. Religion makes this assumption because though it sees a
persistence in 'self' it does not see the conditions that keep this
'self' persisting and therewith also does not see its destruction.

What now is the Not-__Determined__?

The Not-__Determined__ is defined as follows:

"The destruction of lust, the destruction of hatred, the destruction of
delusion -- this, monks, is called the
Not-__Determined__"footnote:[Saṃyutta Nikāya IV, Asaṅkhata Saṃyutta,
Sutta No. 12.] (__asaṅkhata__). The Path leading to the
Not-__Determined__ is further defined as the Noble Eightfold Path.

Then we have Arahatship also defmed as the destruction of lust and of
hatred and of delusion: "The destruction of lust, the destruction of
hatred, the destruction of delusion -- this, friend, is called
Axahatship."footnote:[. Saṃyutta Nikāya IV. Jambukhādaka Saṃyutta, Sutta
No. 2.]

Thus, the Not-__Determined__ is synonymous with Arahatship. The
Not-__Determined__ therefore is the __living experience of the Arahat__.
He has trod the Path leading to the Not-__Determined__, has arrived at
the Not-__Determined__, and is now living experiencing the
Not-__Determined__.

Now, actually and in truth, there is no 'Arahat' to be found. "Anuradha,
the __Tathāgata__,footnote:[Tathāgata refers to the Buddha.] actually
and in truth, is here not to be found" (__Anurādha, diṭṭheva dhamme
saccato thetato Tathāgate anupalabbhyamāne__)".footnote:[Saṃyutta Nikāya
IV, Avyākata Saṃyutta, Sutta No. 2.] The reason for this is that there
is no 'self' or 'I' and 'mine' existing with the Buddha. As with the
Buddha, so with the Arahats. Though we use the word 'Arahat' for
purposes of conversation there is no 'person' called an Arahat. No
'person' who says 'I am Arahat' or 'this Arahatness is mine.' We can
distinguish an Arahat from another Arahat as two different individuals.
But with regard to the Arahat there is no 'person' or 'somebody' or
'self' who says 'I' and 'mine'. "The Arahat intentionally acts, but the
acting is quite unaccompanied by any thought of a subject who is acting.
For all non-Arahats such thoughts (in varying degrees, of course) do
arise. The Arahat remains an individual (i.e., distinct from other
individuals), but is no longer a _person_ (i.e. a somebody, a 'self', a
subject). This is not, as one might perhaps be tempted to think, a
distinction without a difference. It is a genuine distinction, a very
difficult distinction, but a distinction that _must_ be
made."footnote:[Ñānavīra Thera, in a letter to the author.] It is _the_
distinction that has to be seen.footnote:[The ordinary man cannot
distinguish between individuality and 'pers0n'-ality. T0 hiIn, there is
alwlays only a 'pers0n'-ality, and individuality is identical with it.
The Arahat is an individual (puggala) in that there is distinct set of
Five Groups as separate from another set, but there being no Grasping,
he is not a 'person' (Sakkāya).]

The difference between life-action and the action of inanimate things is
the presence of intentionality in life-action. Intention is present only
in life, and it is present in _all_ life whether Arahat or non-Arahat.
The Buddha teaches that all life, save that of the Arahat, has Grasping
also. Thus for the non-Arahat there is both intention and Grasping,
whilst for the Arahat there is intention but _no_ Grasping. Gtasping, as
mentioned earlier, is essentially subjectivity ('self', 'I' and 'mine').
The subjectivity, to some degree or other, is present in all life except
that of the Arahat. Thus again, all non-Arahats have both intention and
subjectivity, whilst the Arahat has intention but no subjectivity. All
life before the advent of the Buddha (i.e., before the ascetic Gotama
became Arahat) was a case of intention together with subjectivity. The
Buddha, in his own being, discovered that there could be intention but
no subjectivity -- a difficult thing indeed to see. It is also so
difficult a thing to achieve that nothing short of the Noble Eightfold
Path can take one there.

If the ordinary man is told there can be intentionality without
subjectivity, i.e., that there can be intentional action completely
unaccompanied by any thoughts of 'I', he will invariably say that this
is impossible. But it is precisely this 'impossibility' that the Buddha
discovered and made a possibility. It is essentially in this that he
stands unique.

There is an Arahat-ness that is being experienced which we refer to as
the 'Arahat's life' or the 'living experience of the Arahat'. That is
all. But no 'person' or 'self' with regard to the Arahat is to be found.
And that means no 'person' or 'self' is determined. That is why
Arahat-ness is referred to as the Not-__Determined__, i.e. as
__asaṅkhata__. Being Not-__Determined__, there can be no appearance, no
disappearance, and no otherwise-ness in persistence.

In teaching Suffering and the cessation of Suffering, the Buddha teaches
the _saṅkhata_ and the __asaṅkhata__. _Saṅkhata_ refers to the 'person'
(__sakkāya__) which is a Suffering, and _asaṅkhata_ refers to the
Arahat, which is the cessation of the 'person' (__sakkāyanirodha__) or
the cessation of Suffering.

'''''

Be it again noted that the problem of 'self' (__attā__) is of
considerably greater difficulty than it is generally supposed to be. So
are the problems of Impermanence (__anicca__) and Suffering
(__dukkha__).

'Self' is not an indefiniteness. It is a __deception__, and a deception
(a mirage, for example) can be as definite as one pleases. The only
thing is, that it is _not_ what one takes it for. When the sun shines on
the sand there is the _appearance_ of water. I am thus _deceived_ to
take the phenomenon as water. The _deception_ of water _is_ there all
right though the phenomenon is __not__-water. I am only _deceived_ in
thinking that it is water. To understand the phenomenon of the sun
shining on the sand I must realize that it is not-water. So is it with
'self'. The deception of 'self' is there. I must understand that the
phenomenon I take to be 'self' is Not-self (__anattā__). The Five
Grasping Groups are taken to be 'self' though in truth they are not. I
must therefore see that the Five Grasping Groups are Not-self.

To make an assertion, positive or negative, about 'water' with regard to
the sun shining on the sand is to work accepting falsity at face value.
To say 'the water exists' or 'the water does not exist' is to base one's
statement on the wrong permise 'water'. Likewise to make an assertion,
positive or negative, about 'self' is to work accepting falsity at face
value. For this reason the Buddha refrains _both_ from asserting _and_
from denying the existence of 'self' when Vacchagotta questioned him as
to whether 'self' exists or does not exist.

To have answered Vacchagotta categorically that 'self' does exist or
that 'self' does not exist would have been unwise. For the fact is that
whilst no actual self is to be found there yet _is_ a deception of a
'self' to be found. What a person who asks such direct questions about a
deception should be given are not direct answers of 'yes' or 'no', but
__proper instruction__.

'Self' is always something very ambiguous to the __puthujjana__. He
always feels there is a self, but whenever he tries to get hold of it or
spot it he fails. The deer thinks there is water when the sun shines on
the sand and produces the _mirage_ of water. But when the deer runs
after the 'water' the water eludes him. If the deer is told, "There is
water", it will reply, "But I cannot find water however much I run after
it." If on the other hand the deer is told. "There is no water", it will
reply, "But I see water however much you say no." The _puthujjana_ is in
the same dilemma with regard to his 'self'. If he is told, "There is no
self for you", he will say, "But I see a self". On the other hand if he
is told, "There is a self for you", he will say, "But I cannot find
precisely where or what it is". And that would have been just the
position Vacchagotta would have fallen into had the Buddha given him
direct answers to his questions either in the affirmative or in the
negative. To the _puthujjana_ a 'self' always __appears__, but never
does he find it when he tries to.

What the Buddha said was: "All things are Not-self" (__sabbe dhammā
anattā__).footnote:[Majjhima Nikāya 35.] It simply means that no thing
is self, or that if you look for a self you will not find one. 'Self' is
a deception, like a mirage. It does not mean that the mirage, as such,
does not exist. The mirage _does_ exist. And it keeps persisting. It
keeps persisting as '__my__ self' which is distinct from all other
things. In its persistence there is a distinctiveness to be seen, a
being different to all other things -- 'the self, the world' (__attā ca
loko ca__).

Impermanence (__aniccatā__) is seen in its essential and effective
meaning, and is seen __for certain__, only when Not-Self-ness
(__anattatā__) is also seen and recognized, simply because one thinks
that whatever else in the world is impermanent one's 'self' is
permanent. Everything to the seer is impermanent except the seer
himself! What after all is the significance of Impermanence if it does
not apply to the _one_ thing that matters to me -- my 'self'?

It is only when a person sees that this last bastion of permanency,
viz., his 'self', is nothing but a deception or mirage which will pass
away when the conditions that keep it going are removed, that he really
and truly gets the impact of Impermanence. It is _only then_ that he
sees that _all_ (which, for him, is nothing more than his Five Grasping
Groups) is impermanent. Then only does he have perception of
Impermanence.
