[[ch-01-grasping]]
= 1. Grasping

[quote, role=quote]
____
"'Person! Person!' (__sakkāya__), Venerable One, it is said. But what is
it that the Exalted One has called the 'person'?"

"These Five Grasping Groups (__upādāna-kkhandhā__), friend Visākha, has
the Exalted One called the 'person', namely: the Grasping Group of Form,
the Grasping Group of Feeling, the Grasping Group of Perception, the
Grasping Group of Determinations, the Grasping Group of Consciousness.
These Five Grasping Groups, friend Visākha, has the Exalted One called
the 'person'."

-- https://suttacentral.net/mn44/en/sujato[MN 44], The Shorter Classification
____

Thus the Buddha teaches me that I comprise five groups or aggregates of
Grasping. The Pali word _upādāna_ has been translated here as
_Grasping_. It may also be translated as _Holding_.

[quote, role=quote]
____
And what, monks, is Form (_rūpa_)? The Four Primary Modes
(_dhātu_), and the Form that is present by grasping (_upādāya_) the
Four Primary Modes -- this, monks, is called Form.

-- https://suttacentral.net/sn22.56/en/bodhi[SN 22.56], Perspectives
____

The Four Primary Modes mentioned here are the Earth-Mode, Water-Mode,
Fire-Mode and Air-Mode. They are often referred to as 'elements'. But in
relation to 'matter', which is what Form refers to 'elements' gives the
idea of indivisible fundamental ingredients, and a wrong impression can
be created that Buddhism splits the world-mass into four distinct
fundamental ingredients. Form refers to what we call 'matter'. But the
Four Primary Modes do not refer to four elements or ingredients which
constitute this 'matter'. They refer to four distinguishable general
**modes of behaviour**, according to which 'matter' makes itself known.
The most important group of behaviours to me is that which I refer to as
'my body' – 'this material body made up of the Four Primary Modes'
(__kāyo rūpī catummahābhūtiko__, https://suttacentral.net/mn74/en/sujato[MN 74]).

____
And what, monks, is Feeling (__vedanā__)? It is these six
feeling-groups, namely: feeling sprung from Contact with the eye,
feeling sprung from Contact with the ear, feeling sprung from Contact
with the nose, feeling sprung from Contact with the tongue, feeling
sprung from Contact with the body, feeling sprung from Contact with the
mind. This, monks, is called Feeling.
____

In the above passage, by Contact (__phasso__) is not meant what is
commonly referred to as 'sense-impression'. As we shall see later on,
Contact is the *coming together* of three things, the sense-base (eye,
ear, etc.), the corresponding percept (sight, sound, etc.), and the kind
of Consciousness involved (eye-consciousness, ear-consciousness, etc.).

[quote, role=quote]
____
And what, monks, is Perception (__saññā__)? It is these six
perception-groups namely: sight-perception, sound-perception,
smell-perception, taste-perception, touch-perception, idea-perception
(__dhammasaññā__). This is called Perception.

And what, monks, are Determinations (__sankhārā__)? It is these six
intention-groups (__cetanākāya__), namely: intention with regard to
sight, intention with regard to sound, intention with regard to smell,
intention with regard to taste, intention with regard to touch,
intention with regard to ideas. These, monks are called Determinations.

And what, monks, is Consciousness (__viññāna__)? It is these six
consciousness-groups, namely: eye-consciousness, ear-consciousness,
nose-consciousness, tongue-consciousness, body-consciousness,
mind-consciousness. This, monks, is called Consciousness.

-- https://suttacentral.net/sn22.56/en/bodhi[SN 22.56], Phases of the Clinging Aggregates
____

The personality is thus analysed and broken up into its constituent
parts. My entire being is composed of them. Beyond them there is naught
else for me. *My world* is the totality of these Five Grasping Groups.
They constitute **my world**.

None of these Groups can however exist by itself separated from the
others. They are inseparable, and of their inseparability the Venerable
Sāriputta says:

[quote, role=quote]
____
Whatever, friend, there exists of Feeling, of
Perception, and of Consciousness, these things are associated and not
dissociated, and it is impossible to dissociate one from the other and
show their differences. For, whatever one feels, one perceives and
whatever one perceives, of that one is conscious.

-- https://suttacentral.net/mn43/en/sujato[MN 43], The Great Classification
____

Then again we have the Buddha teaching:

[quote, role=quote]
____
Were one, monks, to declare
thus: 'Apart from Form, apart from Feeling, apart from Perception, apart
from Determinations, I will show the coming, or the going, or the
disappearance, or the appearance, or the growth, or the increase, or the
abundance of Consciousness' -- that is not possible.

-- https://suttacentral.net/sn22.53/en/bodhi[SN 22.53], Engagement
____

Before proceeding any further it is extremely important to understand
clearly what the Buddha defines as Grasping (__upādāna__), or as
Holding.

The difference between life and inanimate things is that in the former
there is *intention*. All conscious action is *intentional*, whilst
action pertaining to inanimate things is devoid of intention.

Now, in the context of the Five Grasping Groups, the Buddha defines the
Group of Determinations as the Group of Intention (__cetanā__). But why
does he describe it is a *Grasping* Group? The rest of mankind has seen
Intention as either good or bad intention, moral or immoral intention,
and so on. Nevertheless the Buddha appears to see something far more
fundamental and deep-rooted in it. All these intentions, whether they be
good or bad, moral or immoral, or anything else, he groups together and
describes as a Grasping. To him they all appear to be basically of one
and the same character. They are all forms of Grasping.

What then is Grasping?

And what precisely is the difference between Grasping (__upādāna__) and
Intention (__cetanā__)?

This, more than any other, is the fundamental question posed by the
Buddha's Teaching.

Now, it is easy to *state* the answer, but it is extremely difficult to
*see* it.

The answer is: essentially, all notions of subjectivity, all notions of
a 'self' or a 'person' or a 'somebody', all thoughts of 'I' and 'mine',
are Grasping. Thus the Grasping Group of Determinations (here Intention)
means, the **Group of Intention based an notions of 'self' and thoughts
of 'I' and 'mine'**. Intentions which are *not* based on any notion of
'self' or any thought of 'I' or 'mine' whatever are merely a Group of
Intention.

We shall consider the relationship between the three notions: 'self',
'I' and 'mine' in more detail later on. Of these three notions, the most
fundamental one is 'mine'. To *grasp* something (or *hold* something)
means to *consider it as 'mine'*. It is not easy to *see* this. But it
is extremely important that it is seen.

To grasp Form means: to consider Form as 'mine'. The Grasping Group of
Form means *Group of Form considered as 'mine'*. So it is with the
other Groups.

Further, if there be anything that is grasped or can be grasped, then
that is the Five Groups or a part thereof. When I say I grasp a certain
external material object, what I really mean is that I grasp those
feelings, perceptions, etc., which arise when I become conscious of that
object. If I do not want those particular feelings, perceptions etc.,
then I do not want the object also, and hence will not grasp it.

Now, just as much as one grasps Form, one grasps Feeling, Perception,
Determinations and Consciousness also. One considers them all as 'mine'.

My world is the Five Grasping Groups that go to make me up. If there is
anything that I must comprehend, then it must be these.

[quote, role=quote]
____
Monks, I will show you things that are to be comprehended, and what
comprehending is ... Do ye listen to it. And what, monks, are the things
to be comprehended? Form, monks, is a thing to be comprehended; Feeling
is a thing to be comprehended; Perception is a thing to be comprehended;
Determinations are a thing to be comprehended; Consciousness is a thing
to be comprehended. These, monks, are the things to be comprehended. And
what, monks, is comprehending ...

-- https://suttacentral.net/sn22.106/en/sujato[SN 22.106], Should Be Completely Understood
____

The immediate question that arises is: Could there be a Group of Form, a
Group of Feeling, a Group of Perception, a Group of Determinations, a
Group of Consciousness which is wholly and entirely *devoid* of notions
of 'self' and thoughts of 'I' and 'mine'? Or, as against the Five
Grasping Groups could there be just the Five Groups? Particularly, with
regard to intentional action, could there be any such action which is
*unaccompanied* by any notions of 'self' and thoughts of 'I' and 'mine'?

For the present we leave this question unanswered and proceed.
