[[ch-16-satipatthana]]
= 16. A Note on the Four Applications of Mindfulness

__(Cattāro Satipaṭṭhānā)__

[[start]]The actual way of living out the Noble Eightfold Path for the
development of Wisdom and therewith gaining deliverance from Suffering,
or for attaining Arahatship, is the practising of the Fourfold
Applications of Mindfulness __(cattāro satipaṭṭhānā)__. How one
practises this Way of Mindfulness is given in the Discourse called the
__Mahā Satipaṭṭhānā Sutta__.footnote:[https://suttacentral.net/dn22/en/sujato[DN 22] and https://suttacentral.net/mn10/en/sujato[MN 10]]

It is sometimes thought that the practice of this Way of Mindfulness can
be undertaken without any prior understanding of the Buddha's Teaching.
This is wrong. To the one who examines the _Satipaṭṭhānā Sutta_ carefully
it is quite clear that there must be a good understanding of the
Teaching if one is to embark on the practice of the four _satipaṭṭhānas_
so to obtain any beneficial results. Repeatedly the _Satipaṭṭhānā Sutta_
says ‘abides seeing the nature of things in things’ (__dhammesu
dhammānupassī viharati__),
and this abiding is defined as understanding or knowing as
it really is __(yathābhūtaṁ pajānāti)__, This means that the individual
practising it is one who is **seeing**.

Further, the _Sutta_ says that if the _Satipaṭṭhānā_ is practised for
between seven years to seven days the individual so practising it can
expect either Arahatship or __anāgāmi__-ship. This therefore indicates
that, if such great results are to be expected, its practice has to be a
full-time pursuit which cannot in any way be taken lightly. For
instance, _kamesu micchācārā vāyāmo_ will not be a mere avoidance of
‘wrongful’ sex conduct as it is sometimes supposed to be, but a
*complete cutting away* from *all* pleasures of the senses. Such a
thorough practice is very difficult for a householder. Therefore it
would be incorrect to expect one to become a __sotāpanna__, _sakadāgāmi_
or __anāgāmi__, or even to reach the Path, by a repetition of the
_Satipaṭṭhānā Sutta_ however often and regularly that be.

It is also sometimes thought that the fruits mentioned in the
_Satipaṭṭhānā Sutta_ can be achieved quickly and in a comfortable manner
without sufficient renunciation. Such individuals sooner or later find
themselves disillusioned. And then the worst of it all happens. Having
been so disillusioned, they begin to wonder whether the Buddha has been
right or wrong; and to add to the bargain they imagine that they are now
in a better position to wonder.

The Buddha says that the _Satipaṭṭhānā_ is the ‘one and only way’
__(ekāyano maggo)__ to the full comprehension of the Four Noble Truths
and therefore to Arahatship. In order to see this one should examine in
detail what is meant by ‘abides seeing the nature of things in things’
__(dhammesu dhammānupassī viharati)__.

_Viharati_ means abides or lives. That means one is having living
experience. In other words one is *conscious* of something Categorizing
broadly, one is conscious of the four Groups of Form, Feeling,
Perception and __Determinations__. That any of these Four Groups is
*present* means one is conscious of it.

Consciousness is *always* entailed. That is why Consciousness is not one
of the four _satipaṭṭhāna_ -- the four _satipaṭṭhānas_ being on the Body
(i.e. the most important Form to one), Feeling, Mentality __(citta)__
and dhammas __(things)__. Not doubt Consciousness is included in the
list of the *dhammas* which are to be contemplated on under the fourth
_satipaṭṭhāna_ called __dhammesu dhammānupassī viharati__. But that is
different.

Now, all living experience can be classified under two categories:

1.  Experiencing something and having *right* knowledge about the experience,
2.  Experiencing something and having *wrong* knowledge about the experience.

I can see a rope and recognize it as a rope, or I can see a rope and
take it for a snake. Whilst seeing the sun shining upon the sand I can
take it to be ‘water’ or to be the sun shining upon the sand. The
seeing, together with the wrong understanding, is as much a living
experience as the seeing together with the right understanding is.
Likewise one experiences a certain thing. One feels a feeling (__vedanaṁ
vediyāmī__). That is, there is _vedanāsu_ ... __viharati__. One
experiences a lustful thought __(sarāgaṁ cittaṁ)__. That is, there is
_citte_ ... __viharati__. Likewise there is the experience of the
various _dhammas_ That is, there is _dhammesu_ ... __viharati__. But -
and this is the important thing -- one can see the true nature of that
which is being experienced *or* not see it. Seeing the true nature of
the feeling that is being experienced is the __vedanānupassī__.
Likewise, seeing the true nature of the thought is the __cittānupassī__.
Seeing the true nature of the _dhamma_ is the __dhammānupassī__. So,
together we get __vedanāsu vedanānupassī viharati__, _citte cittānupassī
viharati_ and __dhammesu dhammānupassi viharati__.

The position with regard to the _satipaṭṭhāna_ on the body is slightly
different towards the latter part, in that one does not and cannot
experience in oneself all the states of the body described therein, such
as the dead body in the charnel-field, though of course one sees that
the same fate will befall one's own body. In this particular case one
sees the phenomenon externally (i.e. as of another) but as applicable
internally (i.e. to oneself) too. A matter worthy of note in this
_satipaṭṭhāna_ concerning the body is the use of the word
__kāyasaṅkhāra__. Having spoken of the in-breathing and out-breathing,
the word _kāyasaṅkhāra_ is brought in. __Kāyasaṅkhāra__, we have seen,
has been defined as in-breathing and out-breathing. Diverting the mind
to _kāyasaṅkhāra_ is to indicate that the in-breathing and out-breathing
is the _saṅkhāra_ upon which the body stands supported When the thing
(body, in this case) is seen to depend on a _saṅkhāra_ (breathing, in
this case) that is subject to arising and passing away, then it is seen
that the thing (body) is also subject to arising and passing away, and
is therefore Not-self. Therefore to translate _kāyasaṅkhāra_ as
‘activity of the body’ or as ‘bodily formation’ is not only wrong but
also misleading and misses the entire purpose.

It is quite clear that there can be *no other way* for one to fully
comprehend things. The _dhammesu_ ... _viharati_ part is necessary for
*full* comprehension, since full comprehension comes only with actual
experience. That is why, though the _sekha_ sees the cessation of
Suffering, he is described as not having fully comprehended it. To fully
comprehend it or *penetratively* see it *through and through* he must
also *experience* it. The Arahat is at all times experiencing the
cessation of Suffering. He therefore fully comprehends it and sees it
penetratively through and through.

[[truth-for-him]]The _Satipatthānā Sutta_ assumes a prior understanding of the Buddha's
Teaching. Obviously, this understanding cannot be obtained from this
__Sutta__. It has to be obtained from the other Suttas. Therefore,
before embarking on the actual practice of the _Satipatthāna_ one has to
go through the other Suttas and devote a great deal of time to trying
to obtain sufficient understanding of the Buddha's Teaching. And the
most certain way of obtaining a proper understanding of it is to build
one's understanding on the very fundamentals that the Buddha has taught
in the __Mūlapariyāya Sutta__. But very hard work is needed. In
conclusion one can only repeat what has already been said in the preface
- that is, that though these fundamentals and their resultant
implications are very difficult to **see**, they edify him who sees
them. They are truth **for him**.
