[[suffering]]
Suffering
---------

Just as one does with some other doctrines in Buddhism one imagines all
too soon that one has comprehended the doctrine of Suffering also. Such
imaginings and coming to conclusions effectively impede one's progress.
For one believes one has understood what in truth one has not.

The _puthujjana_ meets with sufficient Suffering in his life. He may
have also heard about the Buddha having declared that life is Suffering.
But yet, in spite of it all, however much Suffering he undergoes, he is
not drawn towards the Buddha's Teaching, which offers him the way out of
Suffering. He contents himself by feeling that he will in time get over
his present state of Suffering, and that his present state of Suffering
is just another one of those aspects of life which he must put up with.
"Sense pleasures are said by me to be of little satisfaction, of much
Suffering, of much tribulation, wherein is more peril."footnote:[MN 22]
The _puthujjana_ does not see this.

The _puthujjana_ delights in the fact of his existence. 'I exist' or 'my
existence' is something desirable to him. He delights in notions of
'self'. He delights in seeing things as 'mine'. "'All is mine', he
conceives. He delights in All" -- __sabbaṁ meti maññati sabbaṁ
abhinandati__.footnote:[MN 1] He delights in 'self'-existence. He does
not see that 'self'-existence is Suffering. He does not see that
delighting in 'self'-existence is really a delighting in Suffering. He
can even have an aversion to destroying his thoughts of 'I' and 'mine',
which means he can have an aversion to the Buddha's Teaching, an
aversion to treading the Noble Eightfold Path that leads to the utter
destruction of these thoughts. It is therefore no surprise that the
Buddha was rather hesitant at the very outset to teach what he had
discovered.

The reason for the _puthujjana_ acting in this fashion is that he really
does *not* see Suffering. He may *believe* that he sees Suffering, but
actualy he does not see it. For him to see Suffering he must see
Impermanence and Not-self too. The perception of Suffering comes only
together with the perception of Impermanence and Not-self. And
developing that perception is by no means an easy task.

'Self' always implies permanency, and hence desirability. The
_puthujjana_ has to see that what he takes to be his 'self' (thereby to
be permanent and desirable) is really Not-self. This he can only see by
seeing that what he takes as his 'self' is impermanent. When that which
he takes to be 'self' is seen to be impermanent he no longer takes it to
be 'self', and therewith he loses desire for it. He also sees that by
taking it to be 'self', whilst in truth it is Not-self, he is always led
into betrayal and disappointment, i.e., he is always led into Suffering.

____
"Neither do I, monks, see that holding to a belief in 'self' from the
holding to which there would not arise sorrow, lamentation, suffering,
grief, despair."footnote:[MN 22]
____

When this insight grows in him he sees that he had been working right
through with a deception -- the deception of 'self'. He sees that he had
been working on the basis that a deception was the actual thing, and
that therefore it was always a case of betrayal, disappointment, grief,
agitation, worry, suffering, to some degree or other. "It is just
Suffering that is produced, Suffering that persists and disappears.
Nought beside Suffering is produced, nought beside Suffering
ceases."footnote:[SN I, Bhikkhunī Saṃyutta, Bhikkhunī Vagga, Sutta, No.
10.] To the extent one sees this, to that extent one has right view.

When the individual no longer regards anything as 'self' (which only
means that he no longer regards any of the Five Grasping Groups as
'self') he has got rid of his __sakkāyadiṭṭhi__. He has then crossed
over from the plane of the _puthujjana_ to the plane of the _Ariyas_
(Noble Ones), and along with it he has left a whole heap of Suffering
behind him which otherwise he would have to undergo. Since he may still
have thoughts of 'I' and 'mine' left in him, he will yet have Suffering.
But that Suffering will be nothing compared with what it was when he was
a __puthujjana__.

The Buddha summarily defines Suffering as the Five Grasping Groups:
"Birth is Suffering, decay is Suffering, disease is Suffering, death is
Suffering, union with the undesired is Suffering, being sundered from
the desired is Suffering, not getting what is wished for is Suffering.
In short, the Five Grasping Groups are Suffering."footnote:[FIXME
missing footnote] This essentially means, all notions of 'self', all
thoughts of 'I' and 'mine' are Suffering.

Birth, decay disease, death, etc., are all Suffering because they apply
to a 'self' or an 'I' who is subject to all these. The _puthujjana_
thinks 'I was born' or 'I will be born' or 'I am diseased' or 'I am
decaying' or 'I will decay' or 'I will die' or 'I am not getting what I
want', etc. He thus laments and grieves and despairs and sorrows, and so
suffers. It is 'I' who is lamenting. It is 'I' who is disappointed and
betrayed by the scheme of things. It is 'I' who is grieving, etc. It is
'my' body that is altering in a manner that 'I' do not wish it to. It is
'my' perception that 'I' am not satisfied with, and so on. If 'my' life
or 'my' so and so's life is not affected then there is no worry, no
care, no Suffering. What is there to care for or get worried about a
life that does not concern 'me'? For a world that is not 'mine'? There
is attachment to something only because that something is 'mine' or has
to do with 'mine'. For me to be concerned about something it has to have
a connection with *me* in *some* way or other.

____
"I will show you, monks, worry from Grasping, likewise no worry from no
Grasping, Do ye listen."

"And how, monks, is there worry from Grasping?"

"Herein, monks, the untaught _puthujjana_ regards Form thus: 'This is
mine; this am I; this is my self'. Of such a one the Form alters and
becomes otherwise. Owing to the altering and otherwise-ness of Form,
sorrow and grief, woe, lamentation and despair arise in him. Thus,
monks, there is worry from Grasping."
____

The same applies to the other four Groups, Feeling, Perception,
Determinations and Consciousness.

"And how, monks, is there no worry from no Grasping?"

"Herein, monks, the well-taught Ariyan disciple (Noble diSCiple) regards
Form thus: 'Not, this is mine; not, this am I; not, this is my
self"footnote:[_Na_ _etaṁ mama_ is usually translated as "This is not
mine". But this rendering tends to leave in the reader's mind the
impression that though *this* is not mine, there may be something else
that is mine. In fact such an impression is deliberately made to remain
in the reader's mind when, for instance, _na eso me attā_ is translated
by scholars as "this is not the self of me" -- as if to say that *this*
is not my self, but something else is. Such situations have to be
avoided. "Not, this is mine" (which is a translation by Ñāṇavīra Thera)
may not sound quite perfect. But accuracy in meaning is more important
than readability. The same of course applies to the whole triad.] (__na
etaṁ mama, na eso ahaṁ asmi, na eso me attā__). Of such a one the Form
alters and becomes otherwise. But in spite of the altering and
otherwise-ness of Form, sorrow and grief, woe, lamentation and despair
arise not in him. 'Thus, monks, there is no worry from no
Grasping".footnote:[SN III, Khandha Saṃyutta, Nakulapita Vagga, Sulta
No. 8.]

The same again applies to the other four Groups.

Now, it is the *same* phenomenon, viz., altering and becoming otherwise,
that is taking place with the untaught _puthujjana_ and the well-taught
Ariyan disciple. But their attitudes towards the phenomenon, the ways in
which they regard it (__samanupassati__) are of opposing kinds. The
first way brings up SuffeIing, the second way prevents Suffering coming
up. With the Arahat, of course, the position is different, because, he
*having come* to the end of *all* thoughts of 'self', and of 'I' and
'mine', *neither* regards things as 'mine', etc., *nor* as 'not mine',
etc. With the Arahat there is no Suffering whatever. No question of the
arising of Suffering or not-arising of Suffering is present for him. Of
the differences between the __puthujjana__, the Ariyan disciple, and the
Arahat, we shall speak in detail later.

When a person begins to see Impermanence, Not-Self, and therewith
Suffering as the Ariyan disciple does, he begins to lose delight in
thoughts of 'I' and 'mine'. He truly gets drawn towards the Buddha's
Teaching, and he begins to see a definite purpose in his existence which
makes his existence a very important matter to him. Henceforth he does
not aimlessly wander 'taking things as they come'. He lives with a
purpose and fashions his life relentlessly to achieve that purpose.

Actually, in the end, the _puthujjana_ sees nothing of which he can
rightly say: this and *no other* is what has to be done. Fettered he is
born, fettered he exists, fettered he dies, fettered to 'self'. He finds
that his existence (__bhava__) is without meaning and purpose. Yet he
knows not how to end his purposeless existence. But the Ariyan disciple
sees a purpose to his existence, and sees that this purpose is nothing
but the bringing of that existence to an end (__bhavanirodha__).

Since the Arahat has no notions of Subjectivity, no thoughts of 'I' and
'mine' whatever, he has come to the extinction of that which conditions
Suffering. When the condition for Suffering is extinct, Suffering is
also extinct. He has come to the extinction of Suffering. He has come to
the cessation of Suffering -- __dukkhanirodho__. "He having put aside
all tendency towards attachment, having dispelled all tendency to
resistence, having removed tendencies to views and conceits such as 'I
am', having put aside ignorance, Knowledge having arisen, he is here and
now an end-maker of Suffering."footnote:[MN 9] No more can any Suffering
arise in him. He certainly can have painful or unpleasant feeling, but
such painful or unpleasant feeling, is *not* Suffering. In such an
eventuality he just bears the pain. He does not *suffer* by it.
Suffering is all over with him. "He feeling a pleasant feeling, feels it
unbound (__visaññutto__) to it; feeling an unpleasant feeling, feels it
unbound to it; feeling a neutral feeling, feels it unbound to it. He,
monks, is called an Aryan disciple unbound to birth, decay, death,
sorrow, grief, suffering, lamentation and woe; he is unbound to
Suffering, I declare."footnote:[SN IV, Vedanā Saṃyutta, Sagātha Vagga,
Sutta No. 6.]

Suffering (__dukkha__), it must be noted, does not refer to bodily pain.
In the Pali, the word _dukkha_ is used to denote Suffering, and also to
denote that a feeling is painful (as in __dukkhaṁ vedanaṁ__). Suffering
is something mental. It refers to sorrow, woe, lamentation, grief,
despair, agitation, worry, etc., all of which are **mental**. That is
why the Arahat can have bodily pain, but no Suffering.footnote:[When the
Arahat's body changes to the state that the _puthujjana_ considers as a
state of decay, the Arahat can then have bodily painful feelings. But
these bodily painful feelings do not lead him to consider the body as
having decayed, a consideration which is nothing but Suffering since it
is always attended with grief, fear, etc.]

When the _puthujjana_ experiences a painful feeling, he feels a
repugnance for it. This means he has a twofold feeling, i.e., a bodily
painful feeling and a mental painful fee1ing. "He feels a twofold
feeling, bodily and mental."footnote:[SN IV,Vedanā
Saṃyutta,Pathamasagātha Vagga, Sutta No. 6.] He knows no refuge from
painful feeling other than sensual pleasure. He is thus bound to sensual
pleasure. The Arahat on the other hand can also experience a painful
feeling. But neither does he have a repugnance for painful feeling nor
has he a delight in sensual pleasure. Whether it is a plesant feeling,
or an unpleasant or painful feeling, or a neutral feeling, the Arahat is
neither worried by it nor delighted by it. For him, it is just a
feeling.

____
"Now on that occasion a certain monk was seated not far from the Exalted
One in cross-legged posture, holding his body upright, enduring pain
that was the fruit of former __kamma__, pain racking, sharp and bitter;
but he was mindful, composed and uncomplaining. And the Exalted One saw
that monk so seated and so employed, and seeing the meaning of it, at
that time gave utterance to this saying of uplift: 'For the monk who
hath all _kamma_ left behind, and shaken off the defilements aforetime
gathered, who stands fast without 'mine' -- for such there is no need to
talk to folk'."footnote:[Udāna, Nanda Vagga, Sutta No. 1.]
____

The Arahat does not need to talk to folk, entreating them to relieve him
of his pain, or complaining to them about his pain, because he does not
*suffer* by it, because it gives him no grief, lamentation, etc. For
grief, lamentation, etc. to be there he must think '**I am** in pain',
and such thoughts are completely extinct in him. Any pain that comes his
way -- that he just bears.

Again:

The Buddha says that for the _puthujjana_ *all* is Suffering. That is to
say, with regard to feeling for instance, whether the _puthujjana's_
feelings are pleasant, unpleasant or neutral, they are nevertheless
Suffering. It is not only unpleasant feeling, that is Suffering for him,
but *all* feeling.footnote:["Whatever is felt, that is Suffering" --
_yad kiṁci vedayitaṃ tad dukkhasmin ti_ (SN II, Abhisamaya Saṃyutta,
Kalārakhattiya Vagga, Sutta No. 2). Or again, "It is just Suffering that
is produced, Suffering that persists and disappears. Nought beside
Suffering is produced, nought beside Suffering ceases" -- _Dukkhaṁ eva
hi sambhoti, dukkhaṁ tiṭṭhati veti ca, nāññatra dukkha sambhoti,
nāññatra dukkhā nirujjhati ti_ (SN I, Bhikkhunī Saṃyutta, Bhikkunī
Vagga, Sutta No. 10).] It is precisely *this* that is difficult to see,
and hence the difficulty of seeing the First Noble Truth.

To see this one has to turn towards the fundamental characteristic of
the __puthujjana__, which is but a regarding things as 'mine'. The
_puthujjana_ regards that which should be regarded as '**not** mine' as
'mine'.That means he regards the Five Grasping Groups (which constitute
*all* for him) as 'mine' whilst he should regard them as 'not mine'.
With regard to feeling, whether the feeling he experiences is pleasant
or unpleasant or neutra1, he regards it always as 'mine'. This regarding
the Groups as 'mine' is always attended with agitation and worry to
*some* degree or other, which only means that he is **always suffering
to some degree or other**.[multiblock footnote omitted] As we shall see
in the next chapter, the _puthujjana_ acts in this fashion because he is
Ignorant of (i.e. he does not **see**) the Four Noble Truths, viz., the
Noble Truth of Suffering, the Noble Truth of the Arising of Suffering,
the Noble Truth of the Ceasing of Suffering, and the Noble Truth of the
Path leading to the Ceasing of Suffering. In other words, the
_puthujjana_ continues to suffer with no prospect of reducing his
Suffering, and therefore continues to be a __puthujjana__, because he is
ignorant of the Buddha's Teaching.

____
"Now I, brahmin, lay down that a man's wealth is the
Dhamma,footnote:[i.e. the Buddha's Teaching.] Ariyan, beyond the world
(__lokuttara__)."footnote:[MN 96]
____
