[[ch-14-the-puthujjana-sekha-and-asekha]]
= 14. The Puthujjana, Sekha and Asekha

There are three distinct classes of individuals that the Buddha's
Teaching brings out, i.e., the __puthujjana__, the _sekha_ (Learner), and
the _asekha_ (Learning-ender). The fundamental differences between them
are as follows:

1.  The _puthujjana_ regards things as ‘mine’.
2.  The _sekha_ (learner) knows and sees that the notion ‘mine’ is wrong
but the notion ‘mine’ still arises in him. Therefore he regards things
as ‘not mine’.
3.  The _asekha_ (Learning-ender) not only knows and sees fully that the
notion ‘mine’ is wrong, but also no thoughts of ‘mine’ whatsoever arise
in him. Thus he neither regards things as ‘mine’ nor as ‘not mine’. The
_asekha_ is the Arahat.

From these fundamental differences follow all other differences that lie
between them. We can therefore indicate the differences between them in
other ways too. As an example, we may speak of their differences as
follows; the _puthujjana_ does not see the Buddha's Teaching; the
_sekha_ sees the Buddha's Teaching but has not fully experienced it; the
_asekha_ not only sees the Buddha's Teaching but also *fully*
experiences it.

To the extent the _sekha_ experiences the Teaching, to that extent does
he see the Teaching better. His seeing is still imperfect and his
cultivation of the Four Applications of Mindfulness{empty}footnote:[See <<ch-16-satipatthana.adoc#start,Chapter 16: On the Four Applications of Mindfulness>>] is only partial
(__catunnaṁ kho āvuso satipaṭṭhānānaṁ padesaṁ bhāvitattā__, https://suttacentral.net/sn47.26/en/bodhi[SN 47.26])
as against that of the _asekha_ which is complete (__satipaṭṭhānānaṁ samattaṁ bhāvitattā__, https://suttacentral.net/sn47.27/en/bodhi[SN 47.27]).

He, the __sekha__, can see a part of the
Teaching without experiencing it. But seeing and understanding in the
*fullest* sense comes only with the experience of it. It is therefore to
be expected that there would be various classes of _sekhas_ depending on
the extent to which they experience the Teaching.

In the following Sutta we have the difference between the _sekha_
and the _asekha_ denoted as follows:

____
Again, monks, the monk who is a _sekha_ knows the five controlling
faculties: faith, energy, mindfulness, concentration, and wisdom. Yet he
neither lives experiencing with the body, nor penetratively sees with
wisdom, what they lead to, their excellence, their fruit, and their end ...

Here, monks, a monk who is an _asekha_ knows the five controlling
faculties: faith, energy, mindfulness, concentration, and wisdom. He
lives experiencing with the body, penetratively seeing with wisdom, what
they lead to, their excellence, their fruit, and their
end.

-- https://suttacentral.net/sn48.53/en/sujato[SN 48.53], A Trainee
____

The _sekha_ has faith in the fact that deathlessness can be attained by
developing the five controlling faculties. He ‘stands knocking at the
door of deathlessness’ -- __amara dvāraṁ āhacca tiṭṭhati__ (https://suttacentral.net/sn12.49/en/bodhi[SN 12.49]).
But the _asekha_ having developed these faculties
fully has achieved deathlessness and lives experiencing deathlessness.
Arahat Sāriputta said that the latter was the case with him.
Incidentally, it is wrong to think that the _puthujjana_ has these
faculties. The _puthujjana_ does not possess these faculties. It is the
_sekha_ who has acquired them, but of course he has to develop
them (https://suttacentral.net/sn48.12/en/sujato[SN 48.12] and https://suttacentral.net/sn48.18/en/sujato[SN 48.18]).

Khemaka, an _Anāgami_ (i.e. one of the higher classes of __sekhas__) says:

____
Though, friends, I discern in the Five Grasping Groups no self
nor aught pertaining to self, yet I am not Arahat, nor one in whom the
taints are destroyed. Though, friend, in the Five Grasping groups is
found ‘I am’, yet I do not discern that I am this ‘I am’.

{empty}... Friends, though an Ariyan disciple has put away the five lower fetters,
yet there remains in his Five Grasping Groups the conceit ‘I am’, the
desire ‘I am’, the tendency ‘I am’, still not removed from him.

-- https://suttacentral.net/sn22.89/en/bodhi[SN 22.89], Khemaka
____

The _puthujjana_ is *not* on the Path to __Nibbāna__, whilst the _sekha_
is on the Path. And once an individual is on the Path, the Buddha
teaches that he is assured of arriving at __Nibbāna__. The _sekha_ is
assured of being an _asekha_ (i.e. Arahat). The _asekha_ or the Arahat
*has trod the Path to completion* and has arrived at the goal of
__Nibbāna__. He lives experiencing __Nibbāna__.

Now, all _sekhas_ and the _asekhas_ are referred to as __Ariyas__. Thus,
in the broadest classification we have _puthujjanas_ and __Ariyas__.
Literally, _Ariya_ means Noble.

We may now examine in some detail the various categories of individuals
classed as _puthujjanas_ and __Ariyas__.

Two classes of _puthujjanas_ can be distinguished:

1.  The _assutavā_ (one who has not heard). He has not heard the
Buddha's Teaching, and so he holds views contrary to the Teaching.
2.  The _anulomikāya khantiyā samannāgata_ (one possessed of
acquiescence in agreement). He has heard the Teaching, and he possesses
tacit agreement with the Teaching. But he is not one who has merely
studied the Teaching and or professes to follow the Teaching. He is much
more than that. He makes a genuine attempt to realize the Teaching in
himself, knowing that he still does not actually see the
Teaching. (https://suttacentral.net/an6.101/en/sujato[AN 6.101])

Of these two kinds of _puthujjana_ the _assutavā_ is me kind that is to
be found more often.

There are eight classes of __Ariyas__. In ascending order of perfection
they are:

1.  _Sotāpatti-phala-sacchikiriyāya paṭipanno_ -- The one who practices for the realization of the fruit of Steam-entrance.
2.  _Sotāpanno_ -- The Stream-entrant.
3.  _Sakadāgāmi-phala-sacchikiriyāya paṭipanno_ -- The one who practises for the realization of the fruit of once-return.
4.  _Sakadāgāmi_ -- The Once-returner.
5.  _Anāgāmi-phala-sacchikiriyāya paṭipanno_ -- The one who practises for the realization of the fruit of non-return.
6.  _Anāgāmi_ -- The Non-returner.
7.  _Arahattāya paṭipanno_ -- The one who practises for the realization of Arahatship.
8.  _Arahā_ -- The Arahat, or the Consummate One.

Of these eight, the first seven are not yet Arahat. That is, they are
still not Consummate or Perfect, and have still more work to do. Thus
they are called _sekhas_ (Learners). But they are all on the Path, and
are assured of becoming Arahats or Consummate Ones. They have crossed
from the plane of the _puthujjana_ __(puthujjana-bhūmi)__ to the plane
of the Noble __(ariya-bhūmi)__. The last and the eighth, i.e., the
Arahat, has done whatever was to be done, has finished training, has
achieved the goal, has laid down the burden, has attained the Consummate
state, has attained __Nibbāna__. He is therefore _asekha_ (Learning-ender).

Thus, with the __puthujjana__, we have nine kinds of
individuals (https://suttacentral.net/an9.9/en/sujato[AN 9.9]).
If we take into account the two types of _puthujjanas_ we then have ten kinds of individuals.

It will be seen that of the seven _sekhas_ there are fruit-attainers
__(phala-lābhi)__, i.e., the __sotāpanna__, the _sakadāgāmi_ and the
__anāgāmi__. The remaining four are practising for the realization of
the corresponding fruit. Thus they are called path-attainers
__(magga-lābhi)__. They have attained to the path which will lead them
to the corresponding fruit. The _asekha_ is also a fruit-attainer. He
has attained to the fruit of Arahatship. The notion that the attainment
of the fruit is immediately followed by the attainment of the path is
wrong. This notion found in certain Commentaries is not in keeping with
the Suttas wherein the path-attainer is definitely said to be
practising for the realization of the fruit. There is therefore a time
interval between path-attainment and fruit-attainment.

____
Here, friends, a
monk develops insight preceded by serenity. In thus developing insight
preceded by serenity, the Path is born. He pursues that Path, develops
and practises it. In him thus pursuing, developing, and practising that
Path, the fetters are put away, and the latencies
cease.

-- https://suttacentral.net/an4.170/en/thanissaro[AN 4.170], In Tandem
____

However, the first class of Path-attainer *shall always* attain the
fruit before his death even if that fruit-attainment be just before
death. According to the Suttas one of two thing makes this fruit
attainment possible -- diligent work, or the crisis of approaching death
which provide the necessary impetus to attainment (https://suttacentral.net/sn25.1/en/sujato[SN 25.1]).
Unlike the _puthujjana_ who is subject to retrogression the _sekha_ whether he be a
path-attainer or a fruit-attainer progresses towards the goal.

The Buddha teaches that there are ten fetters which bind beings to
__bhava__, and the _sekhas_ who are fruit-attainers are generally
described in terms of the various fetters they have broken. These
fetters are (1) ‘person’-view __(sakkāyadiṭṭhi)__, (2) Doubt
__(vicikicchā)__, (3) Practice of rites and ritual
__(sīlabbata-parāmāso)__, (4) Desire for sense-pleasure
__(kāmacchando)__, (5) Ill-will __(vyāpāda)__, (6) Attachment to Form
__(rūparāgo)__, (7) Attachment to no-Form __(arūparāgo)__, (8) Conceit
__(māno)__, (9) Restlessness __(uddhaccaṁ)__, and (10) Ignorance
__(avijjāṁ)__. The first five are described as lower fetters
__(orambhāgiyāni saññojanāni)__ whilst the other five are described as
higher fetters (__uddhambhāgiyāni saññojanāni__, https://suttacentral.net/an10.13/en/bodhi[AN 10.13]).

The first fruit-attainer is called _sotāpanno_ (Stream-entrant). He has
destroyed the first three fetters of ‘person’-view, doubt, and practice
of rites and ritual. Entered the Stream (i.e. entered the __sota__)
means got on to the Noble Eightfold Path, the Stream __(sota)__ being
defined as this path:

____
The Stream, Sāriputta, is just this Noble
Eightfold Path, that is to say, right understanding, right thinking,
right action, right speech, right living, right effort, right
mindfulness, right concentration.

-- https://suttacentral.net/sn55.5/en/sujato[SN 55.5], With Sāriputta (2nd)
____

The second fruit-attainer is
called _sakadāgāmi_ (Once-returner). He has destroyed the first three
fetters and reduced lust, hatred and delusion (__tiṇṇaṁ saññojanānaṁ
parikkhayā rāgadosamohānam tanutta__); Therefore he has not only
destroyed the first three fetters but also has partly overcome the
fourth and the fifth fetters, namely desire for sense-pleasure and
ill-will. The third fruit-attainer is called _anāgāmi_ (Non-returner).
He has destroyed the first five fetters, i.e., the lower fetters. The
fourth and last fruit-attainer is of course the Arahat who has destroyed
all the ten fetters.

The first path-attainers, i.e., those practising for the realization of
the fruit of Stream-entrance, are of two kinds -- the _dhammānusāri_
(Dhamma-striver) and the _saddhānusāri_ (Faith-striver). These two have
just crossed over from the plane of the _puthujjana_ to the plane of the
__Ariya__. The _dhammānusāri_ is one who through wisdom is pleased with
the Dhamma to an extent, whilst the _saddhānusāri_ is one who through
faith is firmly attached to Dhamma (https://suttacentral.net/mn70/en/bodhi[MN 70] and https://suttacentral.net/sn25.1/en/sujato[SN 25.1]).
As stated earlier they are both incapable of passing away without realizing the fruit of
Stream-entrance, i.e., without becoming __sotāpanna__.

The maximum number of lives left for the _sotāpanna_ is seven
__(sattakkhattuṁ paramatā)__. Further, none of these seven lives will be
in an unfortunate sphere. He is assured of _Nibbāna_ or Enlightenment
within this period __(niyato sambodhi-parāyano)__. The _sakadāgāmi_ returns
once more to this world and accomplishes the destruction of Suffering
__(sakideva imaṁ lokaṁ āgantvā dukkhassantaṁ karoti)__. The __anāgāmi__,
when he dies here, will be reborn spontaneously in the Pure Abodes and
attains to Extinction there (https://suttacentral.net/an3.88/en/sujato[AN 3.88] and https://suttacentral.net/an3.89/en/sujato[AN 3.89]).

All this means that, as a cart pushed just over the hilltop will roll
down by its own weight without extra effort, so will the _sotāpanna_ in
any case end up in _Nibbāna_ within a maximum of seven further lives.
The Buddha however exhorts all _sekhas_ to act with diligence
__(appamādena karaṇīyan)__ and try to make an end of it all in this life
itself by attaining Arahatship.

____
Monks, just as a little bit of faeces
is foul smelling, even so do I not praise __bhava__, not even for so
brief a time as is needed for a finger snap.

-- https://suttacentral.net/an1.316-332/en/sujato[AN 1.328]
____
