[[ch-12-ignorance]]
= 12. Ignorance

We have seen that the arising of Consciousness is dependent upon
conditions.

In other words, the presence of an experience (the presence being
Consciousness, and the experience being Name-and-Form) is dependent upon
conditions.

These conditions determine *what* is to be present, i.e., they determine
what particular Consciousness is to be. All these conditions taken as a
whole are also Name-and-Form, which again is nothing but the other four
Groups.

But of these conditions totalled as Name-and-Form there is one condition
which plays a key role, viz., intention. Intention directs the play as
it were. And the direction along which intention directs is dependent
upon __taṇhā__.

Now, the Buddha teaches that Consciousness is dependent upon
Name-and-Form. He also teaches that Consciousness is dependent upon
Determinations (__saṅkhārapaccayā viññānaṁ__). That iS, with
Determinations as condition, arises Consciousness.

Thus we have, in the above mentioned instance, Determinations
(__saṅkhārā__) being synonymous with Name-and- Form. The reason is that
although intention is primarily a condition for the arising of
Consciousness, through intention *alone* pure and simple, Consciousness
cannot come about. All those other conditions such as
In-and-Out-Breathing, Perception, Feeling, etc., must also be present.
In the statement, Consciousness is dependent upon Determinations
(__saṅkhāra paccayā viññānaṁ__), the word Determinations (__saṅkhāra__)
includes all these things.

The question that arises now is: How is it that the Grasping Groups
persist in the manner explained so far and in *no other* manner? In
other words, why does life (save that of the Arahat's, of course)
persist in the manner it does and in no other manner? This same question
can be put in other ways too. For example, it may be put thus: If
_taṇhā_ is that which guides intentional action, and hence the play of
1ife, what is it that keeps this all important factor called _taṇhā_ in
existence?

The answer is: Ignorance of life. In other words, things are not *seen*
in their true nature. They are seen wrongly. And Ignorance of life means
nothing but Ignorance about the Five Grasping Groups.

__Taṇhā__, that is to say, wanting 'self'-existence and sense-pleasure,
is maintained because of Ignorance. "I dec1are, monks, that
_bhava-taṇhā_ (wanting 'self'-existence) is with nutriment, not without
nutriment. And what is the nutriment of __bhava-taṇhā__? Ignorance is to
be so called."footnote:[https://suttacentral.net/an10.62/en/bodhi[AN 10.62], Craving]

Ignorance can be defined in more than one way. It can be defined as not
seeing or not knowing the arising and ceasing of the Five Grasping
Groups.

____
"Ignorance! Ignorance! it is said, Lord. But what, Lord, is Ignorance,
and to what extent is one Ignorant?"

Herein, monks, the uninstructed _puthujjana_ does not, as it really is,
know Form that is of the nature of arising as Form that is of the nature
of arising; does not, as it really is, know Form that is of the nature
of passing away as Form that is of the nature of passing away; does not,
as it really is, know Form that is subject to arising and passing away
as Form that is of the nature of arising and passing away. He does not,
as it really is, know Feeling ... Perception ... Determinations ...
Consciousness ... This, monks, is called Ignorance, and to that extent
is there Ignorance."

-- https://suttacentral.net/sn22.126/en/sujato[SN 22.126], Liable To Originate
____

Not knowing the arising and ceasing nature of the Five Grasping Groups
means not knowing Impermanence. And not knowing Impermanence
simultaneously involves not knowing Not-self and not knowing Suffering.
Therefore Ignorance may also be defined as not knowing Impermanence,
Not-self and Suffering.

It shouldtbe clearly understood that by the word 'knowing'
(__pajānāti__) is not meant a mere conceptual and objective knowing, but
a knowing as true -- a seeing, a comprehending, with *no doubt* about it
(__tiṇṇa vicikiccho__).

Another way of defining Ignorance would be:

____
"Friend, non-knowledge of Suffering, non-knowledge of the arising of
Suffering, non-knowledge of the ceasing of Suffering, non-knowledge of
the Path leading to the ceasing of Suffering -- this, friend, is called
Ignorance."

-- https://suttacentral.net/mn9/en/bodhi[MN 9], Right View
____

Suffering, arising of Suffering, ceasing of Suffering, and the Path
leading to the ceasing of Suffering, are called the Four Noble Truths.
Thus Ignorance is the non-knowledge of the Four Noble Truths.

Now, _taṇhā_ is present because Ignorance is present. In other words,
since life is Ignorant of itself it has __taṇhā__. What then must be
present for Ignorance to be present? Or, on what condition does
Ignorance depend? This is a very important question.

____
"Monks, a first point of Ignorance is not to be discerned, so that one
may say: 'Before this was not Ignorance, it has come to be since.' This,
however, is to be discerned: 'Ignorance is dependent on this.' I say,
monks, that Ignorance is with nutriment, not without nutriment.

"And what is the nutriment of Ignorance? The Five Hindrances (__pañca
nīvaraṇā__) are to be so called. The Five Hindrances too, I declare, are
with nutriment, not without nutriment. And what is the nutriment of the
Five Hindrances? The three evil ways of conduct (__tīṇiduccaritāni__)
are to be so cal1ed. They too, I declare are with nutriment, not without
nutriment.

And what is the nutriment of the three evil ways of conduct?
Non-restraint over the senses (__indriya asaṃvaro__) are to be so
called. That too, I declare, to be with nutriment, not without
nutriment.

And what is the nutriment of non-restraint over the senses? Lack of
mindfulness and clear comprehension (__asatāsampajaññaṃ__) are to be so
ca1led. That too, I declare to be with nutriment, not without nutriment.

And what is the nutriment of lack of mindfulness and clear
comprehension? Improper attention (__ayoniso manasikāro__) is to be so
called. That too, I declare, is with nutriment, not without nutriment.

And what is the nutriment of improper attention? Absence of faith
(__asaddhiyaṃ__) is to be so called. That too, I declare, is with
nutriment, not without nutriment.

And what is the nutriment of absence of faith? Hearing of not-right
doctrine (__asaddhamma savanaṃ__) is to be so called. That too, I
declare, is with nutriment, not without nutriment.

And what is the nutriment of hearing of not-right doctrine? Association
with the unworthy (__asappurisasaṃsevo__) is to be so cal1ed.

"Thus, indeed, monks, the fulfilment of association with the unworthy
fulfils the hearing of not-right doctrine; the fulfilment of hearing
not-right doctrine fulfils absence of faith; the fulfilment of absence
of faith fulfils improper attention; the fulfilment of improper
attention fulfils lack of mindfulness and clear comprehension; the
fulfilment of lack of mindfulness and clear comprehension fulfils
non-restraint over the senses; the fulfilment of non-restraint over the
senses fulfils the three evil ways of conduct; the fulfilment of the
three evil ways of conduct fulfils the Five Hindrances; the fulfilment
of the Five Hindrances fulfils Ignorance. Such is the nourishment of
Ignorance, such is the fulfilment."

-- https://suttacentral.net/an10.62/en/bodhi[AN 10.62], Craving
____

Thus, according to the above, Ignorance finally depends upon not hearing
the Buddha's Teaching, and of course upon not practising it. At the same
time if we take all of the factors narrated in the above, beginning with
the Five Hindrances, (these Hindrances being lust, ill-will, sloth and
torpor, restlessness and worry, and doubt) upon which Ignorance depends,
we find that each and every one of these factors *involves the presence
of Ignorance.*

For the Five Hindrances, improper attention, etc., to be present
Ignorance must be present. It would then appear that Ignorance depends
upon Ignorance. This is in fact directly indicated in the __Sammādiṭṭhi
Sutta__.footnote:[https://suttacentral.net/mn9/en/bodhi[MN 9]] In this _Sutta_ it is said that
the condition for Ignorance is the cankers; "From the arising of the
cankers is the arising of Ignorance. From the ceasing of the cankers is
the ceasing of Ignorance." These cankers are in turn defined in the same
_Sutta_ as the canker of sense-pleasure, canker of __bhava__, and the
canker of **Ignorance**: "Friend, there these three cankers, viz., the
canker of sense-pleasure, the canker of __bhava__, the canker of
Ignorance." Thus Ignorance depends upon the canker of Ignorance.

That Ignorance depends upon Ignorance really means this: any thing upon
which Ignorance depends *involves* Ignorance. The Five Grasping Groups
is a matter of *not-knowing* things rightly. Thus all factors that make
for the *Grasping* Groups are individually also a matter of
*not-knowing* right1y. Ignorance is something negative and abstract --
**not-knowing**. Its corresponding direct positive manifestation is the
Grasping, which essentially is a considering things as 'mine'.

With every attempt the uninstnicted _puthujjana_ makes to gain right
knowledge he carries Ignorance with him. When he tries to spot out
Ignorance, to recognize Ignorance -- that he does with Ignorance. It is
as if a man sets out to catch a thief, but the thief himself leads the
man in his search, because the man does not recognize the thief as *the*
thief.

This indicates to us how firm Ignorance is and how difficult it is to
get rid of it, so much so that it appears almost an impossibility to get
rid of Ignorance without some exteral aid. It is this aid, however, that
the Buddha gives. He gives it in the form of a Teaching that goes
*against* the _puthujjana's_ understanding of things. That is why the
Buddha describes his Teaching as "going against the stream"
(__paṭisotagāmi__).footnote:[https://suttacentral.net/mn26/en/bodhi[MN 26]] The _puthujjana_
constantly thinks 'This is mine; this am I; this is my self.' The Buddha
points out to him that it is wrong, and teaches him to think instead
'Not, this is mine; not, this am I; not, this is my self'. It is because
of Ignorance that the _puthujjana_ thinks 'This is mine ...' But every
time he thinks against this stream, metaphorically speaking, he injects
into Ignorance a destructive poisonous dose. When this "going against
the stream" is practised there come a time when *all* notions of 'self',
*all* thoughts of 'I' and 'mine' are completely got rid of, never to
arise again.

____
"Lord, how knowing, how seeing, does there not come to be in this body
having Consciousness, and in all external indications, the tendency to
the conceit 'I' and 'mine'?"

"Rahula, whatever Form ... Feeling ... Perception ... Determinations ...
Consciousness, be it past, future, or present, external or internal,
gross or subtle, low or high, far or near -- all Consciousness -- (is to
be regarded as) 'Not, this is mine; not, this am I; not, this is my
self.' That is seeing things by right insight as they really are.

"Thus knowing, Rahula, thus Seeing, in this body having Consciousness,
and in all external indications, there comes to be no tendency to the
conceit 'I' and 'mine'.

-- https://suttacentral.net/sn22.91/en/bodhi[SN 22.91], Rahula
____

All thoughts of 'I' and 'mine' are completely got rid of means that
Ignorance is completely got rid of; which again means that the entire
purpose of all this effort is achieved, viz., Suffering is wholly and
entirely destroyed.

The Arahat has got rid of Ignorance, which means that the Arahat fully
**knows**, or that (Right) Knowledge has arisen (__vijjā uppanno__) in
him. And he fully knows means, he has *ended* Grasping. With him, the
'person' is extinct; 'my existence is extinct; Suffering is extinct.

It should be noted that three distinct types of individuals are involved
in all this. Firstly the _puthujjana_ who thinks 'This is mine ...'
Secondly, the Aryian disciple who *sees* that 'This is mine ...' is
wrong, but still is *not* rid of thoughts of 'I' and 'mine'. It is
*this* second type of individual who thinks 'Not, this is mine ...'. He
is called a "learner" (__sekha__), and he is *on the Path* to
Arahatship. Thirdly, there is the Arahat. The Arahat not only sees that
'This is mine ...' is wrong, but also *has completely rid* himself of
thoughts of 'I' and 'mine'. Therefore the Arahat does *not* have the
occasion to say 'Not, this is mine ...' either. He is called
"learning-ender" (__asekha__: literally "not-learner", but to prevent
any confusion it is better translated as "learning-ender").

ThuS, summarily: the _puthujjana_ says 'This is mine ...'; the Ariyan
disciple on the Path says 'Not, this is mine ...'; the Arahat says
neither.

These distinctions, particularly that between the Ariyan disciple on the
Path and the Arahat, should be noted, or else confusion can arise.

We have said that it is almost impossible to overcome Ignorance without
some extemal aid. How then did the Buddha overcome it without any such
aid? The Buddha said, "For me there is no teacher."footnote:[https://suttacentral.net/mn26/en/bodhi[MN 26], The Noble Search]
This means he overcame Ignorance by himself.

The answer is: though it is extremely difficult and appears almost
impossible, it is nevertheless possib1e. The destruction of Ignorance
*unaided* is something so difficult that it is extremely rare. It is
precisely as rare as the appearance of Buddhas.
