[[nibbāna]]
Nibbāna
-------

By now the reader may have obtained some idea of the individual called
the Arahat. Essentially, the Arahat is that individual who has no
notions whatever of 'self', and no thoughts whatever of 'I' and 'mine'.
Thus he is not subject to any form of Suffering whatever. In other
words, we may say that in the Arahat these things are extinct. Or, the
Arahat is that individual who experiences here and now the *extinction*
of these things. In him these can *never* arise again. He *experiences*
extinction. That is, he experiences __Nibbāna__.

_Nibbāna_ literally means extinction (or cessation). The word by itself
says nothing more. To the question "The extinction of what, is
__Nibbāna__?" many answers can be given. Some of the more important
answers would be that it is the extinction of subjectivity, or of
Suffering, or of the cankers, or of __tanhā__, or of Grasping. The
extinction of any one of these things implies *also* the extinction of
the others. When all subjectivity is extinct, all Suffering is also
extinct, Ignorance is also extinct, the cankers are also extinct, and so
on. It is therefore clear that _Nibbāna_ can be described in many ways,
and in discussion one would usually refer to it as the extinction of
that thing round which the discussion revolves. If one is discussing
__bhava__, then it would be appropriate to describe _Nibbāna_ as the
extinction or cessation of __bhava__: "The cessation of _bhava_ is
__Nibbāna__"footnote:[Anguttara Nikāya V. Dasaka Nipāta, Ānisaṃsa Vagga,
Sutta No. 7.] -- __bhavanirodho nibbānaṃ__. If one is discussing the
'person' (__sakkāya__) then it would be appropriate to say that Nibbīzna
is the cessation of the 'person' (__sakkāyanirodho__).footnote:[Saṃyutta
Nikāya III, Khandha Saṃyutta, Anta Vagga, Sutta No. 3.] If we reckon the
purpose of the Buddha's Teaching (which should at no time be lost sight
of) then we will describe _Nibbāna_ as the extinction of Suffering, or
as the cessation of Suffering, or as the destruction of Suffering.

_Nibbāna_ is often defined as "the destruction of lust, the destruction
of hatred, and the destruction of delusion."footnote:[Saṃyutta Nikāya
IV. Jambukhādaka Saṃyutta, Sutta No. 1.]

We saw earlier that Arahatship also has been defined by the Buddha as
"the destruction of lust, the destruction of hatred, and the destruction
of delusion." It means that the Arahat experiences all this
destructions. He experiences the extinction of lust, hatred and
delusion. Thus he experiences __Nibbāna__.

In the Saṁyutta Nikāya IV, there are 33 descriptive words given for the
Not-__Determined__ (__asaṅkhata__) or for the destruction of lust,
hatred and delusion. As terms for the destruction of lust, hatred and
delusion, they also become terms for Arahatship, and so for _Nibbāna_ as
well. In fact one term is _Nibbāna_ itself. It is well worth rapidly
going through these terms dwelling at some length on the more important
ones.

[[asaṅkhata---the-not-determined]]
(1) Asaṅkhata - The __Not__-Determined
++++++++++++++++++++++++++++++++++++++

We have seen its meaning earlier. It means Not-__Determined__. There is
no 'person' or subject ('I') determined. To the Arahat _only_ is
applicable the word 'impersonal' in its _fullest_ meaning.

[[antaṁ---the-end]]
(2) Antaṁ - The End
+++++++++++++++++++

Arahatship is the _summum bonum_ of all life's endeavour. It is the end.
All that had to be done has been done (__kataṃ karanīyaṁ__). There is
nothing more to come here from (__nāparaṁ itthattāyāti__). "For the
Arahat, friend, there is nothing further to be done."footnote:[Saṃyutta
Nikāya III, Khandha Saṃyutta, Dhammakathika Vagga, Sutta No.10.]

[[anāsavaṁ---the-without-cankers]]
(3) Anāsavaṁ - The Without Cankers
++++++++++++++++++++++++++++++++++

All the Cankers, viz., the cankers of sense-pleasure, of
'self'-existence, and of Ignorance are extinct in Arahatship.

[[saccaṁ---the-truth]]
(4) Saccaṁ - The Truth
++++++++++++++++++++++

The experience of Arahatship is the experience of the highest truth, or
of the highest actuality. "For this, monks, is the highest Ariyan
wisdom, that is to say the knowledge of the destruction of all
Suffering. That deliverance of his is founded on truth, is
unshakeable... For this, monks, is the highest Ariyan truth, that is to
say, __Nibbāna__, which is not a state unreal."footnote:[Majjhima Nikāya
140.]

[[pāraṁ---the-beyond]]
(5) Pāraṁ - The Beyond
++++++++++++++++++++++

Essentially it means that Arahatship is beyond all Suffering.

[[nipunaṁ---the-subtle]]
(6) Nipunaṁ - The Subtle
++++++++++++++++++++++++

The experience of the Arahat is not plain to common understanding. It is
deep, and cannot be comprehended through a process of mere conceptual
thinking. It is comprehensible only to the wise man, and that too if he
dwells upon it with Right Mindfulness (__sammā sati__).

_Nipunaṁ_ can also be taken to mean "accomplished" or "skilled".

[[saduddasaṁ---the-very-hard-to-see]]
(7) Saduddasaṁ - The Very Hard to See
+++++++++++++++++++++++++++++++++++++

What is so very hard to see is that the Arahat has intention but has no
thoughts of subjectivity, or that he has intention but no __tanhā__. His
intentional action is completely unaccompanied by any thoughts of 'I"
and 'mine'.

[[ajaraṁ---the-no-decay]]
(8) Ajaraṁ - The No-decay
+++++++++++++++++++++++++

We have already seen its meaning. The Arahat does not decay simply
because there is no 'person' or 'I" to decay. The changes that occur in
his body are not decay to him.

[[dhuvaṁ---the-stable]]
(9) Dhuvaṁ - The Stable
+++++++++++++++++++++++

Arahatship is _the_ stable simply because it is _the only_ state of life
that _does not_ and _cannot_ change its character or nature. For
instance, the Arahat can never go back to being a __puthujjana__.
Arahatship is irreversible.footnote:[It will be seen that the Buddha's
Teaching is aimed at altering one's thinking, and altering it to the
point where it can _never more_ be altered.]

[[apalokitaṁ---the-taken-leave-of]]
(10) Apalokitaṁ - The Taken Leave of
++++++++++++++++++++++++++++++++++++

The Arahat has "taken leave of" the world. "__My__ world" is extinct in
him. So long as he lives he experiences feelings, etc., but he is
neither attracted by them nor repelled by them.

[[anidassanaṁ---the-non-indicative]]
(11) Anidassanaṁ - The Non-Indicative
+++++++++++++++++++++++++++++++++++++

This is one of the most important descriptions of Arahatship, yet one
which is often misunderstood. _Anidassanaṁ_ is usually seen explained as
"invisible" or "cannot be seen with the eyes". Far from such,
_anidassanaṁ_ refers to something very important and equally difficult
to see.

Literally, _anidassanaṁ_ means "not pointing to" or "non-indicative".
What, however, does Arahatship not point to? Of what is it
non-indicative?

The answer is: a subject ('I').

The non-Arahat has Grasping Consciousness. That is to say, to the
non-Arahat, in varying degrees, things present themselves as 'mine'. And
as we have said earlier this presence of things as 'mine' points to an
'I' to whom they are present. A subject 'I' is thus indicated. With the
Arahat there is no presence of things as 'mine'. His Consciousness is
Not-Grasping (__anupādā__). No 'mine' being present, no 'I' is
indicated. The Arahat's Consciousness therefore does not point to or
indicate a subject 'I'. Thus his Consciousness is non-indicative
(__viññāṇaṁ anidassanaṁ__). That is why Arahatship is described as the
"Non-Indicative".

To the non-Arahat in varying degrees "things are mine". To the Arahat,
"things are". When the life of the Arahat ceases "things are" also
ceases. In other words: To the non-Arahat there is a 'my world'; to the
Arahat 'my world' has ceased, and there is only a 'world' left; when the
Arahat's life ceases the 'world' also ceases.

[[nippapaṁ---the-without-impediment]]
(12) Nippapaṁ - The Without Impediment
++++++++++++++++++++++++++++++++++++++

'I am' is called a __papañcitaṁ__.footnote:[Saṃyutta Nikāya IV,
Saḷāyatana Saṃyutta, Āsīvisa Vagga, Sutta No. 11.] 'I am' is also called
a _maññitaṁ_ (supposition), a _mānagataṁ_ (gone to
conceit).footnote:[Saṃyutta Nikāya IV, Saḷāyatana Saṃyutta, Āsīvisa
Vagga, Sutta No. 11.] _Papañca_ is sometimes taken to refer to
"diffuseness in thinking".footnote:[Anguttara Nikāya IV, Aṭṭhaka Nipāta,
Gahapati Vagga, Sutta No. 10.] From this it is clear that _papañca_
refers definitely to something that is a hindrance or impediment to
progress. The Arahat has cut out all such impediments
(__chinnapapañca__). Arahatship is therefore without impediment.

[[l3-santaṁ---the-peace]]
(l3) Santaṁ - The Peace
+++++++++++++++++++++++

In the _puthujjana_ there is no real peace, no real tranquility. So long
as thoughts of 'I' and 'mine' are present there _cannot_ be utter peace.
These being absent in the Arahat he is really and truly at peace.
Arahatship is the highest peace it is possible to experience.

[[amataṁ---the-deathless]]
(14) Amataṁ - The Deathless
+++++++++++++++++++++++++++

We have seen earlier what is meant by the Arahat being deathless. With
the Arahat there is no 'person' to die.

[[panītaṁ---the-excellent]]
(15) Panītaṁ - The Excellent
++++++++++++++++++++++++++++

Arahatship is the most excellent experience possible.

[[sivaṁ---the-fortunate]]
(16) Sivaṁ - The Fortunate
++++++++++++++++++++++++++

Arahatship is the most fortunate purely because there is no Suffering
whatsoever.

[[khemaṁ---the-security]]
(17) Khemaṁ - The Security
++++++++++++++++++++++++++

Arahatship is the experiencing of the highest security. It is the
highest form of security because there is no 'person' or 'I' to feel any
insecurity. The 'person' not existing, the experience is one that is
completely free from insecurity.

[[tanhakkhayo---the-desttuction-of-tanhā]]
(18) Tanhakkhayo - The Desttuction of tanhā
+++++++++++++++++++++++++++++++++++++++++++

The Arahat is free from all __tanhā__, of whatever kind it be.

[[acchariyaṁ---the-wonderful]]
(19) Acchariyaṁ - The Wonderful
+++++++++++++++++++++++++++++++

Arahatship is the truly wonderful experience.

[[abbhūtaṁ---the-astonishing]]
(20) Abbhūtaṁ - The Astonishing
+++++++++++++++++++++++++++++++

Arahatship is the truly astonishing experience.

[[anītikaṁ---the-freedom-from-harm]]
(21)Anītikaṁ - The Freedom from Harm
++++++++++++++++++++++++++++++++++++

With the Arahat there is no 'person' to be harmed. A painful feeling is
experienced just in the same unattached or unaffected manner as a
pleasant feeling would be.

[[anītikadhammaṁ---the-state-of-freedom-from-harm]]
(22) Anītikadhammaṁ - The State of Freedom from Harm
++++++++++++++++++++++++++++++++++++++++++++++++++++

Arahatship is an experience that is beyond being harmed. It is the state
of freedom from harm.

[[nibbānaṁ---extinction]]
(23) Nibbānaṁ - Extinction
++++++++++++++++++++++++++

This is a word with a very broad meaning, and in its meaning it includes
the extinction of all those that make for the _Grasping_ Groups. As we
shall presently see it is extended to cover the extinction of the
residual Not-Grasping Groups which happens when the life of the Arahat
comes to an end.

[[avyāpajjho---the-harmless]]
(24) Avyāpajjho - The Harmless
++++++++++++++++++++++++++++++

In Arahatship there is no ill-will, no thoughts of causing harm, etc.,
whatever.

[[virāgo---non-attachment]]
(25) Virāgo - Non-Attachment
++++++++++++++++++++++++++++

Arahatship is described as non-attachment purely because there is no
attachment of any kind whatever to things. With non-attachment there
also comes the corresponding characteristic of non-resistance or
non-repulsion. The Arahat is neither attracted by things nor repelled by
them.

[[suddhi---purity]]
(26) Suddhi - Purity
++++++++++++++++++++

In the true and worthy sense of the word, it is only Arahatship that can
be called Purity.

[[mutti--the-release]]
(27) Mutti- The Release
+++++++++++++++++++++++

Arahatship is the release from all Suffering.

[[anālayo---the-done-away-with]]
(28) Anālayo - The Done Away With
+++++++++++++++++++++++++++++++++

Usually in the context of done away with __tanhā__. The Arahat has
completely done away with _tanhā_ or any other thing that makes for
Suffering.

[[dīpaṁ---the-island]]
(29) Dīpaṁ - The Island
+++++++++++++++++++++++

Used in a metaphorical sense for safety - safety from all Suffering.
Arahatship is the island of safety.

[[o-lena---the-cave]]
(3O) Lena - The Cave
++++++++++++++++++++

Again used in a metaphorical sense. Arahatship is compared to a cave
which one gets into for safety from all harm, etc.

[[l-tānaṁ---the-shelter]]
(3l) Tānaṁ - The Shelter
++++++++++++++++++++++++

Once again used in a metaphorical sense. Arahatship is the shelter from
all harm, etc.

[[saranaṁ---the-refuge]]
(32) Saranaṁ - The Refuge
+++++++++++++++++++++++++

Arahatship is the only refuge from all Suffering. It is so because it is
only the Arahat who is completely free from all Suffering.

[[parāyanaṁ---the-ultimate-goal]]
(33) Parāyanaṁ - The Ultimate Goal
++++++++++++++++++++++++++++++++++

A goal beyond Arahatship there is not. All other 'goals' are nothing but
various states involving Suffering to _some_ degree or other. Arahatship
is wholly and entirely free from Suffering. Hence it is the ultimate
goal.

[[note-four-asterisk-mark-hierarchy-to-be-solved.]]
note: four asterisk mark: hierarchy to be solved.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Apart from the above thirty three descriptions other descriptions for
Arahatship are to be found, such as not-born (__ajātaṁ__), not-being
(__abhūtaṁ__) or not-made (__akataṁ__): "Monks, there is the not-born,
the not-being, the not-made, and the not-__determined__. If, monks,
there were not the not-born, the not-being, the not-made and the
not-__determined__, there would be discerned no escape here from the
born, the being, the made and the __determined__. But, monks, since
there is the not-born, the not-being, the not-made and the
not-determined, therefore an escape from the born, the being, the made,
and the _determined_ is discernible."footnote:[Udāna, Pāṭaligāmiya
Vagga, Sutta No. 3.] _Arahatship is referred to as not-born, not-being,
not-made and not-determined because with regard to the Arahat there is
no longer a 'person' (who says "I' and 'mine') that is born or being or
made or determined._

Another common description of Arahatship is the "ultimate happiness"
(__paramaṁ sukhaṁ__). This "ultimate happiness" is defined by the Buddha
as follows: "Were there a going beyond the sense-pleasures of the world,
that detachment is happiness. Were there a destruction of the conceit 'I
am', that indeed is the ultimate happiness."footnote:[Mahāvagga I,
Mucalinda Kathā.]

A description of Arahatship which would interest the ethicist is that
given in the __Pāsādika Sutta__footnote:[Dīgha Nikāya 29.] wherein the
Buddha in describing the Arahat says: "Friend, the monk in whom the
cankers are destroyed is incapable of deliberately depriving a living
being of life. The monk in whom the cankers are destroyed is incapable
of taking what is not given so that it constitutes theft. The monk in
whom the cankers are destroyed is incapable of indulging in sex
(__methunaṁ dhammaṁ__). The monk is whom the cankers are destroyed is
incapable of mindfully uttering falsehood. The monk in whom the cankers
are destroyed is incapable of laying up treasure for indulging in
pleasures as he did when being a house-holder. The monk in whom the
cankers are destroyed is incapable of taking a course of action through
desire. The monk in whom the cankers are destroyed is incapable of
taking a course of action through hatred. The monk in whom the cankers
are destroyed is incapable of taking a course of action through
delusion. The monk in whom the cankers are destroyed is incapable of
taking a course of action through fear. Friend, the monk who is Arahat,
in whom the cankers are destroyed, has done what was to be done, has
laid down the burden, attained the highest, completely destroyed the
fetter of __bhava__, released through right knowledge, is incapable of
these nine behaviours."

The Arahat is incapable (__abhabbo__) of doing these nine things. The
nature of Arahatship is such that it is _impossible_ for these things to
be done. The conditions that must be present if these things are to be
done are not present in the Arahat, nor can they ever arise in him
again.

Of all these descriptions of Arahatship the most common one, however, is
that it is the destruction of lust, hatred and delusion.

Now, Arahatship as we saw, is the experience of the extinction of
Grasping. The Five Grasping Groups are wholly and entirely extinct and
what remains is a Not-Grasping residual Five Groups. These residual Five
Groups are called the "Extinction element with residue" (__saupādisesa
nibbānadhātu__). It is the "stuff remaining". When Arahatship is over,
i.e., when the life of the Arahat is over, the "residue" is also over.
This is called "Extinction element without residue". (__anupādisesa
nibbānadhātu__). It is "without stuff remaining". In the three phases we
have, therefore, firstly Five Grasping Groups, secondly Five Groups, and
thirdly the extinction of the Five Groups. The first refers to the
non-Arahat, the second to the Arahat, and the third to the life-ending
of the Arahat.

____
"Monks, there are these two _Nibbāna_ elements. What two? . The
_Nibbāna_ element with residue and the _Nibbāna_ element without
residue.

"What, monks, is the _Nibbāna_ element with residue?

"Here, monks, a monk is Arahat, has destroyed the cankers, has lived the
life, done what was to be done, laid down the burden, attained the
highest goal, completely destroyed the fetter of __bhava__, released by
perfect knowledge. In him the five senses still remaining, these not
destroyed, he experiences pleasant and unpleasant things, feels ease and
pain. In him the destruction of lust, the destruction of hatred, and the
destruction of delusion is called the _Nibbāna_ element with residue.

"What, monks, is the _Nibbāna_ element without residue?

"Here, monks, a monk is Arahat ... released by perfect knowledge. But in
him, monks, here itself all that are sensed, not delighted in, will
become cool. This, monks, is called the Nibbāna element without
residue."footnote:[Itivuttaka 44.]
____

Often it is assumed that the descriptions of _Nibbāna_ such as not-born,
not-being, not-made and not-__determined__ are descriptions of the
_Nibbāna_ element without residue. This is a wrong assumption. Making
such a wrong assumption, it is lamented that the Nibbāna element without
residue is an incomprehensibility. But such a situation should not
arise.

There is nothing incomprehensible in the Buddha's Teaching, though the
Teaching is certainly difficult to __see__. The Not-__Determined__
(__asañkhata__) has been very clearly defined as Arahatship. And any
synonym for Not-__Determined__ must also be a descriptive word for
Arahatship or for the _Nibbāna_ element with residue.

Another _Sutta_ passage which describes the _Nibbāna_ element with
residue, but is usually taken to describe the _Nibbāna_ element without
residue, is as follows: "Monks, there is that sphere wherein is neither
earth nor water nor fire nor air, wherein is neither the sphere of
infinite space, nor of infinite consciousness, nor of nothingness, nor
of neither-perception-nor-non-perception, wherein is neither this world
nor a world beyond, nor both sun and moon. There, monks, there is no
coming, I declare; no going, no persisting,footnote:[As shown earlier,
_thitiṃ_ (persistence) is a characteristic of the __saṅkhata__, i.e. of
the Five Grasping Groups. It is not a characteristic of the _asaṅkhata_
which is Arahatship. Appearance (__uppādo__), disappearance (__vayo__),
and _thitiṃ_ (persistence) are applicable only to a 'person' or a 'self'
or a 'somebody'. With the Arahat the latter are extinct; hence
appearance, disappearance, and persistence are not applicable.] no
passing away, no arising. Without support without being, without
anything as object it is. This, indeed, is the end of
Suffering."footnote:[Udāna, Pāṭaligāmiya Vagga, Sutta No. 1.]

Here again it is Arahatship or the _Nibbāna_ element _with_ residue that
is being referred to. To get the full meaning of this passage, however,
one must understand what is meant by the Four Primary Modes - earth,
water, fire and air - "getting no footing".

In the __Kevaḍḍha Sutta__footnote:[Dīgha Nikāya 11.] we have Kevaḍḍha
asking the question: "Where do the Four Primary Modes - earth, water,
fire and air - cease without remainder?"

The Buddha points out to Kevaḍḍha that it is not a proper question, and
that the proper question should be: "Where do (the Modes) earth, water,
fire and air get no footing (__nagādhati__)? Where do long and short,
large and small, auspicious and inauspicious, and Name-and-Form cease
without remainder (__asesaṁ uparujjhati__)?"

It is necessary to see why Kevaḍḍha's question is not a proper question
before we can see the significance of the question that the Buddha
himself put in its place.

The Four Primary Modes (i.e. the four primary modes of behaviour)
_purely by themselves_ are not a matter for Consciousness. But their
_appearance_ is a matter for Consciousness, and their 'existence' is
_inferred_ through the behaviour of this __appearance__, i.e. through
the behaviour of Name (__nāma__). In other words, since Name behaves in
a certain fashion (e.g. while an object is perceived the percept behaves
in a certain fashion) we _infer_ that the object, or that the set of
behaviours, of which we are conscious behaves in that same fashion too.
This means that we are really _inferring_ that the Four Primary Modes
exist. Therefore, strictly speaking, we cannot say that the Four Primary
Modes __exist__. At the same time, since there is a behaviour of
appearance we cannot also say that they do _not_ exist. Further, if we
cannot say that they __exist__, we cannot also say that they __cease__.
Thus Kevaḍḍha's question is improper.footnote:[The impropriety of
Kevaḍḍha's question is fully within the scope of Science and the
Philosophy of Science. But the same does not apply to the question that
the Buddha put in its place and to its answer, the reason being that
Arahatship is beyond the scope of any Science or Philosophy.]

What we _can_ rightly say is that there is a behaviour of appearance - a
behaviour which is not motivated by the individual's Consciousness but
by something which he experiences as having _no_ connection with his
Consciousness. The appearance keeps behaving as he maintains his
awareness. What _does_ definitely exist for the individual is his being
conscious of something and the appearance of that something whilst he is
so conscious. Thus the Four Primary Modes get a _footing_ in this
existence. And it gets this footing as the __behaviour of appearance__.
In other words, we can only say that the Four Primary Modes _appear to
exist as rūpa_ (i.e. as Form or 'matter') in _nāma-rūpa_
(Name-and-Form).footnote:[The Buddha states that Form or 'matter' is
dependent on the Four Primary Modes. See page 20. This statement is
better understood at this stage.] Appearance gets a borrowed behaviour
and behaviour gets a borrowed appearance.

As against what is the case with the Four Primary Modes the concepts of
long and Short, large and small, auspicious and inauspicious are
_always_ a matter for Consciousness. They are actually a part of Name,
and therefore exist for so long as Consciousness exists only.

Now, for Name-and-Form to be there, Consciousness must be there. When
Consciousness ceases, Name-and-Form ceases. When Name-and-Form ceases,
the Four Primary Modes __lose their footing in existence__, and those
concepts like long and short, large and small, auspicious and
inauspicious __cease__. Therefore Kevaḍḍha's question should be as
formulated by the Buddha.

Further, we have seen that cessation has two aspects, firstly the
cessation of the Grasping, and secondly the cessation of the
Not-Grasping Residue. In the same manner "getting a footing" also has
two aspects.

With the Arahat, Grasping Consciousness has ceased. The Arahat's
Consciousness is Not-Grasping (__anupādā__). That means, nothing is
present to him as 'mine'. Now, 'mine' being absent, no 'I' is indicated
(__anidassanaṁ__). No 'I' being present, his Consciousness is "not
devoted" (__ananuruddha__)'footnote:[Majjhima Nikāya II and Saṃyutta
Nikāya IV, Saḷāyatana Saṃyutta, Saḷa Vagga, Sutta No. 1.] to anything
(or is "not engaged" with anything) as for example the __puthujjana__'s
Consciousness is when he experiences a pleasant feeling. On the other
hand it is "not in opposition" (__appaṭiviruddha__) to anything either,
as for example the __puthujjana__'s Consciousness is when he experiences
an unpleasant feeling. Therefore, with regard to the footing that the
Four Primary Modes get and with regard to those concepts like long and
short, large and small, auspicious and inauspicious, he is neither
devoted to them nor is in opposition to them. They bear no
_significance_ whatever to him as they do bear to the non-Arahat. Now,
the Arahat's Consciousness being neither devoted to anything nor in
opposition to anything, it is said to be ceased' (__niruddha__).
'Non-Indicative' Consciousness (which is the Arahat's Consciousness) is
therefore a Consciousness that is said to be 'ceased' (__viññānassa
nirodhena__). When Consciousness is said to be ceased, the Four Primary
Modes are said to get no footing in existence. Further, Name-and- Form
is also then said to be ceased, and therefore all concepts are also said
to be ceased.

_Viññāna nirodha_ - cessation of Consciousness - is used to refer to the
cessation of Grasping Consciousness (in which case it points to the
Arahat's Consciousness, i.e. to _anidassana vifīñāna_ - 'non-indicative'
Consciousness) as well as to the cessation of the Arahat's Consciousness
which occurs when the Arahat's life ceases.

To the extent that the Arahat has Consciousness, to that extent the Four
Primary Modes get a footing, and there is the presence of the concepts
of long and short, etc. But these have nothing whatever to do with
Grasping; and as a result the Arahat's Consciousness being neither
devoted to them nor obstructed by them, they bear no significance
whatever. When the Arahat's Consiousness ceases with the laying down of
life the Four Primary Modes get no footing whatsoever, and likewise the
concepts of long and short, large and small, auspicious and
inauspicious, and Name-and-Form cease without any remainder whatsoever.

Therefore the answer to the question is: "The non-indicative
Consciousness, the without end;footnote:[Anantaṃ (without end) should
probably be taken to mean "without aim" or "without objective".] the all
given upfootnote:[Pahaṃ, as a shortened form of pajahaṃ so as to
maintain the metre in the verse, and meaning "given up entire1y", fits
in here very much better than pabhaṃ.]- there it is where earth, water,
fire and air get no footing. There it is where long and short, large and
small, auspicious and inauspicious, and Name-and-Form cease without
remainder; with the ceasing of Consciousness, these cease."

The Arahat's Consciousness does not take anything as an object for
holding (__anārammanamevetaṁ__). The holding or the Grasping is over,
and so the subject ('I') is over. The subject ('I') being over, 'my
world' (__loko__) is over, a 'world beyond' is over; coming, going,
birth, death are all over; Suffering is over. "For him who clings there
is agitation. For him who clings not there is no agitation. Agitation
not being, there is calm. Calm being, there is no inclination.
Inclination not being, there is no coming, no going. Coming and going
not being, there is no decease-and-birth. Decease-and-birth not being,
there is no 'here' nor 'yonder' nor anything in between. This, indeed,
is the end of Suffering."footnote:[Udāna, Pāṭaligāmiya Vagga, Sutta No.
4.] Clearly this refers to Arahatship. "For him who clings not" means
"for the Arahat."

These passages from the _Udāna_ just quoted are misconstrued to refer to
the _Nibbāna_ element without residue only because attempts are made to
understand them __verbally__. If seeing and understanding the Buddha's
Teaching is only a matter of verbally understanding the __Sutta__, then
one can be an Arahat in next to no time. The _Nibbāna_ element without
residue is also seen described by meaningless words like 'Absolute',
'Unconditioned', and so on, only because of a lack of understanding,
which in turn is born of the attempt to understand the Teaching
verbally. Further, it is sometimes thought that the _Nibbāna_ element
without residue is some kind of metaphysical existence which has nothing
to do with the Five Groups, yet, that it is an eternal existence of some
sort or other. Such a view can arise owing to the presence of that very
subtle form of Grasping - "__Nibbāna__ is mine, he conceives"
(__nibbānaṁ meti maññati__) - which the Buddha refers to in his
Discourse on The Fundamentals 0f All Things.footnote:[Majjhima Nikāya
1.]

[[note-another-four-asterisk-mark-hierarchy-to-be-solved.]]
note: another four asterisk mark: hierarchy to be solved.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The Buddha Said: "All _determinations_ are Impermanent, all things are
Not-self, all _determinations_ are Suffering" (__sabbe saṅkhārā aniccā,
sabbe dhammā anattā, sabbe sankhārā dukkhā__). The following question
can arise here: whilst saying that all _things_ are Not-self, why did
the Buddha say that all _determinations_ are impermanent and Suffering?
In other words, whilst saying that all things are Not-self, why did he
say that _all things upon which other things depend_ are Impermanent and
Suffering? Why did he not _directly_ say all _things_ are Impermanent
and Suffering as he did with regard in the characteristic of Not-self?

The answer is that there is a distinct purpose in his Teaching. He does
not say things seeking others' approval of them. Nor does he set out to
_explain_ or _analyse_ things. He has just one intention underlying his
Teaching. That is, purely and simply, to lead the follower towards the
extinction of Suffering. And this extinction of Suffering is at one and
the same time the extinction of all notions of 'self' and of all
thoughts of 'I' and 'mine'. The purpose of the Teaching is not to save
'self' but to be saved _from_ 'self'.

Thus the Buddha does not take one directly towards a thing's
impermanence. He takes one towards it in an indirect manner, and that is
more effective. He shows that a thing is impermanent by showing that the
things upon which that thing depends are impermanent. Then, since the
thing is impermanent, he shows that it is Not-self.

It should therefore be clear that this triad - 'All _determinations_ are
Impermanent, all things are Not-self, all _determinations_ are
Suffering" - is not an exposition of things pure and simple. It includes
a definite _way_ of teaching.

This fact is lost sight of, and then in a conceptual manner various
reasons are adduced for its particular form. The most common of these
reasons appears to be that in this triad the word 'thing' (__dhamma__),
unlike the word '__determinations__' (__saṅkhāra__), includes _Nibbāna_
also. In other words it is often thought that the reason for the Buddha
saying "all _determinations_ are Impermanent, all things are Not-self"
without saying "all things are ' Impermanent, all things are Not-self"
is that he wanted _Nibbāna_ too to be included as something Not-self.

But this is a wrong notion, and it is arrived at in the following
manner:

To begin with, the word _saṅkhāra_ is taken to mean "__determined__".
That is, it is taken to be the same as __saṅkhata__. This, as we have
seen, is wrong. _Sankhāra_ means something which _determines_ some other
thing, i.e., a __determination__, or a _determinant_ Now, _Nibbāna_ has
been described as the Not-__Determined__, i.e., as __asaṅkhata__. On the
face of this description of _Nibbāna_ it cannot be included in the word
_saṅkhāra_ which is now wrongly taken to be the same as __saṅkhata__.
Therefore a word which embraces both _saṅkhata_ and _asaṅkhata_ has to
be found. That would be _dhamma_ (thing). Since the Buddha wanted
_Nibbāna_ also to be described as Not-self the word _dhamma_ was used.

Such is the wrong argument through which this wrong notion is arrived
at.

But the _Nibbāna_ element, with or without residue, has _nothing
whatever_ to do with 'self' _or_ Not-self. In _Nibbāna_ there is no
deception of a 'self' whatever, which means that there is no such 'self'
__to be denied__. There is no necessity whatever for Not- self. The
question of Not-self arises only when the question of 'self' arises.
_Nibbāna_ is beyond both 'self' and Not-self. The Arahat has no notion
whatever of 'Self'. Hence the Arahat has no occasion whatever to see
anything as Not-self. Seeing things as Not-self is only the _path_ to
Purityfootnote:[Purity refers to Arahatship. See page 101.] (or to
__Nibbāna__). It is _not_ Purity. "All things are Not-self. When this is
seen with wisdom, one wearies oneself of Suffering. This is the path to
Purity."[]^path] The Arahat _has arrived_ at Purity and lives in Purity.
He has come to the end of 'Not, this is my self'.

With the Five Grasping Groups there is a deception of a 'self'.
Something appears as 'self'. But this thing which appears as 'self' is
really not a self. That is to say, it is Not-self. The 'self' of the
Five Grasping Groups is _not_ a self, since no self of any kind whatever
is to be found at all anywhere. Therefore this 'self' has to be seen as
Not-self.

With the residual Not-Grasping Groups of the Arahat there is no apparent
'self' to be found. There _nothing_ appears as 'self'. Hence no seeing
anything as Not-self arises.

Again: Though no self actually is to be found, things are being seen as
'self' or Not-self. And seeing things as 'self' precedes seeing things
as Not-self. The Arahat has come to the end of all seeings. And in
__Nibbāna__, which is the experience of the Arahat, there is no question
of a seeing things as Not-Self, since there is no question of a 'self'
arising at all.

Perhaps an analogy would help to make this matter clearer. Let us
imagine two deer gazing at the sun shining upon the sand. One of them is
an ordinary deer, and being ordinary it sees 'water' as it gazes at the
said phenomenon. To this deer there is the problem of 'water'. It has to
be told that what it is taking for 'water' is not-water, and that it is
merely the sun shining upon the sand. Now let us imagine that the second
deer has perfect understanding and clear penetrative vision. To this
deer, its vision being so perfect, no 'water' appears at all. It also
understands fully well that it is gazing at the sun shining upon the
sand. To this deer there is nothing to be taken as 'water' or as
not-water. Suppose we now tell this clear visioned deer that the
phenomenon it is gazing at is not-water, it will look at us and say,
"What on earth are you speaking about?"

The confusion seems to lie in assuming that when the Buddha says some
_dhamma_ is __anattā__, what the Buddha purely and simply means by it is
that _in_ that _dhamma_ there is no __attā__. Such an assumption is a
very grave lapse, seriously misleading, and missing the vital point. (To
indicate that there is no permanent self-existent thing anywhere, a
Buddha is not necessary. A Hume would do for that. Let alone _in_ the
Arahat, even _in_ the _puthujjana_ there is no actual self.) This type
of assumption will only lead us to the conclusion that, with regard to
the problem of 'self', there is really no difference between the Arahat
and the __puthujjana__. So that it will not lead us anywhere; since the
real culprit - that is, the _deception_ of 'self' (which is there for
the __puthujjana__, but not there for the Arahat) - has been beautifully
allowed to escape notice, and so will continue to remain as strong as it
ever was. This is precisely what happens with the individual who thinks
that when the Buddha says some _dhamma_ is __anattā__, all that is meant
by it is that _in_ the _dhamma_ there is no __attā__. He further seeks
confirmation of this verbal understanding by analysing the Five Groups
into infinitesimal bits and pieces with the lofty equanimity of the
scholar, and to his great satisfaction (since his verbal understanding
is being confirmed) he sees no actual self anywhere. In fact he could
well spare himself the trouble of such fine analysis and yet see that
there is no self to be found anywhere. But - and that is the vital point
- in spite of all his masterly analysis, he still __looks upon the Five
Grasping Groups as 'self'__; more precisely, as 'my self'.

In this triad - _sabbe saṅkhārā aniccā, sabbe dhammā anattā, sabbe
sankhārā dukkhā_ - the meaning of _sabbe dhammā anattā_ is: All things
(which are taken as 'self') are Not-self. Thus it does not apply to
Arahatship or __Nibbāna__.

As we have said earlier the Buddha is teaching with a definite purpose.
He does not have to help us remove a self that actually does not exist.
He is helping us to remove the _notion_ of 'self' that exists with us.
And he, and _only_ he, can help us to remove this notion. His Teaching
is one that is designed to lead on towards a specific goal. That is also
why he says that the _saṅkhārā_ are __aniccā__, without directly saying
that the dhamma (which are __saṅkhatā__. and dependent on __saṅkhārā__)
are __aniccā__. Further, his Teaching is also one that is 'well said'
(__svākhāto__). But it is also necessary that we understand it
well.[multiblock footnote omitted]

"What is impermanent, that is Suffering; what is Suffering, that is
Not-self" (__yad aniccaṁ taṁ dukkhaṁ, yaṁ dukkaṁ tad
anattā__).footnote:[Saṃyutta Nikāya III, Khandha Saṃyutta, Anicca Vagga,
Sutta No. 4.] Here again, the Buddha is showing the person who is seeing
things as 'self' how and why those things are Not-self. Wherever a
'self' is asserted the Buddha rejects it, and shows that there is no
basis to consider anything as a self. He does not have to do that with
the Arahat. These three characteristics of Impermanence, Not-self and
Suffering always stand or fall together. __Nibbāna__, with or without
residue, is _beyond_ all these three characteristics.
