[[ch-10-birth-decay-and-death]]
= 10. Birth, Decay and Death

Prince Siddharta left his palace for no other reason than to find the
solution to the problem of birth, decay and death, to determine whether
he could get beyond these phenomena. All these were nothing but
Suffering. And as Gotama the Buddha he claimed he had won the not-born,
the not-decaying and the not-dying.

[quote, role=quote]
____
"So I, monks, being liable to birth because of 'self' (__attanā__),
having known the peril in what is liable to birth, seeking the non-born,
the uttermost security from the bonds -- Nibbāna -- won the not-born,
the uttermost security from the bonds -- Nibbāna. Being liable to
decay because of 'self' ... won the not-decaying, the uttermost security
from the bonds -- Nibbāna. Being liable to disease because of 'self'
... won the not-diseasing, the uttermost security from the bonds --
Nibbāna. Being liable to death because of 'self' ... won the
not-dying, the uttermost security from the bonds - Nibbāna. Being
liable to sorrow because of 'self' ... won the not-sorrowing, the
uttermost security from the bonds - Nibbāna. Being liable to stain
because of 'self' ... won the stainless, the uttermost security from the
bonds - Nibbāna. Knowledge and vision arose in me: 'Unshakeable is
my Deliverance; this is the end of birth; there is no _bhava_ again now.'"

-- https://suttacentral.net/mn26/en/bodhi[MN 26], The Noble Search
____

But the _puthujjana_ sees the Buddha 'decaying' and 'dying' in the same
manner he sees others. Nevertheless the Buddha claimed he had arrived at
and experiences the not-decaying and the not-dying. And the Buddha was
the first individual in the world who made this claim. Subsequently, of
course, those who followed his instructions to the very end and became
Arahats, also made the same claim.

How are we to understand this?

The understanding of this must obviously lie in the understanding of the
phenomenon of birth, decay and death.

The definition of birth, decay and death given by the Buddha himself is
as follows:

[quote, role=quote]
____
"And what monks, is birth?"

"That which, of this and that *being* in this and that group of
**beings**, is birth, production, descent, arising coming forth, the
appearance of the Groups, acquiring of the sense-bases -- this is called
birth."

"And what, monks is decay and death?"

"That which, of this and that being in this and that group of beings, is
decay, decrepitude, breaking up, hoariness, wrinkling of the skin,
shrinkage of life-span, over-ripeness of faculties -- this is called
decay. That which, of this and that being in this and that group of
beings, is falling, separation, breaking up, disappearance, mortality,
death, completion of time, breaking up of the Groups, laying down of the
body, cutting off of the living senses -- this is called death. Thus it
is, this decay and this dying that is called decay and death."

-- https://suttacentral.net/sn12.2/en/bodhi[SN 12.2], Analysis of Dependent Origination
____

Now, birth, decay and death in the above are referred to in relation to
'beings'. The Pali word is __satta__. _Satta_ (being) is defined for us
as follows:

[quote, role=quote]
____
"'Being! being! (__satta__)' it is said. To what extent, Lord, is one
called a being?"

"That desire, Radha, that attachment, that de1ight, that _taṇhā_ which
is concerned with Form ... Feeling ... Perception ... Determinations ...
Consciousness -- entangled thereby, fast entangled thereby, *therefore* is
one called a 'being'."

-- https://suttacentral.net/sn23.2/en/sujato[SN 23.2], Sentient Beings
____

Very clearly, _satta_ (being) refers to the Five _Grasping_ Groups. For,
as we have seen earlier, desire, attachment, delight and _taṇhā_ are
present only in the Grasping Groups.

Thus, birth (__jāti__) means **birth of the Grasping Groups**. Decay
(__jarā__) means **decay of the Grasping Groups**. Death (__marana__)
means **death of the Grasping Groups**. Just as much as _bhava_ means
the **existence of the Grasping Groups**. Fundamentally, then: Birth
means birth of 'self' and the birth of 'I' and 'mine'; decay means decay
of 'self' and the decay of 'I' and 'mine'; and death means death of
'self' and the death of 'I' and 'mine'.

In the Pali passage, the translation of which has been quoted at the
beginning of this chapter, _attanā_ is a key word. The Buddha says here
that before attaining Buddhahood he was subject to birth, decay and
death *because of 'self'* (__attanā__). If this word is lost sight of
the entire point is missed.

Apart from the Buddha and the Arahats, every other living being has
thoughts of 'self' and of 'I' and 'mine' to some degree or other. To the
_puthujjana_ his existence is just a matter of existence of 'self', a
matter of '**I** exist' or '**my** existence'. That is, it is just a
matter of __bhava__. To him there is only a birth of 'self', of a
'person' or 'somebody' who says: 'This is mine; this am I; this is my
self'. So is it with decay and death. Where there are no thoughts of 'I'
and 'mine' whatever, no thoughts or feelings of subjectivity, no
__bhava__, the question of birth, decay and death does not arise. For,
there is no 'person', no 'I' who is born or decays or dies. Thoughts
such as 'I was in the past', or 'I am in the present', or 'I will be in
the future' are all over. So also are the thoughts 'I was born' or 'will
I be born again' or 'I am decaying' or 'I will decay' or 'I will die'.

Now, the _puthujjana_ neither *experiences* his birth nor even
recollects it. He has also no experience of his death. But the Buddha
says that birth is Suffering and death is Suffering. If however, the
_puthujjana_ does not experience his own birth and death, what 'birth'
and 'death' does he then *experience* as a Suffering? What is this
'birth' that *is* a Suffering to him? Likewise, what is this 'death'
that is a Suffering to him?

The answer is:

The _puthujjana_ sees *others* being born and dying. For him this is a
matter of **immediate seeing**. So he comes to the conclusion that he
also was born and that he also will die. He thinks 'I was born' and 'I
will die'. This is all that birth and death mean to him during his
conscious existence. It is this *thinking* of his own birth and death
that is a *present* Suffering, and not the actual events of his birth
and death. This thinking of his own past birth and his own future death
goes on right through his life, forming a part of the mass of Suffering
that exists for him.

[quote, role=quote]
____
"Things have mind as forerunner, mind as chief, are mind made."

__manopubbaṅgamā dhammā manoseṭṭhā manomayā__.footnote:[This verse in the _Dhammapada_
embraces in its orbit a far wider range than it is generally reckoned
to. Quite understandably it has been given first precedence in this
collection of verses in as much as the _Mūlapariyāya Sutta_ has been
given first precedence in the collection of medium length discourses
called the __Majjhima Nikāya__.]

-- https://suttacentral.net/dhp1-20/en/anandajoti[Dhp 1]
____

What drove Prince Siddharta out of his
palace at the age of twenty-nine was not the actual event of his birth
or of a death, but the *thought* of his past birth and a death to come.

__Jāti__, it must be noted, is *not* rebirth. In the Pali, rebirth is
__punabbavābhinibbatti__, which means, **the coming to be of a renewed
bhava.**footnote:[For example: _katam panāvuso āyatim
punabbhavābhinibbatti_ -- "How, friend, is there the coming to be of a
renewed __bhava__? (https://suttacentral.net/mn43/en/sujato[MN 43]). In the following Sutta
passage both _jāti_ and _punabbhavābhinibbatti_ appear: _āyatim
punabhhavābhinibbattiyā sati āyatiṁ jāti jarāmaranaṁ sokaparideve dukkha
domanassupāyāsā sambhavanti_ -- "There being in the future a coming to
be of a renewed __bhava__, there is in the future birth, decay, death,
sorrow, grief, suffering, lamentation and woe produced" (https://suttacentral.net/sn12.38/en/bodhi[SN 12.38]).]

Another form of _bhava_ springs up. This new springing up in the future is
re-birth. And if one is free from birth (as the Arahat is), then one is
also free from any possibility of rebirth. "He having realised the
destruction of birth does not come to rebirth." (https://suttacentral.net/iti104/en/sujato[Iti 104])

As the body with all its sense organs changes from youth to old age, it
is to the _puthujjana_ that this change is **decay**. 'Decay' is the
concept that the _puthujjana_ has regarding a change in his body which
he considers as '**my** body'. How does he form this concept? To him the
body is a means by which he satisfies his __taṇhā__, i.e. his wanting
'my existence' and sense-pleasures. This is the significance his body
has to him. When the body has changed to what he calls old, it no longer
permits him to enjoy the same satisfaction of his __taṇhā__, which
_taṇhā_ still remains in him as strong as ever. Thus the body is now not
as *desirable* as it was. He laments and grieves at it. And he considers
it as having decayed. But the Arahat has no trace of _taṇhā_ whatever.
In him there is no wanting 'my existence' or sense-pleasures whatever.
Thus, to the Arahat, the body does not have the same significance as it
has to the __puthujjana__. To the Arahat it is just body and no more.
Not having __taṇhā__, when the body grows old he does not lament or
grieve at it. It is not decay to him. The body has just changed, and
that is all. There is no 'I' or a 'my this' or a 'my that' to
decay.footnote:[A change in the body is considered or conceived of as a
change for the better or for the worse *only if* it is considered as a
change in '**my** body'. The same applies to Feeling, Perception,
Determinations and Consciousness. It is very important that this is seen.]

[quote, ]
____
* "'I am' -- monk, this is a supposition (__maññitaṁ__).
* 'This am I' -- this is a supposition.
* 'I will exist' -- this is a supposition.
* 'I will not exist' -- this is a supposition.
* 'I will be possessed of Form' ...
* 'I will be possessed of not-Form' ...
* 'I will be possessed of Perception' ...
* 'I will be possessed of non-Perception' ...
* 'I will be possessed of neither Perception nor non-Perception' -- this is a supposition.

A supposition, monk, is a disease; a supposition is an
imposthume; a supposition is a barb. Monk, when he has gone beyond all
suppositions, the sage is said to be at peace. But, monk, a sage who is
at peace is not born, does not decay, is not agitated, does not envy.
**As there stands nothing of which can be said 'was born'**, not being
so born, how, monk, could he decay (__tam pi'ssa bhikkhu na'tthi yena
jāyetha, ajāyamāno kiṁ jiyyissati__)? Not decaying, how could he die?
Not dying how could he be agitated? Not being agitated, how could he envy?"

-- https://suttacentral.net/mn140/en/bodhi[MN 140], The Exposition of the Elements
____

That of which can be said 'was born' is 'self' or 'I'. But the Arahat is
completely free from 'self' and 'I'. He has no thoughts of 'self or of
'I' and 'mine' whatever. Therefore he has no thoughts of a 'was born' or
a 'decaying' or a 'will decay' or a 'will die'. With him there is no
'self' or 'I' to which *only* these things apply.footnote:[It is not impossible
to use the words `'decay'` and `'death'` for the Arahat
provided the implications are very clearly kept in mind. The change that happens
to the body of the non-Arahat is the same as that which happens to the body of
the Arahat. In the former case it is a decay, and this implies that the change
is unwelcome and is a Suffering. But in the latter case the change is not
unwelcome (in fact, it is neither welcome nor unwelcome) and is not a Suffering.
If in this latter case we call the change `'decay'`, then we will have to use
the word *purely* as a *designation* for the change but having no other
significance whatsoever. The same applies to the use of the word `'death'`.
Ordinary usage of the words `'decay'` and `'death'`, however, always imply
definite significances such as unwelcome-ness and Suffering. These significances
being wholly and entirely absent for the Arahat, the change that goes on in the
Arahat's body is not called decay and the laying down of life in the Arahat is
not called death. The Arahat is decayless and deathless.]

All this is of course easily **stated**, though not at all easy to
**see**. But the Buddha's Teaching *is* not easy to see. In fact, it is
a very difficult Teaching to See.

In the __Upasena Sutta__ we have the case of a serpent
having fallen on the body of Arahat Upasena. Upasena then requests the
monks to lift his body on to a couch and take it outside so that it may
break upfootnote:[The body 'breaking up' refers to life ending.] there.
Arahat Upasena was then told that no change for the worse in his
faculties necessitating such action was evident. The reply the Arahat
gave is very illuminating. He said:

[quote, role=quote]
____
"Friend Sāriputta, he who should think 'I am the eye', 'the eye is
mine', or 'I am the tongue', 'the tongue is mine', or 'I am the mind',
'the mind is mine' -- in him there would be an otherwise-ness in his
body, there would be a change for the worse (__viparināmo__) in his
faculties. But in me, friend Sāriputta, there are no such thoughts as 'I
am the eye', 'the eye is mine', or 'I am the tongue', 'the tongue is
mine', or 'I am the mind', 'the mind is mine'. How then, friend
Sāriputta, could there be to me the existence of an otherwise-ness in
the body, or a change for the worse in the faculties?"

-- https://suttacentral.net/sn35.69/en/sujato[SN 35.69], Upasena and the Viper
____

So the monks put the Venerable Upasena's body on a couch and bore it
outside, and the body broke up then and there.

In the Sutta passage, the translation of which has been just given, we
get the word __viparināmo__. The literal meaning of this word is
"transformation". To the non-Arahat this transformation is either a
"change for the better" or a "change for the worse". But to the Arahat
there is no such thing. For him there is purely and simply a change
which bears *no* significance of either being for the better or for the
worse. This is the basic meaning of Arahat Upasena's reply.

The Buddha did not say that he *will* be experiencing deathlessness
after his life is over and the body broken up. He said that he, likewise
the Arahats, *live experiencing* deathlessness. Exhorting the five monks
at Benares (whom he first taught) to listen to him, he described himself
thus:

[quote, role=quote]
____
"The Tathāgata, monks, is Arahat, is All Enlightened. Give ear,
monks. Deathlessness has been reached (__amatamadhigataṁ__). I will
intruct you."

-- https://suttacentral.net/pli-tv-kd1/en/brahmali[Vin I. 5-8], Mahāvagga
____

_Amatamadhigataṁ_ means "**gone** to deathlessness" and *not* "going to
deathlessness." It is something that *has happened* or *has been achieved*
"Having attained it and realised it" (__sacchikatvā upasampajja__) the Arahat
"lives experiencing it in the body" (__kāyena ca phusitvā viharati__).

The Arahat has come to the cessation of birth, decay and death. He is
"entirely freed from birth, decay and death" -- __parimutto jātiyā jarā
maranena__. (https://suttacentral.net/an3.38/en/bodhi[AN 3.38])

He "has done away with birth and death" -- __pahīnajātimarano__. (https://suttacentral.net/an3.57/en/bodhi[AN 3.57])

He "has gone beyond birth and death" -- __jāti marana maccagā__. (https://suttacentral.net/iti77/en/sujato[Iti 77])

He is one who "has arrived at the destruction of birth" --
__jātikkhayaṁ patto__. (https://suttacentral.net/iti99/en/sujato[Iti 99])

He "has conquered death" -- __maranābhibhū__. (https://suttacentral.net/thag20.1/en/sujato[Thag 1180])

To him applies: "Calm and unclouded, peaceful, freed of longing, he hath crossed
over birth and decay, I say" -- __santo vidhūmo anīgho nirāso atāri so
jātijaranti brūmī'ti__. (https://suttacentral.net/an3.32/en/bodhi[AN 3.32])

When Ānanda attained at Arahatship he said of himself, "Gone to the end of birth
and death he bears the final frame" -- __dhāreti antimaṁ dehaṁ
jātimaranapāragu__. (https://suttacentral.net/thag17.3/en/sujato[Thag 1022])

Again, the Buddha is the first human being in the world who overcame
death, though the greatest thinkers in the world have wondered how it
could ever be done. And the Buddha did not overcome death in the fashion
that everybody would imagine it should be done. That is by living for
ever. He did it by *removing* that to which death **applies**. The
experience of the living Arahat is birthless, decayless and deathless,
because all subjectivity (i.e. everything that is to do with 'self' and
'I' and 'mine') to which alone birth, decay and death are applicable,
has been completely cut off never to arise again.

After all this subjectivity has been made extinct there yet remains life
for a while longer, which is the life of the Arahat. This the Buddha
describes as 'stuff remaining' (__upādisesa__). This too comes to an end
when the Arahat's life span is over and the body breaks up. But the
ending of the Arahat's life is not to be called 'death'. About
_upādisesa_ we shall speak more later.

With anybody other than an Arahat questions pertaining to 'after death'
(__parammaranā__) are relevant. What happens to the being (__satta__)
when the body breaks up after death (__kāyassa bhedā parammaranā__) is a
relevant question. But such a question is not relevant to the Arahat.
With the Arahat there is no question of death, hence no question of
after death. For the Arahat there is only a breaking up of the body
(__kāyassa bhedā__) which happens with the Arahat's life coming to an
end (__jīvita pariyādānā__). That is all. As we have said earlier, with
the Arahat there is no 'person' existing. There is only a certain
experience going on.

Does the Tathagata exist after death? Does the Tathagata not exist after
death? Does the Tathagata both exist and not exist after death? Does the
Tathagata neither exist nor not exist after death?

The Buddha does not give replies to these questions either in the
affirmative or in the negative. For this reason it must not be thought
that there is something very mysterious about them or that there is
something unrevealed by the Buddha here. He teaches that these questions
*do not apply* (__na upeti__). Why so? Because, in relation to the
Buddha, there is *no* 'person' or 'being' or 'somebody' who says 'I' and
'mine' existing *to whom* they can apply. Thus there is no death
applicable to the Buddha. Hence questions pertaining to 'after death' do
not apply.

The Buddha on one occasion so admonished Vacchagotta when the latter
asked these questions. Vacchagotta then proclaimed that he was at a loss
on this point, that he was bewildered, and what is more, that that
measure of satisfaction he had had from former conversation with the
Buddha -- even that he had now lost! At which the Buddha informed
Vacchagotta that he *ought* to be at a loss, that he *ought* to be
bewildered, which only means that the uninstructed _puthujjana_ *ought*
to be at a loss in understanding the Buddha's Teaching.

[quote, role=quote]
____
"You ought to be at a loss, Vaccha, you ought to be bewildered. For,
Vaccha, this Dhamma is deep, difficult to see, difficult to understand,
peaceful, excellent, beyond dialectic, subtle, intelligible to the wise."

-- https://suttacentral.net/mn72/en/thanissaro[MN 72], To Vacchagotta on Fire
____

This particular Discourse to Vacchagotta is well worth a careful study.
The burning flame that is brought in as a simile is to denote the
'person' (__sakkāya__). Just as the flame burns and exists by taking up
dried leaves and sticks (__tiṇakaṭṭhupādānaṁ__), so does the 'person'
exist by Grasping. And just as the flame will become extinct
(__nibbāyeyya__) when there is no more taking up of dried leaves and
sticks, so does the 'person' become extinct when the Grasping ceases.
What would remain is that which we referred to as the 'stuff remaining'
and designated as Arahat. In as much as there is now no flame to go
east, west, north, south or anywhere else, with regard to the Arahat
there is no 'person' to die, and hence no 'person' to arise after death.

The _puthujjana_ looks upon the Arahat as he would look upon himself.
That is as a __sakkāya__, a 'self', a 'person' who says 'I' and 'mine'.
Thus viewing he puts these questions. The _puthujjana_ being a Five
*Grasping* Groups (which essentially means having thoughts of
subjectivity, of 'I' and 'mine') thinks that the Arahat is also a Five
*Grasping* Groups. He does not know that *all* Grasping is extinct in
the Arahat, that the Arahat "has laid down all Grasping" --
__sabbupādānapariyādāna__, (https://suttacentral.net/sn35.62/en/bodhi[SN 35.62]) that the Arahat "has destroyed
all Grasping" -- __sabbupādānakkhayaṁ__. (https://suttacentral.net/ud3.10/en/anandajoti[Uda 3.10])
He does not see that the Arahat "by the destruction,
dispassion, cessation, giving up, casting out all suppositions, all
standpoints, all latent conceits of 'I' and 'mine', is freed without
Grasping". (https://suttacentral.net/mn72/en/thanissaro[MN 72])

When the Arahat is asked questions about himself on the basis of things not
applicable to him, what other reply can he give than saying that those questions
about him do not apply to him?

[quote, role=quote]
____
"Even so, great king,

* *that* Form ...
* *that* Feeling ...
* *that* Perception ...
* *those* Determinations ...
* *that* Consciousness

by which one discerning the Tathagata might discern him --

* *that* Form ...
* *that* Feeling ...
* *that* Perception ...
* *those* Determinations ...
* *that* Consciousness

has been got rid of, cut off at the root, made like a
palm-tree stump that can come to no further existence and is not liable
to rise again in the future. Freed from reckoning as Consciousness is
the Tathagata, great king. He is deep, immeasurable, unfathomable as is
the great ocean. To say, 'The Tathagata exists after death', does not
app1y. To say, 'The Tathagata does not exist after death', does not
apply. To say, 'The Tathagata does exist and does not exist after
death', does not apply. To say, 'The Tathagata neither exists nor does
not exist after death', does not apply".

-- https://suttacentral.net/sn44.1/en/bodhi[SN 44.1], Khema
____

The Groups of Form, Feeling, Perception, Determinations and
Consciousness which have been cut off at the root never to arise again
are the *Grasping* Groups of Form, Feeling, Perception.

Determinations and Consciousness. And birth, decay and death apply only
to the Grasping Groups, because an 'I' or a 'self', to which only birth,
decay and death are applicable, is present only if there is Grasping.
When Grasping is extinct, all such subjectivity is extinct. What then
remains is a residual *Not-Grasping* Five Groups to which birth, decay
and death do not apply. "This is deathlessness, that is to say, the
deliverance of the mind from Grasping" -- __etaṁ amataṁ yadidaṁ anupādā
cittassa vimokkho__. (https://suttacentral.net/mn106/en/sujato[MN 106])

[quote, role=quote]
____
The King Pasenadi asks the Buddha, "To the born is there any other than
decay and death?" To which the Buddha replies, "To the born, great king,
there is none other than decay and death.

"Great king, were there eminent
nobles, prosperous, owning great treasure, great wealth, large hoards of
gold and silver, immense means, abundant supplies of goods and corn --
to them who are born there is none other than decay and death.

"Great king, were there eminent brahmins ...

"Great king, were there eminent
householders, prosperous, owning great treasure, great wealth, large
hoards of gold and silver, immense means, abundant supplies of goods and
corn -- to them who are born there is none other than decay and death.

"Great king, were there monks who are Arahat, have destroyed the cankers,
have finished, done what was to be done, laid down the burden, won the
highest good, completely destroyed the fetter of __bhava__, freed by
right insight -- to them there is a breaking up of the body, a laying
down of it."

-- https://suttacentral.net/sn3.3/en/sujato[SN 3.3], Old Age and Death
____

In the above reply the Buddha teaches that birth, decay and death are
applicable to the nobles, brahmins, etc. But when it comes to the
Arahat, birth, decay and death do not apply.

If the point that has been discussed in this chapter is missed the
uniqueness of the Buddha's Teaching is also missed. The Buddha's
Teaching is to be experienced here and now, in this life -- all of it,
from beginning to end. Decaylessness and deathlessness are also to be
experienced here and now.
