[[ch-15-rebirth]]
= 15. Rebirth

A discussion on rebirth is usually a discussion on a subject concerning
which there is no personal experience among those who discuss it. Also,
for the task of seeking a solution to the _present_ problem of Suffering
in the _present_ itself, a study of rebirth is not essential. For these
reasons this chapter will not be a discussion on the subject of rebirth
proper. Nevertheless there are a couple of matters regarding rebirth
which are worth of thought. This chapter will therefore limit itself to
a discussion of those matters.

However much one may argue and infer that it is only through the
Buddha's doctrine of rebirth that the variegated inequalities of human
beings could be accounted for, there yet remains a certain amount of
doubt about it until one _sees_ rebirth. Until then, to some extent or
other, one has trust in the Buddha with regard to the matter.

On the other hand the Buddha demands no belief in rebirth from one whose
sole aim is to end Suffering, nor does he insist that one must see
rebirth if one is to come to the end of Suffering. As we pointed out
earlier, the _Suttas_ speak of Arahats who saw rebirth and could
recollect past lives as well as of those who could __not__.footnote:[For example: https://suttacentral.net/sn16.9/en/bodhi[SN 16.9: Jhanas and Direct Knowledges]]
Certainly belief in rebirth would be very useful in that it would act as an urge
to reach the Path as fast and as diligently as possible, and so get to
_Ariyabhumi_ (plane of the __Ariyas__) at least, in this life. But it is
not absolutely essential.footnote:[It is sometimes thought that the most effective way of convincing one of the validity of the Buddha's Teaching is to prove to one that there is rebirth. This is not so. We find that even ascetics who could see rebirth and could recollect their past lives did not always accept the Buddha's Teaching In fact, their very seeing rebirth and recollecting past lives made them come to wrong View. For example, see [https://suttacentral.net/dn1[DN 1]].
pass:[<br><br>]
Far too much time seems to be spent on the subject of rebirth by those interested in the Buddha's Teaching. If this time is spent by them in trying to see here and now itself a solution to the problem of their present existence, they are bound to be benefited much more, and in fact will also be attracted towards the Buddha's Teaching much more.]

The present problem of my existence, which is just the problem of my
_present_ Suffering, is to be solved _here_ and _now_ with no reference
to a past life or a future life. Whether there will be or whether there
will not be a renewed existence (__punabbhava__) for the __puthujjana__,
it is clear that for the Arahat there can be no renewed existence in the
future. The Arahat has already done away with birth (__jāti__) and
existence (__bhava__) here itself, these never to arise again. Likewise,
it is clear that for the __sekhas__, whatever rebirth awaits them, it
cannot be in spheres of unfortunate or unpleasant experience, for the
simple reason that the key factor which conditions such experience is
out in them - __sakkāyadiṭṭhi__, and that thoughts of 'I' and 'mine'
keep steadily declining in them. __Taṇhā__, desire, attachment - these
factors which upbring all the Suffering are thereby greatly reduced in
the __Sekhas__, and hence Suffering is greatly reduced. Whatever new
existence awaits them after death here, that will be an existence with a
very reduced degree of Suffering. Indicating the magnitude of the
__sotāpanna__'s achievement with a simile, the Buddha points out that
the Suffering the _sotāpanna_ has destroyed is as vast as the earth
whilst the Suffering he will have to endure in the future during a
maximum of a further seven lives is as small as the bit of soil he
placed on his finger nail.footnote:[https://suttacentral.net/sn13.1/en/sujato[SN 13.1: A Fingernail]]
With regard to the relative
value of the __sotāpanna__'s achievement it is said: "Better than sole
kingship of the earth, better than going to heaven, better than supreme
rulership of all the worlds, is the fruit of Stream-entrance
(__Sotāpattiphalaṁ__)."footnote:[https://suttacentral.net/dhp167-178/en/sujato[Dhp 178]]

There are many passages in the __Suttas__footnote:[For examp1e, in https://suttacentral.net/mn135[MN 135]]
where we have the Buddha teaching in a rather
general manner how one is reborn in accordance with one's deeds. That
is, he teaches that the rebirth awaiting a person is _in accordance
with_ his __kamma__.footnote:[https://suttacentral.net/mn136[MN 136]]

It should also be noted that the subject of rebirth need not always
remain a matter of trust in the Buddha. The Buddha has shown the course
by following which one could recollect his own past lives and _see_
other beings dying here and being born there according to their
deeds.footnote:[https://suttacentral.net/mn77[MN 77]] To the individual who has achieved
this vision the subject of rebirth no longer remains a matter of trust
in the Buddha. To such an individual, rebirth is a matter of certainty.
The Buddha said that he himself could recollect the past as far back as
he wished.footnote:[https://suttacentral.net/mn29[MN 29]]

On many an occasion the not yet enlightened monks went to the Buddha,
either for inspiration or from curiosity, and inquired from him as to
where some departed one had been reborn. As one reads through these
passages in the __Suttas__, one imagines the Buddha smiling to himself
at these questions and giving the answers and the reasons for them, as
one who answers children, wishing to soothe them. In the
__Mahāparinibbāna Sutta__footnote:[https://suttacentral.net/dn16[DN 16]] we have him telling
Ananda who asked these questions: "Now there is nothing strange in this,
Ananda, that a human being should die; but that as each one does you
should come to me and inquire about him in this manner - that is
wearisome to me. I will, therefore, preach to you a way of Dhamma called
the Mirror of Dhamma, which if the Ariyan disciple possesses, he may, if
he should so desire, himself predict to himself: Torment is destroyed
for me; so is the animal womb, the _peta_ realm. Destroyed is the
falling into hells, into states of woe. I am __sotāpanna__, I am of the
nature not to fall away, and am assured of attaining the goal of
Enlightenment."

From this statement of the Buddha it would also appear that the
_sotāpanna_ (even though he may not actually _see_ rebirth) has some
sort of self-assurance that whatever rebirth awaits him, it will not be
in an unfortunate sphere. It would not be idle speculation to reflect on
this important characteristic of the _sotāpanna_ and try to see whether
any adequate reason lies for its being so.

The Buddha says that the _sotāpanna_ will not be reborn in the animal
world, the world of the __petas__, and such other unfortunate worlds. Of
these worlds the world best known to us is the animal world. For this
reason, we may limit our discussion to the beings in this world, i.e.,
to the animals.

There is really no _fundamental_ or _basic_ difference between the
_puthujjana_ and the animal in as much as both regard Form, Feeling,
Perception, _Determinations_ and Consciousness as 'mine’. The
_puthujjana_ can however (though perhaps not in all cases) _develop_
himself so as to regard these as ’__not__ mine', in which case of course
he no longer remains a __puthujjana__. This development is not available
to the animal, so that there can be no animal which will be regarding
its Form, Feeling, Perception, _Determinations_ and Consciousness as
'not mine'. The fundamental attitude of the _puthujjana_ and the animal
being the __same__, and the fundamental attitude as between the
_sotāpanna_ and the animal being __opposite__, it would appear that
whilst the _puthujjana_ can be reborn an animal the _sotāpanna_
__cannot__. The fundamental characteristic of the __sotāpanna__'s
mentality being 'not mine', he cannot be born in a realm where the
mentality of each and every being in it has the fundamental
characteristic of regarding things as 'mine'. The realms of the
__petas__, etc, would also appear to be those in which each and every
being possesses this latter mentality.

Viewed from the angle of rebirth it is rather frightening, and it
indicates that the _puthujjana_ is in a perilously insecure position. If
he cannot develop himself to the extent of becoming a _sotāpanna_ he
must at least try his best to understand and practise the Buddha's
Teaching.

One, however, comes across the individual who argues thus: however much
life may be Suffering, I will make the most of it and die; for, why
should I sacrifice all my sense-pleasures and make so great an endeavour
as to tread the Noble Eightfold Path if I cannot get a certain proof
that I shall be reborn when I die?

At first glance, this may appear a practical and sensible argument. But
such an individual is no destroyer of Suffering. Leaving aside the fact
that he does not actually _see_ that life is Suffering, he does not even
see that he has a problem. In him one discerns only a looking for
reasons to support a way of life for which he longs. And even if such a
person be given a certain proof of rebirth such as he may desire, it is
a matter of grave doubt whether he will choose to practise the Buddha's
Teaching or to merely do deeds that he thinks will ensure for him a more
fortunate life hereafter.

What can Buddhism do with such people? It can only wait for them,
patiently and with compassion, until some rude shock has awakened them
to the true characteristics of their existence, when they may come to it
as genuine thinkers.

Rebirth or no rebirth, each and every individual (save of course the
Arahat) is undergoing Suffering. But it is only a very small proportion
that can see even the unsatisfactory and disquieting nature of
existence. And it is only this small proportion that has the potential
to become genuine followers of the Buddha.

In the final analysis, it all comes down to one's attitude towards the
problem of one's own existence. Do I have a _present_ problem which I
must solve in the _present_ itself, or do I not? If I _do have_ such a
prob1em, then all discussions on past lives and future lives can
certainly wait.
