[[ch-99-appendix]]
= Appendix

== I. Mano and Citta

*(a.)* The English word ‘mind’ is rather carelessly used to denote the Pali
terms _mano_ and __citta__. __Mano__, in strict terminology, refers to a
particular base __(āyatana)__ just as much as _cakkhu_ (eye) does. On
the basis of these certain perceptions come about Based on the eye there
is seeing; likewise based on _mano_ there is thinking. That is why the
Buddha always teaches six such bases -- these being the six internal
bases __(ajjattikāni āyatanani)__, viz., eye-base __(cakkhāyatana)__,
ear-base __(sotāyatana)__, nose-base __(ghānāyatana)__, tongue-base
__(jivhāyatana)__, body-base __(kāyāyatana)__ and mind-base
__(manāyatana)__.

The eye-base refers to two very conspicuous round lumps of flesh
situated in the head; the ear-base refers to a membrane called the
ear-drum and a flesh flap projecting out of the head. Likewise, the
mind-base can be considered to be, in the main, what is referred to as
the grey-matter in the head. This description of the mind-base, however,
appears inadequate, for the reason that though there can be no hearing
based on the eye-base or no seeing based on the ear-base (and so with
three other bases), there can be seeing, hearing, smelling, tasting and
touching based on the mind-base. In other words, based on the mind-base
there can be imaginary sights, imaginary sounds, imaginary smells,
imaginary tastes and imaginary touch. Therefore, from this point of
view, the mind-base can also be regarded as a collection of imaginary
internal bases based on which imaginary percepts come about.

Occasionally we find _mano_ being indifferently used to refer to
imagination or thinking in the same manner that the English word ‘mind’
is used to refer to thinking.

*(b.)* _Citta_ refers to thinking or to mentality. The relationship that
_citta_ bears to _mano_ is similar to that which, for instance, the eye
bears to seeing.

Derived from _citta_ is the word _cetasika_ which means __mental__. In
the _Sutta_ we further find a dual classification into _kāyika_ (bodily)
and _cetasika_ (mental). But this is quite different from the erroneous
but common classification called ‘mind-and-body’ (or ‘mind-and-matter’)
wherein mind and body are conceived as two things independent of each
other and together constituting the living individual.

There is also no justification for reckoning _citta_ to be the same as
__viññāṇa__. _Citta_ involves __viññāṇa__. But that does not mean it is
the same as __viññāṇa__.

== II. Manosaṅkhāra and Cittasaṅkhāra

In the _Kukkuravatiya Sutta_ (https://suttacentral.net/mn57/en/bodhi[MN 57]) and else where we
get the triad __kāyasaṅkhāra__, _vacīsaṅkhāra_ and _manosaṅkhāra_ as
against the triad __kāyasaṅkhāra__, _vacīsaṅkhāra_ and _cittasaṅkhāra_
that appears in the _paṭiccasamuppāda_ exemplification. The former
triad, it should be noted, is not the same as the latter.

In the triad __kāyasaṅkhāra__, _vacīsaṅkhāra_ and __manosaṅkhāra__, the
word _saṅkhāra_ refers to _cetanā_ (intention). This can be seen from the Sutta
https://suttacentral.net/sn12.25/en/bodhi[SN 12.25],
where __kāyasaṅkhāra__, _vacīsaṅkhāra_ and _manosaṅkhāra_
refer to __kāyasaṅcetanā__, _vacīsaṅcetanā_ and __manosaṅcetanā__, and
this applies to the use of the triad in the _Kukkuravatiya Sutta_ too.

== III. Attā

It will be seen that the Buddha does not give much weight to the many
speculations regarding ‘self’ __(attā)__. He just dismisses them as
wrong views __(miccādiṭṭhi)__. What he *does* give weight to is the
*notion* of ‘self’, which fundamentally is nothing but a notion of
mastery __(vasa)__, or in other words, a notion of existing **as desired**.
Some thing is considered as ‘self’ means that thing is
considered as being readily amenable to altering its existence to suit
one's wish.

____
If, monks, this body were ‘self’, then you should be able to have ‘Let my body be thus, let my body be not thus’.
____

The same
applies to Feeling, Perception, _Determinations_ and Consciousness. In
the __puthujjana__'s conscious life it is just this notion of mastery
that *leads* him on and not those speculations such as ‘Self is eternal’
or ‘Self is not eternal’ or ‘Self is conscious’, etc. which he indulges
in during his moments of speculation.

The _puthujjana_ can well be
divorced from these speculations, but certainly not from the notion that
he has mastery over the Five Grasping Groups. He is constantly thinking
and acting as if he wields power over these Groups. And the many
speculations about ‘self’ have their origin also in this notion of
mastery, a notion for which the _puthujjana_ has passion. He is
possessed __(pariyuṭṭhaṭṭhāyī)__ by it. His very being is sunk in this
notion. When this notion is removed there is no room whatever for any of
the speculations regarding ‘self’ to arise.

When one sees that this notion of mastery is a false notion, or that one
has really no power over the Grasping Groups to make them behave in
accordance with one's wishes, or again that the Grasping Groups are
Not-self __(anattā)__, then one begins to get tired of them, to get
wearied __(nibbida)__ of them, to be disenchanted with them, to be
detached __(virāga)__ from them. This seeing leads one on
__(opanayika)__ to seeing Suffering and the cessation of Suffering.

This notion of mastery is also immediately visible __(sandiṭṭhika)__ in
one's experience. As against this none of the many speculations about
‘self’ are either _opanayika_ or __sandiṭṭhika__. This should also make
it clear why the Buddha pays hardly any attention to these many
speculations.

Holding to belief in ‘self’ __(attavādupādana)__ is dependent on
__bhava-taṇhā__. The stronger the individual's _bhava-taṇhā_ is the
harder does he adhere to some view or other about ‘self’.

== IV. Saddhā

Saddhā is one of the five faculties, and the Buddha states that; the
_puthujjana_ has none of these faculties. It is, however, sometimes thought that
a _puthujjana_ can have _saddhā_. This is not so. With regard to the Buddha,
Dhamma and Sangha, what such a person may have is what is referred to by the
Sanskrit word _bhakti_, i.e. belief tinged with a certain quantum of emotion, or
at a higher level what he may have is what is referred to in the Suttas as
_cittappasāda_, i.e. gladdening, or being pleased in mind. One can have belief
in a doctrine or be pleased about a doctrine even though one does not really see
it or understand it.

On a certain occasion (obviously when Ānanda was still a _puthujjana_)
the Buddha said that if Ānanda dies just at that time, Ānanda would
be reborn seven times the king of the gods and seven times the king of
India by reason of the _cittappasāda_ Ānanda had towards the Buddha. Note
that the word used is _cittappasāda_ and not _saddhā_.footnote:[https://suttacentral.net/an3.80/en/sujato[AN 3.80]]

_Saddhā_ is born of seeing and understanding the Dhamma, and it exists
alongside the other four faculties of _sati_, _vīriya_, _paññā_, and _samādhi_.
There seems to be no precise English equivalent for this word. The words
‘faith’ and belief do not by themselves always carry the right meaning.
There can be rational faith or irrational faith, rational belief or
irrational belief. _Saddhā_ refers to a particular kind of faith or
belief. It is that faith or belief in the Dhamma which is a result of
seeing and understanding the Dhamma. For example, even though the
_sekha_ does not experience the _amata_ (deathlessness) he has _saddhā_ in the
_amata_; and that is because he sees and understands the _amata_.

== V. Saṅkhāra and Saṅkhata

It is not uncommon to see _saṅkhāra_ being mistaken for _saṅkhata_. _Saṅkhāra_
means something which determines some other thing, whilst _saṅkhata_
refers to that which is determined. Immense difficulty can result if
these two things are confused.

== VI. Nirodha-taṇhā

In the _Sangīti Sutta_ (https://suttacentral.net/dn33/en/sujato[DN 33]) are given three groupings of
_taṇhā_. One group consists of the following three classes of _taṇhā_:
_rūpa-taṇhā_, _arūpa-taṇhā_, and _nirodha-taṇhā_.

_Nirodha_ means cessation.
But, for this reason it must not be thought that _nirodha-taṇhā_ means
_taṇhā_ for _Nibbāna_. _Nibbāna_ is _taṇhakkhaya_, i.e. it is the destruction of
_taṇhā_. _Taṇhā_ refers to the _puthujjana's_ wanting, and that is essentially
a wanting sense-pleasure and ‘self’-existence.

To have _taṇhā_ for _Nibbāna_ means to have _taṇhā_ for the destruction of
_taṇhā_. In other words it means to want sense-pleasure and
‘self’-existence so as to destroy wanting sense-pleasure and
‘self’-existence. Such a state of affairs cannot be.

In the same _Sutta_ are mentioned nine kinds of _nirodha_, the first being
_kāma-sañña nirodha_ (cessation of the perception of sense-pleasure),
which is a characteristic of the first _jhāna_. _Taṇhā_ for this cessation,
viz. the cessation of the perception of sense-pleasure, is really a
_taṇhā_ for ‘self’-existence in the first _jhāna_.

Thus _nirodha-taṇhā_ is a
negative form of the positive _bhava-taṇhā_. It is like saying that a
person wants the cessation of unpleasant feeling so that his existence
comprises only pleasant and neutral feeling. When he says he wants the
cessation of unpleasant feeling what he really means is that he wants
the existence of pleasant and neutral feeling. His wanting a particular
positive existence is put in the form of wanting a certain thing to be
absent in his existence. _Nirodha-taṇhā_ therefore means _taṇhā_ for that
_bhava_ wherein the specified thing has ceased.

== VII. Vibhava-taṇhā

[[vibhava-tanha]]Apart from _avijjā_, what really lies at the bottom of _vibhava-taṇhā_ is
a _dissatisfaction_ with the past, present and expected future experience.
The _puthujjana_ is dissatisfied with his past; he is dissatisfied with
the present; and he cannot see any satisfaction in the future which he
knows will be decay and death. In other words, he is dissatisfied with
the _sakkāya_, past, present and future.

Unfortunately, he knows no *escape* from the _sakkāya_. He does not know
_sakkāyanirodha_. Under the circumstances he seeks consolation by doubting
the reality of the _sakkāya_ which of course is nothing but a doubting the
reality of his own existence; and on this basis he logically tries to
find a way out. In this attempt he gets very close to the view of **no existence**.
Nevertheless, having _sakkāyadiṭṭhi_, he cannot doubtlessly
accept that he does not exist.

He is therefore caught in a duality -- the
duality of *is* and *is not* -- a duality which in extremist thinking points
to eternalism __(sasata)__ on the one hand and to nihilism __(uccedha)__ on the
other. So, without applying his view of nihilism to present living he
goes beyond __(atidhāvati)__ and applies it to a future time, i.e. to after
death. He does so because he thinks he has better reason to apply his
view to after death than to present living. He therefore consoles
himself and falls into complacency by thinking that he will be fully and
completely cut off at death. Actually he is not convinced about it, and
he has fears regarding the matter. But at least he finds some
consolation in thinking that everything is completely over at death.

_Vibhava-taṇhā_ is the wanting a complete cutting off of the _sakkāya_ at
death. But this kind of _taṇhā_ is as undesirable as _bhava-taṇhā_ because
it does not give one any opportunity whatsoever to experience
_sakkāyanirodha_ which is nothing but the experience of the cessation of
Suffering. Let alone *experiencing* the cessation of Suffering it does not
give one any opportunity whatsoever to even *see* the cessation of
Suffering. _Vibhava-taṇhā_ will merely keep Suffering going on till death.
It cannot bring Suffering to an end. One's present problem of Suffering
just remains with no prospect whatever of a solution.

== VIII. Puthujjana

When the _puthujjana_ experiences Suffering (i.e. when he is grieved, or
agitated, or worried, etc.) at a time he is considering some particular
thing as ‘mine’, he attempts to get away from that Suffering not by
considering that *same* thing as ‘not mine’ but by switching his mind over
to considering some *other* thing as ‘mine’. Considering this other thing
as ‘mine’ may give him less Suffering, and also provide him with some
kind of temporary relief; but he is basically continuing to regard
things as ‘mine’. Whether it is *this* that he is considering as ‘mine’ or
whether it is **that**, it hardly matters. What matters is that the
considerations ‘mine’ is persisting in him unbroken. Thus he is in no
way going towards the extinction of Suffering as the Ariyan disciple who
considers things as ‘not mine’ is.

One must even for a brief period consider some thing which one has
been considering as ‘mine’ as ‘not mine’. One can then experience its
telling effect -- how the agitation, worry, fear, etc. that were present
at the time of considering it as ‘mine’ immediately subside as the
considering of it as ‘not mine’ sets in.

Incidentally, we have said that ‘mine’ points to ‘I’. Expanded, this
statement would be: ‘is mine’ points to ‘I am’. Since ‘is mine’ is the
same as ‘for me’ (in fact the Pali word *me* refers to both ‘mine’ and
‘for me’), we also have ‘for me’ points to ‘I am’. The _puthujjana_ sees
these things the other way about.

== IX. Upādisesa

_Upādisesa_ means ‘residue’, or ‘that which is remaining’.

However, we find this word used in the Suttas to refer to two different
things that remain. Usually it refers to the _pañcakkhandha_ (the Five
Groups) which is what is remaining with regard to the Arahat. But, for
instance, in the _Satipatthāna Sutta_ (https://suttacentral.net/mn10/en/sujato[MN 10]) it is used to
refer to that which remains with regard to the _anāgāmi_. In the former
case it denotes the difference between _sa-upādisesa nibbānadhātu_ and
__anupādisesa nibbānadhātu__.footnote:[See <<ch-13-nibbana.adoc#remainder,Chapter 13: Nibbāna, ‘Now, Arahatship as we saw...’>>]
In the latter case it denotes
the difference between the _anāgāmi_ and the Arahat. These two differences
are by no means the same. Thus, the word _upādisesa_ does not specify *what*
remains. For this reason Ñāṇavīra Thera considers that _upādisesa_ must be
*unspecified* residue.

== X. Upādāya rūpaṁ

With reference to the _rūpupādānakkhanda_ in the _pañcupādānakkhandha_ we
get the phrase _upādāya rūpaṁ_. This phrase which means ‘by grasping _rūpa_’
is often seen translated as ‘derived from _rūpa_’, or as ‘because of
_rūpa_’, or again as ‘by-product of _rūpa_’. This is seriously misleading for
with regard to the first Group, it immediately shuts the door to the
problem of Suffering and the cessation of Suffering.

In the __Upādāna Paripavatta Sutta__ (https://suttacentral.net/sn22.56/en/bodhi[SN 22.56]) we get the following passages:

____
__Katamañca, bhikkhave, rūpaṁ? Cattāro ca mahābhūtā catunnañca mahābhūtānaṁ upādāya rūpaṁ. Idaṁ vuccati, bhikkhave, rūpaṁ. Āhārasamudayā rūpasamudayo; āhāranirodhā rūpanirodho. Ayameva ariyo aṭṭhaṅgiko maggo rūpanirodhagāminī paṭipadā, seyyathidaṁ -- sammādiṭṭhi ... pe ... sammāsamādhi.__

__Ye hi keci, bhikkhave, samaṇā vā brāhmaṇā vā evaṁ rūpaṁ abhiññāya, evaṁ rūpasamudayaṁ abhiññāya, evaṁ rūpanirodhaṁ abhiññāya, evaṁ rūpanirodhagāminiṁ paṭipadaṁ abhiññāya rūpassa nibbidāya virāgāya nirodhāya paṭipannā, te suppaṭipannā. Ye suppaṭipannā, te imasmiṁ dhammavinaye gādhanti.__
____

The translation would be:

____
What, monks, is rūpa ? The Four Primary Modes and that _rūpa_ by
grasping the Four Primary Modes -- this, monks, is called _rūpa_. By the
arising of the nutriment, the arising of _rūpa_; by the cessation of the
nutriment, the cessation of _rūpa_. The path that leads to the cessation
of _rūpa_ is this Noble Eightfold Path; that is to say, right view ... right concentration.

Whosoever recluses and brahmins, monks, having fully understood _rūpa_
thus, having fully understood the arising of _rūpa_ thus, having fully
understood the cessation of _rūpa_ thus, having understood the path
leading to the cessation of _rūpa_ thus, have attained to weariness, to
detachment, to cessation of _rūpa_, they have well attained. Whosoever have
well attained, they are grounded in this Dhamma and Discipline.
____

At once we see the Buddha indicating the arising of Suffering and the
cessation of Suffering with regard to _rūpa_. The Suffering is in the
_upādāya_ i.e. in the Grasping; and the cessation of Suffering is in the
_abhiññāya_ i.e. in the fully understanding.

Certain other Sutta passages concerning _rūpa_ are those defining the Four Primary Modes.
One such passage (defining the Earth Mode in https://suttacentral.net/mn140/en/bodhi[MN 140]) is:

____
__Katamā ca, bhikkhu, pathavīdhātu?
Pathavīdhātu siyā ajjhattikā siyā bāhirā.
Katamā ca, bhikkhu, ajjhattikā pathavīdhātu?
Yaṁ ajjhattaṁ paccattaṁ kakkhaḷaṁ kharigataṁ upādinnaṁ, seyyathidaṁ --
kesā lomā nakhā dantā taco maṁsaṁ nhāru aṭṭhi aṭṭhimiñjaṁ vakkaṁ hadayaṁ yakanaṁ kilomakaṁ pihakaṁ papphāsaṁ antaṁ antaguṇaṁ udariyaṁ karīsaṁ,
yaṁ vā panaññampi kiñci ajjhattaṁ paccattaṁ kakkhaḷaṁ kharigataṁ upādinnaṁ --
ayaṁ vuccati, bhikkhu, ajjhattikā pathavīdhātu.
Yā ceva kho pana ajjhattikā pathavīdhātu yā ca bāhirā pathavīdhātu pathavīdhāturevesā.
‘Taṁ netaṁ mama nesohamasmi na meso attā'ti -- evametaṁ yathābhūtaṁ sammappaññāya daṭṭhabbaṁ.
Evametaṁ yathābhūtaṁ sammappaññāya disvā pathavīdhātuyā nibbindati, pathavīdhātuyā cittaṁ virājeti.__
____

The translation would be:

____
And what, monks, is the Earth-Mode? The Earth-Mode may be internal, may
be external. And what, monks, is the internal Earth-Mode? Whatever is
hard, solid, is internal, grasped by oneself, that is to say: the hair of
the head, the hair of the body, nails, teeth, skin, flesh, sinews,
bones, marrow of the bones, kidneys, heart, liver, pleura, spleen,
lungs, intestines, mesentery, stomach, excrement, or whatever other
thing is hard, solid, is internal, grasped by oneself -- this, monks, is
called the internal Earth-Mode. Whatever is the internal Earth-Mode and
whatever is the external Earth-Mode, just these are the Earth-Mode. By
wisdom this should be regarded as it really is, thus: ‘Not, this is
mine; not, this am I; not, this is my self.’ Having by wisdom seen this
thus as it really is, he wearies himself of the Earth-Mode, he detaches
his thinking from the Earth-Mode.
____

Here again, we see the Buddha indicating Suffering and its cessation.
The latter part of this passage wherein the Buddha exhorts the disciple
to regard the Mode as ‘Not, this is mine; not, this am I; not, this is
my self’ and thereby detach his thinking __(cittaṁ virājeti)__ from the Mode
has meaning *only* from the fact of the Mode being grasped __(upādinnaṁ)__.

If the word _upādinnaṁ_ is reckoned to mean ‘because of’ or ‘derived from’
the whole meaning and purpose of the Sutta passage is lost. It is
because the Mode is grasped (i.e. it is considered as ‘mine’ and the
individual has attachment __(rāga)__ to it) that he has to regard it as
‘Not, this is mine; not, this am I; not, this is my self’ and get
detached from it.

In the _Kamma Sutta_ (https://suttacentral.net/sn35.146/en/bodhi[SN 35.146])
the phrase _anukampaṁ upādāya_ appears.

It means ‘taking up sympathy’. But we should not take _upādāya_ herein precisely the same
sense in which the word is used in reference to the _pañcupādānakkhandha_
The Arahat takes sympathy, but that does not mean he takes sympathy in
the sense of considering sympathy as ‘mine’. There is no ‘**my** sympathy’
or ‘**I am** in sympathy’ with the Arahat. In the phrase _anukampaṁ upādāya_
the word _upādāya_ is rather indifferently used. It is again due to that
elasticity of language, often present in dialogue.

Another place where
the word _upādāna_ is used without bring given exactly the same meaning as
in _pañcupādānakkhandha_ is the _Aggivacchagotta Sutta_ (https://suttacentral.net/mn72/en/thanissaro[MN 72]).
In this Sutta we get the phrase _ayaṁ aggi tiṇakaṭṭhupādānaṁ paṭicca jalatī_,
which means, ‘this fire is burning dependent on taking up
grass and sticks.’ Perhaps, the use of _upādāya_ and _upādāna_ in such
places has been one of the reasons for thinking that in the phrase
_upādāya rūpaṁ_ too the word _upādāya_ need not be taken in the same sense
in which it is to be taken in reference to the _pañcupādānakkhandha_.

== XI. Invalid Questions

What happens to the Arahat after death? Does he exist? Does he not exist? etc.

The Buddha says that these questions, likewise such questions as, ‘Does
self exist? Does self not exist? Is the world eternal? Is the world not
eternal?’ Are asked through not understanding the Dhamma, or through
delighting in and being attached to the Groups
(See https://suttacentral.net/sn33.1/en/sujato[SN 33.1] and https://suttacentral.net/sn44.6/en/bodhi[SN 44.6]).

The person who asks the question as to what will happen to the Arahat
after death is really asking the following question: ‘What will happen to
*me* after death if *I* become Arahat?’ It is an answer to *this* question
that he is really seeking. The attachment to the Groups lies latent and
unnoticed by the questioner. Although in the question, the questioner
does not indicate the involvement of any subjectivity (i.e. he does not
indicate in the question that he himself is involved), the fact is that
*he* as a subject *is* involved. *He* wants to know what will happen to *him*
after death if *he* becomes Arahat.

Since the questioner is a _puthujjana_
the question appears valid *to him*, and so he keeps on asking it. Not
seeing the _pañcupādānakkhandha_ as _pañcupādānakkhandha_ and the
_pañcakkhandha_ as _pañcakkhandha_ he puts forth these questions. But if he
does see the _pañcupādānakkhandha_ and the _pañcakkhandha_ he cannot and
will not ask these questions, for he then knows that since all
subjectivity and attachment are extinct with the Arahat, they are
invalid questions. Actually, the thinking of one who sees the Dhamma
does not go beyond Arahatship.

The _puthujjana_, whether he be a philosopher, ethicist, ascetic, or
anyone else, does not see that these questions about the Arahat, self
and the world are unjustified. He assumes he is justified in asking them,
and so he keeps on asking them. At the same time he sees that *no* answer
to any one of them is justifiable. He can proceed no further, and so his
thinking ends in frustration.

The Buddha also does not answer these questions. But he shows *how* and
*why* they arise. When this is seen the invalidity of the questions is
seen. When their invalidity is seen the questions are no longer asked.
Thus does the Buddha rescue the thinker from frustration -- not by
answering unanswerable questions, but by bringing him to the *cessation*
of all such questions. That is also why the Buddha's Teaching is ‘beyond
the world’ __(lokuttara)__. It is beyond the world of the _puthujjana_, and
hence beyond his comprehension.

== XII. Dassana

ln the _Sabbāsava Sutta_ (https://suttacentral.net/mn2/en/bodhi[MN 2]), it is said that adherence to
rites and ritual, doubt, and ‘person’-view are to be laid aside by *seeing* __(dassana)__.

This means, that one has to *see* that adherence to rites and ritual,
doubt (about the Dhamma), and having ‘person’-view prevent the cessation
of Suffering. This *seeing* is not quite as easy and simple as it would
appear to be. It is not to be achieved through a process of conceptual
or logical thinking. Nor is it to be achieved by any kind of scholarly
analysis. Only a sustained effort at looking deep down into the very
depths of one's own personal existence, can bring about this **seeing**.
Actually, with this seeing the Four Noble Truths are also seen; and this
is what is meant by the arising of the Dhamma-Eye __(dhammacakkhuṁ udapādi)__.

Further if one is to enter the Path adherence to rites and ritual, doubt
and ‘person’-view must be done away with. For this reason it is a
matter of the highest importance.

== XIII. Rebirth

It should be noted that the Suttas do not explain *how* rebirth takes
place. They only tell us that so long as a being dies with Ignorance and
_taṇhā_ there is a new _bhavā_ springing up.

Conceptually thinking out *how* rebirth takes place (the mechanics of it,
so to say), with connections in time and space, will not help. And any
attempt to do so can do more harm than good (as in fact has happened,
e.g. **by going beyond the Suttas** and introducing the concept of a _paṭisandhi viññāṇa_).

What one *has* to do, as the Buddha says, is to see
and understand one's present Suffering, how it arises, how it ceases,
and the way to its cessation, and thereby reach the Path. The individual
who accomplishes this task will know that whatsoever rebirth will befall
him cannot be in an unfortunate sphere; and that, **for him**, is the most
important knowledge regarding rebirth. It is also a matter of experience
that as one begins to see Suffering and its cessation, one's thoughts
about rebirth (which are purely speculative unless one **sees** rebirth)
begin to recede into the background. In fact the phenomenon of rebirth
itself causes little concern to such a one.

It should also be noted that the more one tries to make the Buddha's
Teaching a subject for scholarship the more confused one will become.
Subjects like rebirth will continue to bother such an individual.
Unanswerable questions about self and the world will continue to worry
him. In short he will remain in the same state of Suffering, and with no
prospect of reducing it.

The Buddha's Teaching is a medicine to be taken -- a medicine, in the
taking of which one experiences its healing effect. As a patient trusts
the physician and takes the medicine, so must one trust the Buddha and
follow his advice and guidance.

____
Let be the past, let be the future, I will preach to you the Dhamma.

__Tiṭṭhatu pubbanto tiṭṭhatu aparanto dhammaṁ te desessāmi.__
____

== XIV. OPANAYIKA

The Buddha said that the Dhamma is well said __(svākhāto)__ and leading on
__(opanayiko)__. It leads on to seeing Suffering and the cessation of
Suffering, and of course to the subsequent experiencing of the cessation
of Suffering. These characteristics of the Dhamma, which are well
portrayed in the Suttas, are however missing in a very large part of the
Abhidhamma.

A knowledge of the large number of _cetasika_ said to be
present in a particular _citta_ is not all that conducive to solving the
problem of Suffering, which is not a problem whose solution can be seen
by pure and simple analysis, however vast and imposing that analysis be.
Analysis for the sake of analysis gets one nowhere. It only results in
frustration. Add to this the Abhidhamma also incorporates a rather
misleading doctrine referred to as the _cittavīthi_ (‘cognitive series’).
It is difficult to see how these doctrines are _opanayika_. If they are not
_opanayika_, they are also not of much use.
